docs/user-guide/troubleshootinstall.md
removed
`sudo npm install -g` command fails with an `EPERM` error
=> removed `sudo npm install -g` command fails with an `EPERM` error

docs/user-guide/introduction.md, docs/user-guide/mvd-errorreportingui.md, docs/user-guide/mvd-uribroker.md, docs/user-guide/mvd-zluxconfiguration.md
Fixed broken link to point to "usingzlux" topic
Accessing the uri broker link should say "virtual..."
in zlux config topic, removed old link (should just be a folder name).
Fix code samples in terminal config and error reporting topics
=> fixed code samples and a broken link

docs/user-guide/api-mediation/api-mediation-onboard-an-existing-rest-api-service-without-code-changes.md
This PR adds instructions how to add static API definition to the Zowe runtime.
Resolves https://github.com/gizafoundation/api-layer/issues/83
=> Add instructions how to define static API to the Zowe runtime

docs/user-guide/cli-configuringcli.md, docs/user-guide/systemrequirements.md
Update supported platforms - we support any OS that runs Node.js 8 or 10. 
Also corrected the names of the Zowe CLI environment variables.
=> Fix prereq

docs/.vuepress/config.js, docs/user-guide/Zowe_User_Guide.ditamap, docs/user-guide/cli-extending.md, docs/user-guide/cli-installcli.md, docs/user-guide/cli-vscodeplugin.md, docs/user-guide/overview.md, docs/user-guide/summaryofchanges.md, docs/user-guide/systemrequirements.md
- Introduce VSCode article cli-vscodeplugin.md
- Describe the extension in the parent topic cli-extending.md
- Parent topic now mentions that some extensions are not into the CLI, but built on the CLI
- Mention and links to topic in the Overview section, overview.md 
- Added to TOC in config.js, Extending Zowe CLI section
- Added to DITAMAP
Recommend a general content review.
=> Vs code plugin

docs/user-guide/install-zos.md, docs/user-guide/troubleshootinstall.md
1.  I added descriptions of the pre- and post-install verification scripts and how to use them.
2.  I fixed a typo in `troubleshootinstall.md`
=> Add pre- and post-install verify script descriptions

docs/README.md
"Extending" button on home page pointed to incomplete article. For now, I pointed it to the first topic under Extending.
=> fix link on home page 

docs/extend/extend-apiml/api-mediation-onboard-an-existing-java-jersey-rest-api-service.md
Get rid of some reference to obsolete enabler for jersey who was removed and updated instructions for .yml files instead of .properties.
=> update doc for jersey

docs/.vuepress/config.js, docs/extend/extend-desktop/mvd-configdataservice.md, docs/extend/extend-desktop/mvd-creatingappplugins.md, docs/extend/extend-desktop/mvd-dataservices.md, docs/extend/extend-desktop/mvd-plugindefandstruct.md, docs/extend/extend-desktop/react-sample.md, docs/extend/extend-desktop/zlux-app-server.md, docs/extend/extend-desktop/zlux-workshop-user-browser.md, docs/user-guide/mvd-configuration.md
Renamed zlux-example-server to zlux-app-server (includes one file name change and a change to the config.js) Also renamed zlux-proxy-server to zlux-server-framework
=> Renamed zlux-example-server and  zlux-proxy-server

docs/extend/extend-apiml/api-mediation-onboard-an-existing-java-jersey-rest-api-service.md
Remove any reference to old `mfaas-integration-enabler-jersey` and replace it with `mfaas-integration-enabler-java` since the first one is not used anymore.
=> Change reference name of jersey enabler

docs/user-guide/systemrequirements.md
Per issue #253 , updated the Node.js version to be 6.14.4.1 and later. 
@armstro Hi Bruce, the doc now still points users to https://developer.ibm.com/node/sdk/ztp/ but  updated the version number for Node.js. As it's some time since this issue was opened, any updates about this issue? Will this doc update suffice? Thanks!
=> Update the Node.js version

docs/user-guide/install-zos.md
The documentation should use the P (stop) operator command when describing the steps to stop the ZSS Cross-Memory server. Normally, the C (cancel) command should not be used to terminate it - it triggers the address space resource manager which disables the PC routines but does not perform the full clean up process. The clients that try to call such server may receive unexpected return codes, instead of the normal "server not running" response.
=> Fix wrong termination command for the cross-memory server

docs/user-guide/install-zos.md
2 commits to fix hyperlinks identified in #402
=> Fixed typos in two links in Installing Zowe

docs/user-guide/cli-usingcli.md
Add a new heading and link to the [CLI Reference document in the zowe-cli repository](https://github.com/zowe/zowe-cli/blob/master/docs/CLIReadme.md)
=> add cli reference link

docs/.vuepress/config.js, docs/.vuepress/theme/styles/config.styl
Added the Feedback link to the nav bar to collect user feedback. 
Hi Jack @jackjia-ibm , wondering if you know a way to add this link to each page, right after the Propose content change in GitHub link?  This link goes to a documentation survey form. Thanks in advance!
=> Add Feedback link to doc site

docs/user-guide/systemrequirements.md
- Cleaned up some extra text in the CLI section to make the page easier to consume. 
- added "not required for CLI" to certain prereqs. Users are getting confused and thinking that they need Node on z/OS in order to use the CLI alone. 
Signed-off-by: BrandonJenkins14 <brandon.jenkins@broadcom.com>
=> clarify prereqs not for CLI

docs/user-guide/systemrequirements.md
This is to backport the system requirement updates to the previous version.
=> Backport system requirement fixes to v1.0.x doc

docs/extend/extend-desktop/mvd-plugindefandstruct.md
The compressed-file-support branch was to add a small section to the Extending chapter that explained that applications can now be packaged as gzip and brotli compressed files in the /web directory.
=> Added language on new gzip and brotli compressed file support.

docs/user-guide/cli-cicsplugin.md, docs/user-guide/cli-db2plugin.md
Fixed syntax problems for #508 
Signed-off-by: BrandonJenkins14 <brandon.jenkins@broadcom.com>
=> fix incorrect syntax for cics and db2 validate command

docs/user-guide/cli-configuringcli.md
To complete #192 
- Added <> around command execution arguments
- Fixed typo on ... ***accesses*** API Mediation ...
=> An example for Create a Zowe CLI profile (issue #192)

docs/user-guide/install-zos.md
As @brooklynakos pointed out, the doc didn't have the ```-X``` argument. The [install script](https://github.com/zowe/zowe-install-packaging/blob/master/scripts/zss/zowe-xmem-deploy-loadmodule.sh#L46) does have it ([sample from IBM](https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.3.0/com.ibm.zos.v2r3.bpxa400/cpexfile.htm)). This pull-request adds ```-X``` to the command in the documentation.
=> Update the cp command to match the install script

docs/README.md
CLI reference guide is in-demand, but is easily missed. Add a button so that the download is more prominent.
Consider future changes to home page design - how can we make more content visible without scrolling, or highlight popular topics, without cluttering the page?
=> Button for CLI Ref download

docs/user-guide/cli-configuringcli.md, docs/user-guide/cli-usingcli.md
1. There is no longer a `zowe help explain profiles` command. Removed references in doc. 
2. Profiles are no longer required - they are optional. Removed outdated language about this. 
Signed-off-by: BrandonJenkins14 <brandon.jenkins@broadcom.com>
=> fix outdated information about profiles

docs/getting-started/cli-getting-started.md
Attempted to make the order and sample values of params for the command examples more consistent. Not sure however which values should be preferred for consistency, like username for example (`user123`, `myusername123`, or `ibmuser`).
=> Make command examples in quick start guide more consistent

docs/user-guide/cli-configuringcli.md
Fixes #462  and fixes #468 
- Introduces new topic "Certificate security"
- Adds notes about certificate security to "Create Zowe CLI Profiles" + link to new topic.
- Adds note about certificate security to "Testing Zowe CLI connection to z/OSMF" + link to new topic
Worked with @dkelosky  to understand the use cases. @JamesBauman , feel free to look it over.
=> Certificate security w/ CLI topic

docs/.vuepress/config.js, docs/README.md, docs/getting-started/freqaskques.md
Moved the FAQs content from [https://zowe.org/faq/](https://zowe.org/faq) to the Getting Started > Zowe FAQs section on docs-site. We already had CLI-specific FAQs in the doc site, so I generalized the name of the existing topic, added the general FAQs, and moved the CLI content to the bottom. 
**Notes:**
- @Tbr00ksy can you please confirm that the content is accurate and useful in your opinion? Feel free to tag others who might want to add or adjust the content.
- I made changes, such as removing some future-tense references to what Zowe "will do", as this content was written pre-GA, fixing grammar, and adding relevant links. 
- Doc Squad, please build this and see if the format/style is OK. Open to suggestions/improvement. 
Fixes #559
=> Move FAQ content from Zowe.org

docs/user-guide/install-zos.md
- Fixed the install directory name. Now all uses `$INSTALL_DIR`
- Fixed two typos
- Reworded one sentence
- Updated the commands to locate the zowe-config-stc.sh script
=> #606 Fix the directory name issue and some typos

docs/troubleshoot/cli/cli-issue.md, docs/troubleshoot/cli/mustgather-cli.md, docs/troubleshoot/cli/troubleshoot-cli.md, docs/troubleshoot/cli/zosmf-cli.md
- Fixed a list that is displayed in blank on the doc site. Removed the extra spaces.
- Changed to second person for some descriptions. It targets at users so used "you".
- Some other small enhancements.
=> Some fixes to the Zowe CLI troubleshooting

docs/.vuepress/config.js, docs/README.md
- Removed the `Feedback` link on the top navbar
- Moved the feedback section to the homepage
- Changed `Appendix` to `References` 
- Added the link to the CLI reference guide to the `References` drop down list
=> Update TOC of docs

docs/README.md, docs/getting-started/freqaskques.md, docs/user-guide/cli-installcli.md, docs/user-guide/install-zos.md, docs/user-guide/update-zos.md
The download link has changed after zowe.org is refreshed.
=> Fix the download link on master branch

docs/user-guide/systemrequirements-zosmf.md
Removed "Technologies"  from the names of the CA security products reverenced in the article.
Updated the target URLs to point to the techdocs versions of the URLs. 
Resolves issue #670
=> Acf2 tss iss670

gh-pages-default/404.html
https://docs.zowe.org/latest/ will show a 404 page without any redirecting help information. This change will fix it.
=> allow to check https://docs.zowe.org/latest/ without following path

docs/getting-started/summaryofchanges.md
summary of changes contained a link to the title of the article... removed
=> Fix mini-ToC in the summary of changes article

docs/user-guide/mvd-configuration.md
There was no mention of core and "other" dataservices, only configuration. In the context of applying RBAC to endpoints explained the three types of service and that you use CFG, COR, or SVC in your SAF profiles depending on which one you're applying the profile to.
=> Doc cor and svc dataservices (mvd 3356)

docs/user-guide/install-zowe-zos-convenience-build.md
The verify build information is the same as that on zowe.org. Also we point users to the post-download page to fetch some files, so it makes sense to leave the information in only one location. The repetitive info on doc site is being removed now. Instead, a link is provided for users to get the instructions.
=> Reduce repetitive information

docs/user-guide/configure-zowe-runtime.md
Signed-off-by: nannanli <nannanli@cn.ibm.com> 
The fix applies to V1.5.0 and later releases.
Fixes: https://github.com/zowe/docs-site/issues/725
=> doc: Updated out-of-date STC naming scheme

docs/.vuepress/versions.json
Updated versions.jason. Adding a link to the Versions drop that lets users open the newly created Active Development documentation.
Signed-off-by: jamesbauman <james.bauman@broadcom.com>
=> Add "Active Development" to v1.0 versions drop-down

docs/.vuepress/versions.json
Updated versions.jason. Adding a link to the Versions drop that lets users open the newly created Active Development documentation.
Signed-off-by: jamesbauman <james.bauman@broadcom.com>
=> Add "Active Development" to v1.1 versions drop-down

docs/.vuepress/versions.json
Updated versions.jason. Adding a link to the Versions drop that lets users open the newly created Active Development documentation.
Signed-off-by: jamesbauman <james.bauman@broadcom.com>
=> Add "Active Development" to v1.2 Versions drop-down

docs/.vuepress/versions.json
Updated versions.jason. Adding a link to the Versions drop that lets users open the newly created Active Development documentation.
Signed-off-by: jamesbauman <james.bauman@broadcom.com>
=> Add "Active Development" to v1.3 Versions drop-down

docs/user-guide/install-nodejs-zos.md
Fixes: #774 
In v1.4.x doc, we stated support of node V8.
=> Propagate the Node v8.16.1 warning change to 1.5.x

docs/user-guide/install-nodejs-zos.md
Fixes: #774
In v1.4.x doc, we stated support of node V8.
=> Propagate the Node v8.16.1 warning change to 1.4.x

docs/troubleshoot/app-framework/app-known-issues.md
Added two NodeJS issues to the App Framework Troubleshooting section. 
Note: The branch name is a little deceptive, only one of the issues is about the [regression bug in NodeJS 1.86.1](https://github.com/ibmruntimes/node/issues/142). The other comes from a Rocket service desk call (Jira ticket RIT-28761).
=> Added two NodsJS issues to framework troubleshooting

docs/user-guide/cli-db2plugin.md, docs/user-guide/cli-extending.md
- Added "Database" to "IBM Db2 Plug-in for Zowe CLI" 
- Added copyright symbols
=> Db2 slight rebrand

docs/getting-started/summaryofchanges.md
The name of the VSC extension was changed. Reflecting this in release notes. 
=> add vsc name change

docs/user-guide/install-nodejs-zos.md
Node 8.16.2 is available which fixes the 8.16.1 issue so update the docs to remove the ref to need 8.16.0
Issue number: #890
=> docs: Remove reference to node.js issue in v1.6.x

docs/user-guide/install-nodejs-zos.md
Issue number: #890 
- Added back the known issue with node v8.16.1 for 8.16.1 is still not supported.
- Updated the workaround to guide users to use v8.16.2.
- State that v12 is not supported yet.
=> docs: Update description about node v8.16.1 issue and workaround in v1.6.x

docs/user-guide/cli-usingcli.md
Porting #883  (prompt feature) to active-development version. The feature is not available in @lts-incremental so we will close #883.
=> Prompt feature for active-dev

docs/user-guide/configure-instance-directory.md
Made several changes to improve technical accuracy, including changing references from USS to zFS when discussing files/directories and adjusting 3270 Terminal naming, to remove "TN" where it would be misleading and confusing. Also added some basic security advice.
Issue number: #977
=> Update configure-instance-directory.md: zFS and 3270

docs/user-guide/cli-installcli.md
Current Node.js pre-req formulation doesn't reflect the requirement precisely enough. We need to specify that we support LTS versions starting from Node v12. Also, a list of supported Node version is added.
=> Node.js pre-req formulation change

docs/getting-started/summaryofchanges.md, docs/user-guide/cli-vscodeplugin.md
Update the [Zowe Explorer](https://docs.zowe.org/stable/user-guide/cli-vscodeplugin.html) page to include the second part of Zowe Explorer video.
Issue number: [944](https://github.com/zowe/docs-site/issues/944)
=> Zowe Explorer video part 2, doc update

docs/user-guide/api-mediation-api-catalog.md, docs/user-guide/cli-usingcli.md
Fixes heading levels that were inconsistent.
=> Fix heading and toc in Using CLI

docs/user-guide/mvd-configuration.md
A section about configuring TN3270 and VT apps was inadvertently removed in a previous release. Reintroducing the content, which is still needed. 
**Note:**  You might want to duplicate this and create PRs to fix in both the 1.8.x and 1.9.x archived doc branches.
=> Reintroduce app config doc

docs/getting-started/summaryofchanges.md
Add CLI Release Notes entry for v1.10.0: 
- CLI changelogs are now automatically generated from PRs in each GitHub repository (Thx @awharn @zFernand0 @tjohnsonBCM) 
- Highlight the SCS plugin fix
=> Cli Release Notes 1.10.0

docs/troubleshoot/app-framework/app-known-issues.md
Log location specific is outdated (pre 1.8), and nodejs issue does not recommend node 12, which is honestly the best one to use these days.
Signed-off-by: 1000TurquoisePogs <sgrady@rocketsoftware.com>
=> Log location, nodejs version suggestion fixes

README.md, docs/.vuepress/versions.json
Removing the Active Development documentation from the live doc site.
**Reason:** Active Development CLI package on Zowe.org is outdated and should be removed. zowe/zowe.github.io#91 is open to remove the package. We can reintroduce it when more forward features are added to @latest CLI or another Zowe component.
**Note:** Port  this change to archived doc branches.
=> Remove active dev from versions

docs/user-guide/cli-updatingcli.md
The command to uninstall Zowe CLI was incorectly doc'd as `zowe` command. In reality it is an `npm` command. Fixing that here.
=> Fix NPM command syntax

docs/troubleshoot/app-framework/app-troubleshoot.md
ZWED0159W errors are in troublehooting as they are silent and can be ignored, however they don't get logged in 1.11
=> Doc that ZWED0159W errors don't occur in 1.11

docs/user-guide/cli-usingcli.md
Command to list all commands (`zowe --help --ac`) was missing from Docs. Adding example to the Get Help w/ CLI section.
=> Add --help --ac command

docs/user-guide/systemrequirements.md
Issue number: #1210 
Updated the system requirements to make it clearer that CLI on z/OS doesn't support DB2 and Secure Credentials plugin
=> system requirements changed

docs/user-guide/cli-configuringcli.md
Remove / from env var examples in Configuring CLI.
=> Fix env var syntax

docs/user-guide/install-nodejs-zos.md
https://github.com/zowe/docs-site/issues/1238
=> Update Supported Node.js versions to mention v6 EOS in September 2020

docs/user-guide/install-nodejs-zos.md
fixes #1251
- Updated PTF and APAR numbers for supported node versions
- Updated end of support statement for v6 to remove duplication
- Removed reference to `evaluation`
=> Correct node.js PTF information

docs/extend/extend-apiml/custom-metadata.md, docs/extend/extend-apiml/onboard-direct-eureka-call.md
Parameter that will allow retry per service on specific status code for all http methods.
=> new parameter that will allow services to set retry for all HTTP methods

docs/getting-started/summaryofchanges.md
Web Help PDF was not displaying correctly in doc site. Replaced the file. 
Fixed inconsistent spacing in the CLI section of Release Notes.
=> Fix Web Help PDF and spacing in RN

docs/user-guide/cli-updatingcli.md
Addresses #1307 
When updating CLI from an older LTS version, users should either: 
- Delete profiles, then recreate them manually after installing the new LTS version. 
- Save the profiles, move them into `.zowe` directory after installing the CLI, then issue a `zowe scs update` command to ensure compatibility with the current version of the Secure Credential Store plug-in. Also update z/OSMF profiles to use the `--user` and `--pass` options.
=> Changes to "Updating CLI" procedure

docs/extend/extend-apiml/onboard-plain-java-enabler.md, docs/extend/extend-apiml/onboard-spring-boot-enabler.md
Cipher parameter was unused and removed to avoid confusion. Code PR: https://github.com/zowe/api-layer/pull/753
Remove ciphers ssl parameter to avoid confusion, as it is unused. [Code PR.](https://github.com/zowe/api-layer/pull/753) [Issue.](https://github.com/zowe/api-layer/issues/693)
=> Resolve 693: Remove unused cipher parameter

docs/user-guide/api-mediation/api-gateway-configuration.md
The PR is linked to the https://github.com/zowe/api-layer/issues/472 
The PR explains the configuration parameter which uses SAF as authentication provide instead of zOSMF and as such removes the need to have running zOSMF on the system.
=> Document configuration parameter for SAF as authentication provider

docs/getting-started/freqaskques.md
It's a quick fix. The Zowe Explorer FAQ anchor link (in TOC) was broken. This PR fixes the issue.
=> Fix the ZE FAQ anchor link

docs/.vuepress/pages.json, docs/appendix/zowe-api-reference.md, docs/appendix/zowe-cli-commannd-reference.md
Using master because this API documentation is for the current release.
Resolve #537. Adds reference links to generated API swagger files, displayed by petstore.swagger.io. [Example here.](https://petstore.swagger.io/?url=https://raw.githubusercontent.com/zowe/docs-site/docs-staging/api_definitions/datasets.json)
=> Add reference links to api docs

docs/user-guide/cli-db2plugin.md
Thank you @JohnPhillipPearson for this fix. 
Changed the password profile option to `--pw` to match the product. Previosuly, the option was `-p`.
=> Update Db2 plugin profile syntax

docs/.vuepress/config.js, docs/.vuepress/versions.json, docs/README.md
Added:
- 1.16.0 versioning
- Archived master branch  (lmk if any of your PRs with `base:master` should have been merged before this.  I'll help add them back to the archived branch and PDF since this was my doing :P) 
- Archived 1.15 PDF
- Updated Algolia search
TODO:
- [] Release Notes (pls be sure changleogs are complete before they build package on Monday)
- [] TPSRs 
- [] BoM (or not)
=> Prepare v1.16.0 doc version

docs/extend/extend-apiml/api-mediation-security.md, docs/user-guide/api-mediation/api-gateway-configuration.md, docs/user-guide/configure-instance-directory.md
This is documentation revert for client cert auth, which should not go to the upcomming release. It will be added back when the client cert auth is ready.
There is no need for TI review imho.
=> Hold off client certificate auth documentation for this release

docs/extend/extend-apiml/api-mediation-security.md
Documents the new method available in the `ZaasClient` interface that takes an `HttpServletRequest` object for querying a token.
=> Document zaas client enhancements

docs/user-guide/cli-installcli.md
Information about npm prerequisite was outdated in the Install CLI topic. Users now require a currently-supported LTS version of npm. 
Copied the more current information from CLI Software Requirements so that the information is correct and consistent across the doc.
=> Consistently describe npm requirement for CLI

robots.txt
#1503 
Blocking all web crawlers from crawling docs of v1.16.0 and earlier versions. This will ensure that older versions of docs do not display in search results but are still accessible via direct URL. 
=> Create robots.txt to disallow crawl of archived docs

docs/user-guide/api-mediation/api-gateway-configuration.md
Related to [APIML PR 985](https://github.com/zowe/api-layer/pull/985) and [APIML issue 843](https://github.com/zowe/api-layer/issues/843).
Documents new configuration for APIML Gateway to set the concurrent connection limit per route and in total.
=> Document APIML Gateway connection limit configuration

docs/.vuepress/pages.json, docs/user-guide/cli-installcli.md, docs/user-guide/install-cli-via-proxy.md
This PR publishes a contribution from @MichaelABroadcom that describes how to install Zowe CLI via a proxy server in cases where the user cannot access public npm directly. 
Thanks!
=> Install Zowe CLI via Proxy 

docs/.vuepress/config.js, docs/.vuepress/versions.json, docs/README.md, docs/getting-started/summaryofchanges.md
Added the 1.18.0 versioning to doc site versions, config, readme, and release notes. 
Did _not_ archive the site, the PDF, etc.. since the release may still be a while in the future.
=> Initial v1.18.0 setup

docs/.vuepress/styles/index.styl
**This addresses the feedback that H3 and H4 headers font size looks similar so not able to identify the correct topic hierarchy.** 
Previously:
Now:
=> Adjust header font size

docs/extend/extend-apiml/onboard-direct-eureka-call.md, docs/extend/extend-apiml/onboard-nodejs-enabler.md, docs/extend/extend-apiml/onboard-overview.md, docs/extend/extend-apiml/onboard-plain-java-enabler.md, docs/extend/extend-apiml/onboard-spring-boot-enabler.md
Fix indentation in plain java enabler sample. Set apiId consistent throughout document and according to conformance criteria. Fixes  https://github.com/zowe/api-layer/issues/1103
=> Indentation and consistency for enablers 

docs/user-guide/api-mediation/api-gateway-configuration.md
Explain to the users how they can configure the removal or replacement of the API Catalog service within the API Mediation Layer. 
Linked to https://github.com/zowe/api-layer/issues/727 
=> Allow removal or replacing of API catalog within the API ML

docs/user-guide/install-zowe-smpe.md
From ```nawname="@PREFIX@.ZOWE.AZWE001.F3"/>``` to  ```newname="@PREFIX@.ZOWE.AZWE001.F3"/>```
=> Typo in SYSIN for GIMUNZIP (EXTRACT JCL)

package.json
Follow up to #1708 which inadvertently broke [master build](https://wash.zowe.org:8443/blue/organizations/jenkins/docs-site/detail/master/315/pipeline) by making the link checker time out.
The directories inside docs/.vuepress/public (typedoc and web_help) contain automatically generated content that doesn't need to have its links checked, and makes the link checker take significantly longer.
This change should approximately halve the time of the "test" stage in the pipeline, since web_help folder used to be included in link check.
Thanks to @jackjia-ibm for helping me to fix this 🙂
=> Exclude docs/.vuepress/public subdirectories from link checker

docs/user-guide/configure-instance-directory.md
Fix wrong path reference of convert-to-zowe-yaml.sh.
=> fix wrong path of convert-to-zowe-yaml.sh

docs/user-guide/systemrequirements-zos.md
OMVS Service in ZSS requires `READ` access to `IRR.RADMIN.LISTUSER` profile in order to obtain information about OMVS segment of the user profile. This PR documents the requirement.
=> Document requirements for OMVS service in ZSS

docs/user-guide/configure-zos-system.md
Fixed a typo in the z/OS System configuration instructions.
=> Fixed a typo in configuration instructions for z/OS System

docs/extend/extend-desktop/mvd-authentication-api.md, docs/extend/extend-desktop/mvd-dataservices.md
This updates the app framework documentation to explain how developers can make use of HA features, and what they can/cant do in an HA environment. Additionally I added some missing ZSS documentation while I was in that area of the doc.
=> Add documentation about HA for app-server and zss

docs/extend/extend-apiml/custom-metadata.md
Adds documentation for the new `customMetadata.apiml.response.headers` configuration parameter.
=> Add docs for customMetadata.apiml.response.headers

docs/user-guide/ze-profiles.md
This PR addressed the issue that's been brought up in the Zowe Explorer squad https://github.com/zowe/vscode-extension-for-zowe/pull/1575 
The Associate Profile feature has been deprecated recently and will be removed when V2 is released (slated for February 2022).
=> Add the Deprecated note (Associate Profile section)

static/Zowe_introduction_video_script.txt, versioned_docs/version-v1.25.x/extend/extend-apiml/api-mediation-passtickets.md, versioned_docs/version-v1.25.x/extend/extend-apiml/api-mediation-security.md, versioned_docs/version-v1.25.x/extend/extend-apiml/service-information.md, versioned_docs/version-v1.25.x/getting-started/overview.md, versioned_docs/version-v1.25.x/user-guide/api-mediation/api-mediation-overview.md, versioned_docs/version-v1.25.x/user-guide/configure-certificates-keyring.md, versioned_docs/version-v1.25.x/user-guide/configure-certificates-keystore.md, versioned_docs/version-v1.25.x/user-guide/configure-zos-system.md, versioned_docs/version-v1.25.x/user-guide/install-ha-sysplex.md, versioned_docs/version-v1.25.x/user-guide/systemrequirements-zosmf-lite.md, versioned_docs/version-v1.25.x/user-guide/systemrequirements-zosmf.md
Signed-off-by: ik673626 <igor.kazmyr@broadcom.com>
This PR addresses an issue with some CA references that 'slipped though' into v1.25 of Zowe Docs. 
I and Andrew couldn't figure out the cause of the issue despite the thorough check of the initial PR that aimed to rebrand all the former CA names. In addition to that, while searching for any CA references in v1.25 on Zowe Docs, the search didn't come up with any results. 
:heart: Thank you!
=> (FIX) Re-branding issue (for V1.25)

docs/user-guide/sdks-using.md
The link to npm semver no longer exists. Searched their doc and found an alternative article.
The link to pip documentation was updated with a redirect.  i updated the link to the new article/URL....
Fixes: #1939 
=> update links in the topic "Install SDK from online registry"

docs/user-guide/verify-zowe-runtime-install.md
`grep` can be quite different on different systems, and the documented example uses options that aren't consistently available across all platforms. `awk` is more stable.
=> fix: Use awk instead of grep for health check example

src/components/DownloadableFiles/DownloadableFiles.js
We recently update the docs-site home page > Downloadable files.  Migrating the v1 changes in to the v2 version of the page.
=> migrated new v1 content into v2 content on the docs home page > Downloadable files

docs/extend/extend-apiml/custom-metadata.md, docs/user-guide/api-mediation/api-gateway-configuration.md
Signed-off-by: Amanda D'Errico <amanda.derrico@ibm.com>
Docs: Updating docs to clearly describe the link from the general Gateway to specific service configuration for CORS enabling. Three states of CORS are described in api-gateway-configuration.md:
1. CORS is disabled on the gateway
2. CORS is enabled on the gateway and in the specific service config
3. CORS is enabled on the gateway but disabled in the specific service config
=> indicate clear link for CORS from Gateway to specific service

docs/extend/extend-apiml/api-mediation-security.md
Signed-off-by: Amanda D'Errico <amanda.derrico@ibm.com>
Docs include both `api/v1/gateway/auth` and `gateway/api/v1/auth` as supported base authentication paths for Zowe V2 LTS, up until March 2023.
=> docs: Zowe V2 LTS extends support for both base authentication paths until March 2023

docs/extend/extend-apiml/api-mediation-security.md
Signed-off-by: Amanda D'Errico <amanda.derrico@ibm.com>
Update authentication endpoints to support `/api/v1/gateway/auth` for duration of v2. Additional edits made in JWT Token and z/OSMF JSON Web Tokens Support.
=> docs: base url supports old format for duration of v2

docs/user-guide/configure-xmem-server.md, docs/user-guide/initialize-zos-system.md
Updated the cross memory server chapter with more information on the `zwe init apfauth` command
=> Cross Memory Server Chapter updates

docs/appendix/server-component-manifest.md
Adding the (required) statement to make it abundantly clear of our intent to require schemas no matter how trivial https://github.com/zowe/docs-site/pull/2108
=> Fix noting that schema is required

docs/user-guide/systemrequirements-zos.md
`IBM SDK for Java Technology Edition V8 or higher` indicates we may support JDK v11, which is not. So remove `or higher` wording.
=> remove potential support of JDK v11

docs/troubleshoot/cli/zosmf-cli.md, docs/user-guide/cli-using-sharing-team-config-files.md
Fixed typo in z/osmf troubleshooting
Fixed formatting anomaly in sharing team config files
=> fix typos/formatting anomalies

src/theme/DocVersionBanner/index.js
In a recent discussion, the message that "it’s no longer actively maintained" in the banner that appears in each version caused some confusion among users who think that the release is not maintained any more.
Thus the banner message has been corrected.
:heart: Thank you!
=> Fix: Banner message in archived versions

docs/user-guide/api-mediation/api-gateway-configuration.md
Remove note Re: Gateway client cert authentication out of beta
Resolves issue: [#2356](https://app.zenhub.com/workspaces/community-5c93e02fa70b456d35b8f0ed/issues/zowe/api-layer/2356)
=> Remove Gateway client certificate note

docs/appendix/server-component-manifest.md
Examples for zisPlugins paths in the manifest file were incorrectly absolute paths, which would not work in the code. This fixes them to be relative.
=> Update zis paths within server-component-manifest.md

package-lock.json, src/components/DownloadableFiles/DownloadableFiles.js
Add central version dropdown for downloadable files section.
**Note**: For Python SDKs, the link always points to the latest version.
=> fix: Add central version dropdown for downloadable files

docs/user-guide/systemrequirements-zos.md
I use the permission table a lot and noticed it was unreadable on docs.zowe.org. 1 line fix to fix it
=> Fixing broken table

versioned_docs/version-v1.28.x/getting-started/release-notes/v1_28_1.md
Changelog for:
- Zowe CLI
- Imperative
- Db2 Plug-in
=> Anax 1281 changelog

docs/extend/extend-ze/ze-extensions.md, docs/getting-started/zowe_faq.md, docs/user-guide/cli-using-using-environment-variables.md, docs/user-guide/ze-ftp.md, docs/user-guide/ze-install.md, sidebars.js
Signed-off-by: anaxceron <ana.ceron@broadcom.com>
- Changed mentions of "master" to "main" in Explorer file names used in Zowe Docs
- Fixed minor consistency deviation in [Using environment variables](https://docs.zowe.org/stable/user-guide/cli-using-using-environment-variables/)
- Added [Information Roadmap for Zowe Explorer](https://docs.zowe.org/stable/getting-started/user-roadmap-zowe-explorer/) to the sidebar ToC
=> master to main updates, typos

docs/extend/extend-apiml/authentication-for-apiml-services.md, docs/extend/extend-apiml/certificate-management-in-zowe-apiml.md, docs/extend/extend-apiml/zaas-client.md, docs/extend/extend-apiml/zowe-api-mediation-layer-security-overview.md, sidebars.js
The file Zowe API ML Security has grown too long to be presented in a single article on zowe docs. This PR chunks the existing topic into 4 topics and addresses api-layer issue [#2563: Improve the structure of the Security documentation](https://app.zenhub.com/workspaces/community-5c93e02fa70b456d35b8f0ed/issues/zowe/api-layer/2563)
=> Restructure API ML security doc

docs/user-guide/cli-configuringcli-ev.md
created a new pull request w/ the same content:
===
Added subheading "Setting a shared plug-in directory" and related content to [Configuring Zowe CLI environment variables](https://docs.zowe.org/stable/user-guide/cli-configuringcli-ev):
- use case for wanting a shared plug-in directory
- warning re: needing to re-install any previously installed plug-ins
- table w/ additional definitions for the env variable
=> Added plugin dir env variable

docs/user-guide/mvd-using.md
The URLs seen below reference externalPort which generally means apiml is involved, so the prefix should be applied to these zlux URLS.
=> Fix incorrect URL

docs/troubleshoot/troubleshoot-apiml.md, docs/user-guide/api-mediation/using-api-mediation-layer.md
This PR fixes a couple minor typos in API ML doc
=> Fix typos in API ML doc

docs/user-guide/api-mediation/api-gateway-configuration.md, docs/user-guide/api-mediation/api-mediation-personal-access-token.md, sidebars.js
Add configuration documentation
The Personal Access Tokens documentation was hidden in installation section and there was no information on how do you enable the tokens on your instance. 
Signed-off-by: Jakub Balhar <jakub@balhar.net>
=> Move usage of the Personal Access Tokens

docs/troubleshoot/troubleshoot-apiml.md
The troubleshooting tip state incorrectly that the Zowe should be run under the same user as zOSMF which isn't true. It's just possible workaround for the specific problem. 
=> Update troubleshooting tip to state that zOSMF user is workaround. 

versioned_docs/version-v2.1.x/user-guide/zowe-ha-overview.md
Fixed broken links in [Overview](https://docs.zowe.org/stable/user-guide/zowe-ha-overview) page for High Availability per comment made in zowe-doc Slack channel by Jakub Balhar
=> fixing broken links in High Avail Overview page

docs/user-guide/systemrequirements-zos.md
https://github.com/zowe/zowe-install-packaging/pull/3198 and its associated documentation adds an optional requirement for a resource to write SMF records.  This is listed in the documentation, but not in the easy-to-find table. So, I added it to the table and linked the table to the prior documentation.
=> Document RAUDITX optional resource in the resource table

docusaurus.config.js, src/components/SearchHeader/SearchHeader.js
Signed-off-by: Leanid Astrakou <LeanyIA@yahoo.com>
1) fixes current Doc website out of date search results (for example: configuration manager is not searchable) and
2) fixes search results for v2.1 --> v2.4 not working
by update indexing keys to match our up-to-date working Algolia Zowe index
=> (master) Fix Doc website out of date search results + non-working v2.1-2.4 search results

sidebars.js
The information roadmap for API ML was accidentally removed from the sidebar in v2.0. This PR reintroduces it.
=> add api ml information roadmap to sidebar

sidebars.js
Thanks to @awharn for helping to debug and fix these issues 🙂 
* Fixes infinite loop in "docs:pdf" script caused by `sidebars.js` referencing the same article twice
* ~Restores file `api-mediation-security.md` that seems to have been accidentally removed causing broken links~
Determined this file was removed intentionally, the broken links will be fixed in a subsequent PR
* ~Updates dependencies to fix some vulnerabilities~
Reverted since it seemed to be making the Netlify build time out
=> Fix infinite loop in "docs:pdf" script

docs/extend/extend-apiml/onboard-plain-java-enabler.md
This PR fixes a broken link to the topic API Mediation Layer Security that was deprecated and replaced with API ML Security Overview
=> Fix API ML security link to direct to API ML Security Overview

docs/extend/extend-apiml/api-mediation-passtickets.md, docs/extend/extend-apiml/api-mediation-sso.md, docs/extend/extend-apiml/certificate-management-in-zowe-apiml.md, docs/extend/extend-apiml/custom-metadata.md, docs/extend/extend-apiml/onboard-overview.md, docs/extend/extend-apiml/onboard-plain-java-enabler.md, docs/extend/extend-apiml/onboard-spring-boot-enabler.md, docs/user-guide/cli-using-working-certificates.md, docs/user-guide/configure-certificates-keystore.md
This PR fixes broken links to the deprecated api-mediation-security.md. links are redirected to current .md files.
This PR also returns the following sections which were lost during chunking:
- API ML truststore and keystore
- API ML SAF Keyring
=> Fix links to API ML security

sidebars.js
Removed APIML article that was deleted in [PR 2622](https://github.com/zowe/docs-site/pull/2622/files#diff-9a6a0fdafefb0eecffb77784bc94f5ad984062167b8bcb7c4a899c90f6f567e8) from the Zowe Docs sidebar. The article (user-guide/api-mediation/api-mediation-internal-configuration) was causing an error in our Zowe v 2.7 doc prep.
=> removed deleted APIML article from sidebar

sidebars.js
Removing a second instance of the **Configuring the Zowe APIs** article from the sidebar. The article appears twice and it should appear only once.
=> removing duplicate article from sidebar

docs/contribute/guidelines-code/documentation.md, docs/extend/extend-cli/cli-developing-a-plugin.md, docs/extend/extend-cli/cli-extending-a-plugin.md, docs/getting-started/release-notes/v2_7_0.md, docs/getting-started/zowe-resources.md, docs/user-guide/cli-using-test-zosmf-connection.md, release-handbook/release_handbook.md
Minor changes including:
- Adding missing vulnerabilities fixed to Zowe v2.7 release notes
- Fixing links and spelling, updating lists in the [Release handbook](https://github.com/zowe/docs-site/blob/master/release-handbook/release_handbook.md)
=> minor edits to v2.7 release notes and Doc Squad Release handbook

sidebars.js
Component registries link was added before, so now it is there twice.
=> Revert "Update sidebars.js for component registries page "

netlify.toml
This was recommended in https://github.com/zowe/docs-site/issues/2766#issuecomment-1501527472 and https://github.com/facebook/docusaurus/issues/4765#issuecomment-1361341991.
The default concurrency is 32 (see https://github.com/slorber/static-site-generator-webpack-plugin/pull/3) and this reduces it to 5.
Hopefully it buys us some time by reducing memory usage for our Netlify build - results seem promising so far.
However it's hard to be sure since the Out of Memory errors are transient and may occur again in the future.
If that happens, we have more long-term ideas to pursue as discussed in #2766 🙂 
Also uses Node.js 16 instead of 14 which reaches End of Life in a few weeks (see https://endoflife.date/nodejs).
=> Restrict SSR concurrency for Netlify build

docs/user-guide/cli-configure-scs-on-headless-linux-os.md
This PR fixes the Bash snippet that unlocks the keyring at login. It needs to include the `gnome-keyring-daemon` command, and should only be run in interactive mode to prevent non-interactive logins like SFTP from hanging.
=> Update Zowe CLI docs for unlocking the keyring automatically

docs/extend/extend-cli/cli-devTutorials.md, docs/extend/extend-ze/ze-extensions.md, docs/extend/extend-zowe-overview.md, docs/getting-started/user-roadmap-zowe-explorer.md, docs/getting-started/zowe_faq.md, docs/user-guide/ze-install.md
Fixing broken links as a result of moving ZE content to the ZE wiki. Fixing other links found in Link Checker
=> fixing broken links

docs/getting-started/zowe_faq.md, src/css/custom.css, versioned_docs/_version-v1.16.x/getting-started/freqaskques.md, versioned_docs/_version-v1.17.x/getting-started/freqaskques.md, versioned_docs/_version-v1.18.x/getting-started/freqaskques.md, versioned_docs/_version-v1.19.x/getting-started/freqaskques.md, versioned_docs/_version-v1.20.x/getting-started/freqaskques.md, versioned_docs/_version-v1.21.x/getting-started/freqaskques.md, versioned_docs/_version-v1.22.x/getting-started/freqaskques.md, versioned_docs/_version-v1.23.x/getting-started/freqaskques.md, versioned_docs/_version-v1.24.x/getting-started/freqaskques.md, versioned_docs/_version-v1.25.x/getting-started/freqaskques.md, versioned_docs/_version-v1.26.x/getting-started/freqaskques.md, versioned_docs/version-v1.27.x/getting-started/freqaskques.md, versioned_docs/version-v1.28.x/getting-started/freqaskques.md, versioned_docs/version-v2.3.x/getting-started/zowe_faq.md, versioned_docs/version-v2.4.x/getting-started/zowe_faq.md, versioned_docs/version-v2.5.x/getting-started/zowe_faq.md, versioned_docs/version-v2.6.x/getting-started/zowe_faq.md, versioned_docs/version-v2.7.x/getting-started/zowe_faq.md
Fixes issue where `details` tags were not formatted properly, causing the collapse boxes to be misaligned.
Note that I saw some uses of `class` instead of `className` in the markdown files - since all the Markdown content is rendered as JSX, you have to use `className=` and not `class=`
=> fix: formatting for `details` tags in FAQ

docs/user-guide/install-zowe-pswi-address-requirements.md
This requirement is no longer applicable to installation of z/OS components
=> remove CCS requirement from z/OSMF Install of z/OS Components

docs/user-guide/install-zowe-pswi-address-requirements.md, versioned_docs/_version-v1.26.x/user-guide/install-zowe-pswi-address-requirements.md, versioned_docs/version-v1.27.x/user-guide/install-zowe-pswi-address-requirements.md, versioned_docs/version-v1.28.x/user-guide/install-zowe-pswi-address-requirements.md, versioned_docs/version-v2.3.x/user-guide/install-zowe-pswi-address-requirements.md, versioned_docs/version-v2.4.x/user-guide/install-zowe-pswi-address-requirements.md, versioned_docs/version-v2.5.x/user-guide/install-zowe-pswi-address-requirements.md, versioned_docs/version-v2.6.x/user-guide/install-zowe-pswi-address-requirements.md, versioned_docs/version-v2.7.x/user-guide/install-zowe-pswi-address-requirements.md
The CCS requirement is not applicable for installing with z/OSMF
=> Remove CCS prereq from Install with z/OSMF 

.github/workflows/build-docs.yml, .github/workflows/deploy-preview.yml
This PR enables Netlify previews for fork PRs by triggering a separate deploy workflow after the build completes. This workflow has access to repository secrets such as the Netlify auth token. Because the docs build has to be uploaded from the first workflow and download by the second one, builds for fork PRs will take on average 7-10 minutes longer than other builds.
=> Fix Netlify preview missing for fork PRs

sidebars.js
This PR adds a link to the new page with ZIS message IDs. The messages themselves were added in https://github.com/zowe/docs-site/pull/2859.
=> Add a link to ZIS message IDs

docs/user-guide/cli-using-command-precedence.md, docs/user-guide/cli-using-using-profiles-v1.md, docs/user-guide/cli-using-usingcli.md, sidebars.js
Fixing broken link in [Using V1 profiles](https://docs.zowe.org/stable/user-guide/cli-using-using-profiles-v1#profile-best-practices) called out in [Issue 2946](https://github.com/zowe/docs-site/issues/2946)
=> fixing broken link

sidebars.js, versioned_sidebars/version-v2.7.x-sidebars.json, versioned_sidebars/version-v2.8.x-sidebars.json
There's a page with hundreds of message IDs and descriptions of what to do when you see them, but it was missing from the sidebar. It was added in v2.7 so I updated the versioned docs to add it all the way back to then.
=> Add missing appserver error codes to sidebar in versions where present

docs/user-guide/systemrequirements-zos.md
Unless you'd like to volunteer for maintaining the specific list of browser versions Zowe supports which changes monthly, you should delete this part of the documentation as seen in my PR.
The problem being fixed:
The documentation clearly states
> The Zowe Desktop supports Google Chrome, Mozilla Firefox, Apple Safari and Microsoft Edge releases that are at most 1 year old, except when the newest release is older.
And then goes on to list:
> - Google Chrome V79 or later
> - Mozilla Firefox V68 or later
> - Safari V13 or later
> - Microsoft Edge 79
All of which are way more than 1 year old.
Why? Because someone thought it was a good idea to enumerate specific versions.
It's more like a maintenance nightmare.
It's highly unlikely people have browsers that are older than this, because the …
=> Stop tracking specific browser versions

docs/getting-started/release-notes/v2_10_0.md
API ML has only one bugfix to announce for the 2.10 release notes.
=> Add API ML bugfix for 2.10 release notes

docs/user-guide/cli-using-integrating-apiml.md
Fixing incorrect commands in [Integrating with API Mediation Layer](https://docs.zowe.org/stable/user-guide/cli-using-integrating-apiml)
=> fixing incorrect commands

docs/user-guide/generate-certificates.md, docs/user-guide/import-certificates.md, docs/user-guide/zos-components-installation-checklist-dev.md, docs/user-guide/zos-components-installation-checklist.md
This PR updates the content in the installation checklists with the current configure certificates articles and transforms some headers into gerunds as per the style guide
=> Update Configure certs in Installation checklists and header fixes

docs/user-guide/api-mediation/api-mediation-internal-configuration.md
Replace v1 reference for environment variables with v2 method
- https://github.com/zowe/docs-site/issues/3019
close #3019 
=> Remove v1 reference

docs/user-guide/systemrequirements-zos.md
@DivergentEuropeans raised a concern regarding search findability for search terms "system permissions" and "security permissions" re: system requirements. (See [closed PR 3054](https://github.com/zowe/docs-site/pull/3054).)
To address this, making a small update to a header in [System requirements](https://docs.zowe.org/stable/user-guide/systemrequirements-zos).
For information only (no action required): @janan07 @samanthasusu 
**NOTE**: In the future, we would like to use tags/keywords in meta data for SEO. With the help of @traeok and @t1m0thyj, we've done some initial work on implementing these but are now blocked. Looking to work w/ Algolia support to move ahead on this.
=> updating header for better SEO

docs/user-guide/certificate-configuration-scenarios.md, docs/user-guide/certificates-configuration-questionnaire.md, docs/user-guide/configure-certificates.md
This PR makes language and formatting fixes to the files under configuring certificates.
=> Language and formatting fixes to Certificates docs

versioned_docs/version-v1.28.x/getting-started/release-notes/v1_28_3.md, versioned_docs/version-v1.28.x/getting-started/release-notes/v1_28_4.md
This PR addresses an oversite to include bug fixes for API ML from versions 1.28.3 and 1.28.4.
=> Add apiml bug fixes for previous 1.28.x versions

docs/contribute/roadmap-contribute.md, docs/troubleshoot/troubleshooting.md, docs/user-guide/install-overview.md, docs/user-guide/zowe-getting-started-tutorial.md, docusaurus.config.js
This PR refactors the drop down menu and standardizes titles in top-level articles so they have consistent naming conventions.
=> refactor drop down menu and some top-level article titles

docs/user-guide/api-mediation/api-catalog-configuration.md
=> Fix Catalog doc to be aligned to v2

docs/user-guide/systemrequirements-zos.md, versioned_docs/version-v1.28.x/user-guide/systemrequirements-zos.md, versioned_docs/version-v2.10.x/user-guide/systemrequirements-zos.md, versioned_docs/version-v2.5.x/user-guide/systemrequirements-zos.md, versioned_docs/version-v2.6.x/user-guide/systemrequirements-zos.md, versioned_docs/version-v2.7.x/user-guide/systemrequirements-zos.md, versioned_docs/version-v2.8.x/user-guide/systemrequirements-zos.md, versioned_docs/version-v2.9.x/user-guide/systemrequirements-zos.md
According to the way our docs claim support for zOS, it appears we no longer support zOS 2.3 as it has entered the same state as 2.2, last year. This update reflects the reality.
=> Update system requirements doc to reflect current zOS

docs/appendix/zowe-glossary.md, sidebars.js
Revert "Revert "Merge branch 'docs-staging' of https://github.com/zowe/docs-site into docs-staging""
This reverts commit a1e5df656a1b925872c7ab6fd5bf6f0bdeb20af0.
Signed-off-by: Andrew W. Harn <andrew.harn@broadcom.com>
Reverts a revert commit that inadvertently removed glossary content
=> Revert commit to restore glossary content

versioned_docs/version-v2.10.x/troubleshoot/troubleshoot-apiml.md, versioned_docs/version-v2.9.x/troubleshoot/troubleshoot-apiml.md
Fix the links to the configure certificates.
Close https://github.com/zowe/docs-site/issues/3152
=> Fix links in Troubleshooting for 2.9 and 2.10

docs/user-guide/ze-profiles.md
-Updating [Zowe Explorer profiles](https://docs.zowe.org/stable/user-guide/ze-profiles) to document new Manage Porfile functionality
- Edit content to separate V2 and V1 profiles
- Updated admonitions to align w/ Docusaurus syntax
=> documenting new Manage Profile func in ZE

docs/getting-started/release-notes/v2_12_0.md
THe API ML release notes for 2.12 were accidentally deleated from docs-staging. This PR re-adds these release notes.
=> re-add API ML release notes for 2.12

.github/workflows/pull-request-checker.yml
=> updating desc comment

.github/pr-comments/for-community.md, .github/pr-comments/for-labeller.md, .github/pr-comments/for-writer.md, .github/workflows/pull-request-checker.yml
- updating comments
- adding community member instructions
=> updating comments; adding community member comment

docs/user-guide/configure-xmem-server.md, docs/user-guide/zos-components-installation-checklist.md
Fix for the cross memory server (ZIS) load module name ZWESI00 -> ZWESIS01
=> ZIS load module typo fix

docs/user-guide/install-nodejs-zos.md, versioned_docs/version-v2.5.x/user-guide/install-nodejs-zos.md, versioned_docs/version-v2.6.x/user-guide/install-nodejs-zos.md, versioned_docs/version-v2.7.x/user-guide/install-nodejs-zos.md, versioned_docs/version-v2.8.x/user-guide/install-nodejs-zos.md, versioned_docs/version-v2.9.x/user-guide/install-nodejs-zos.md
The page docs/user-guide/install-nodejs-zos.md was not consistent with the page docs/user-guide/systemrequirements-zos.md
They slightly duplicate; one talks about nodejs in short, and the other in detail.
I added v18 to the detailed nodejs page, and removed v14
v16 has PTF links, and v18 does not. This is because all of IBM's own documentation links to 404 pages, so I have no links to provide. The PTFs listed however are from IBM's documentation.
=> Fix nodejs requirements page to list actually supported nodes

docs/extend/extend-apiml/api-mediation-oidc-authentication.md, docs/extend/extend-apiml/zowe-api-mediation-layer-security-overview.md
=> Updating APIML OIDC support with Microsoft Entra ID details

docs/troubleshoot/launcher/launcher-error-codes.md
=> Joe winchester/issue/3281

docs/whats-new/release-notes/v2_13_0.md, docusaurus.config.js, sidebars.js
Brings docs live and corrects tags to display current version.
=> Setting latest_version to 2.13.0 and displaying getting_started on the sidebar

docs/user-guide/api-mediation/configuration-cors.md, docs/user-guide/api-mediation/configuration-customizing-management-of-apiml-load-limits.md, docs/user-guide/api-mediation/configuration-routing.md, docs/user-guide/api-mediation/configuration-set-consistent-service-id.md
Post release of 2.13, a few pages were found to have broken links in Advanced API ML configuration. This PR addresses those broken links.
=> Fix broken links in Advanced API ML configuration

scripts/updateTypedoc.sh
This PR enhances `scripts/updateTypedoc.sh` so that it auto-detects the latest RC number. Previously it had an RC number hardcoded and would fail if no bundle existed for that exact RC.
**How to Test**
Run the update typedoc script for Zowe 2.13.0 to verify that it downloads and extracts the RC2 zip file successfully.
=> Auto-detect RC number in update typedoc script

docs/troubleshoot/cli/troubleshoot-cli-credentials.md
Describe your pull request here: Adding Zowe CLI troubleshooting content for PEM certificates
List the file(s) included in this PR: troubleshoot-cli-credentials.md
=> Adding PEM certificate troubleshooting

docs/user-guide/cli-installcli.md
Describe your pull request here: Adding angle brackets to vNext to emphasize that vNext is a variable that could change depending on the latest Zowe release.
List the file(s) included in this PR: cli-installcli.md
=> changing references of vNext

docs/extend/extend-apiml/api-mediation-components-of-URL.md, docs/user-guide/api-mediation/api-mediation-caching-service.md, docs/user-guide/obtaining-information-about-api-services.md, sidebars.js
Describe your pull request here: This PR fixes a couple broken links resulting from changing file paths in the restructuring of the Using API ML section
List the file(s) included in this PR: obtaining-information-about-api-services.md, and api-mediation-caching-service.md
=> Fix links in API ML Using section after restructuring

docusaurus.config.js, release-handbook/creating_site_banner.md
Describe your pull request here: Removing the Zowe Docs site banner re: V1 EOS. Updating banner instructions in Release handbook.
List the file(s) included in this PR: creating_site_banner.md
=> removing V1 EOS site banner

docs/appendix/zowe-yaml-configuration.md
"@include" was never used, and never worked with configmgr, if it ever worked at all, yet we tell users they can use it.
=> Remove reference to "@include" in yaml doc

docs/getting-started/zowe-architecture.md, docs/getting-started/zowe-security-authentication.md, docs/user-guide/api-mediation-sso.md, docs/user-guide/api-mediation/using-api-mediation-layer.md, docs/user-guide/authenticating-with-client-certificates.md, docs/user-guide/authenticating-with-jwt-token.md
Describe your pull request here: Users pointed out some broken links after user section reorg. This PR addresses those issues
List the file(s) included in this PR: using-api-mediation-layer.md, api-medation-sso.md, zowe-architecture.md, zowe-security-authentication.md
=> Link fixes from issues in doc site repo

docs/whats-new/breaking-changes-v3.md, sidebars.js
Describe your pull request here: This PR introduces content from zowe.org about breaking changes of Zowe components to be introduced in Zowe v3.
List the file(s) included in this PR: breaking-changes-v3.md, sidebars.js
=> Add breaking changes file into What's New

docs/user-guide/cli-ftpplugin.md, docs/user-guide/cli-mqplugin.md
Describe your pull request here: Removed the V1 `zowe profiles` commands when creating profiles for the MQ and FTP plug-ins
List the file(s) included in this PR:  `docs/user-guide/cli-ftpplugin.md` and `docs/user-guide/cli-mqplugin.md`
=> Update CLI plug-in docs around creating user profiles

docs/user-guide/api-mediation-change-password-via-catalog.md
Describe your pull request here: Remove link to API Gateway features which have been deprecated after reorg
List the file(s) included in this PR:  api-mediation-change-password-via-catalog.md
=> Remove link to deprecated content in change password via catalog

docs/user-guide/api-mediation/configuration-connection-limits.md
API Mediation Layer from 2.15 supports changing timeouts for Websocket connections. This is documenting how. 
The documentation is linked to the issue: https://github.com/zowe/api-layer/issues/2603 
user-guide/api-mediation/configuration-connection-limits
=> Add explanation for Websocket timeouts.

docs/user-guide/api-mediation/configuration-jwt.md
The documented way to provide the configuration for enabling JWT Token Refresh doesn't work
docs/user-guide/api-mediation/configuration-jwt.md
=> Add Workaround for JWT Refresh Token

docs/user-guide/configure-xmem-server.md, docs/user-guide/configure-zos-system.md
Describe your pull request here: Fixing bad syntax on an admonition. Resolves [Issue 3521](https://github.com/zowe/docs-site/issues/3521).
List the file(s) included in this PR: configure-zos-system.md
=> fixing admonition and typo

versioned_docs/version-v1.28.x/getting-started/release-notes/v1_28_6.md, versioned_sidebars/version-v1.28.x-sidebars.json
Describe your pull request here: Prepping for Zowe v1.28.6 doc
List the file(s) included in this PR: tpsr-v1.28.6.md +
=> doc prep for Zowe v1.28.6

docs/user-guide/cli-using-integrating-apiml.md, docs/user-guide/generate-certificates.md
Describe your pull request here: Fix typo and minor language refactoring with link fix
List the file(s) included in this PR: generate-certificates.md, cli-using-integrating-apiml.md
=> minor language refactoring and link fix

docs/extend/extend-apiml/onboard-plain-java-enabler.md, docs/extend/extend-apiml/onboard-spring-boot-enabler.md, docs/user-guide/configure-certificates.md, sidebars.js
Describe your pull request here: Fix duplications as per peer review
List the file(s) included in this PR: configure-certificates.md, sidebars.js
=> Fix duplications

docs/extend/extend-apiml/api-mediation-websockets.md, sidebars.js
The explanation for how to onboard WebSocket based APIs was missing. This PR fixes this and clarifies structure of the Extend with respect to existing articles. 
-sidebar.js
- docs/extend/extend-apiml/api-mediation-websocket
=> Add Websocket related configuration

docs/user-guide/address-network-requirements.md
In case the storage mode in the Caching Service is `infinispan`, then the Cashing Service will require two more ports. One to form Infinispan claster and another one to secure key exchange.
address-network-requirements.md
=> Additional ports used in Caching Service (infinispan mode)

docs/user-guide/address-network-requirements.md
In case the storage mode in the Caching Service is `infinispan`, then the Cashing Service will require two more ports. One to form Infinispan claster and another one to secure key exchange. 
This PR is almost identical to #3586 with exception to `keyExchange` port number and variable name.
address-network-requirements.md
=> Additional ports used in Caching Service (infinispan mode) - keyExchange port updated

.github/workflows/pull-request-checker.yml
Describe your pull request here: Fixes check that enforces list of changed files is present in PR description.
Check failed on this PR: https://github.com/zowe/docs-site/pull/3573
The same PR description is now passing in my fork: https://github.com/t1m0thyj/zowe-docs-site/pull/1
List the file(s) included in this PR: pull-request-checker.yml
=> Fix file type check in PR checker workflow

docs/extend/extend-apiml/zowe-api-mediation-layer-security-overview.md, sidebars.js
Describe your pull request here: Add API ML security overview to sidebar
List the file(s) included in this PR: sidebars.js.md, zowe-api-mediation-layer-security-overview.md
=> Add API ML security overview to sidebar

docs/user-guide/address-network-requirements.md
The variable `zowe.environments.JGROUPS_KEYEXCHANGE_PORT` won't setup the port for JGroups KeyExchange server. Such variable (different from this one) was added in 2.16 (already in staging). This port is not possible to change in the current version (2.15), so there is no variable.
docs/user-guide/address-network-requirements.md
=> Remove misleading port configuration variable

docs/user-guide/api-mediation/configuration-at-tls.md
Current documentation has several problems that will break if tried as-is
* Non-default ports (10* instead of 7551-7555)
* Port ranges that cover more ports than quantity of servers (10 ports instead of 5)
* Jobnames that catch unrelated parts of Zowe (ZWE*)
* Jobnames that don't catch any part of Zowe by default (ZWEA* instead of ZWE1*)
* Double "server:" entry in the gateway YAML
* Example only covering gateway & discovery - should probably list all servers to prevent confusion.
=> Fix APIML ATTLS documentation

docs/user-guide/configuring-security.md
Describe your pull request here: Links used the old syntax for Docasaurus. This PR updates the syntax
List the file(s) included in this PR: configuring-security.md
=> fix link syntax in Configuring security

docs/user-guide/api-mediation/configuration-client-certificates.md, docs/user-guide/authenticating-with-client-certificates.md
The Client Certificate related information about usage and configuration were mixed between the articles. 
This moves the configuration in general to Install section and keeps only the details of configuration for specific user in the Use section. 
configuration-client-certificates.md, authentication-with-client-certificate.md
=> Move configuration of certificate to Install section

docs/extend/extend-apiml/zaas-client.md
Login example was using confusing "user" instead of "password". Linked to #3697 
zaas-client.md
=> Change the example for login in zaas

docs/user-guide/api-mediation/configuration-client-certificates.md
Describe your pull request here: Fix broken links in Enabling single sign on for clients via client certificate
List the file(s) included in this PR: configuration-client-certificates.md
=> fix links in client-certificate-configuration

docs/user-guide/api-mediation/configuration-connection-limits.md
websocket is [webSocket](https://github.com/zowe/api-layer/blob/f5ef28460cac6a9d5a1fc478cef9932789f7064d/schemas/gateway-schema.json#L250).
Yaml is case sensitive.
=> Typo in example: configuration-connection-limits.md

docs/user-guide/authenticating-with-client-certificates.md
Describe your pull request here: Authenticating with client certificates was missing the procedure to enable the internal API mapper This PR addresses this omission.
List the file(s) included in this PR: authenticating-with-client-certificate.md
=> Add internal api ml mapper config

docs/user-guide/use-certificates.md, versioned_docs/version-v2.12.x/user-guide/use-certificates.md, versioned_docs/version-v2.14.x/user-guide/use-certificates.md, versioned_docs/version-v2.15.x/user-guide/use-certificates.md, versioned_docs/version-v2.16.x/user-guide/use-certificates.md
I am removing a section that suggests users define `zowe.certificate.pem` when using multiple CAs and using a keyring.
The pem section has been and is still required for PKCS12, at all, but in the case of keyrings, it was needed only up until v2.9 (see https://docs.zowe.org/stable/whats-new/release-notes/v2_9_0#zlux-server-framework)
=> remove suggestion for pem section for keyrings

docs/extend/extend-apiml/custom-metadata.md, docs/extend/extend-apiml/onboard-direct-eureka-call.md
There were changes in this PR https://github.com/zowe/api-layer/pull/804 to allow encoded characters by default in onboarded services. Unfortunately the PR #1383 in docs-site was never merged. This PR is correcting the default value.
docs/extend/extend-apiml/custom-metadata.md
docs/extend/extend-apiml/onboard-direct-eureka-call.md
=> fix: allow url encoded characters by default

docs/user-guide/sdks-using.md
Describe your pull request here: Address issue #3851
List the file(s) included in this PR: docs.zowe.org/stable/user-guide/sdks-using
=> Address issue #3851

docs/whats-new/zowe-v3-migration.md
This PR makes the following changes:
* Moves the "## Special Considerations for Older Versions" to the top as "## Upgrading to the latest version of Zowe v2 (v2.18)"
The reason is users should see this first, not last, to ensure they are on the right version to follow the rest of the guide
* Added additional old version instructions based on my memory of what changed
* Moved the keyrings change out of "prerequisites" and into "configuration changes", because it is a configuration item.
=> Put v2 upgrade instructions at top of v3 migrate guide

docs/whats-new/zowe-v3-migration.md
I think its important to tell people that for the most part, migrating from zowe v2 to v3 does not require significant system changes.
So, this PR not only lists the networking changes needed, but reassures that certificate & security changes are otherwise not required.
=> Add System Changes section to migrate guide

docs/whats-new/zowe-v3-migration.md
I can't think of any reliable way to upgrade from v1 to v3.
But, I wanted to call out in the v3 doc what the user should do: a clean install, with updated extensions.
But, as far as I can tell from release notes, keystores as old as v1.27 should work in v3.
=> Add note about v1 for v3 upgrade guide

docs/user-guide/install-zowe-zos-convenience-build.md, sidebars.js
Today you can install zowe servers via many techniques and either on or off of z/OS.
All these options are currently visualized on the sidebar like this 
Since each one of these items is an option, you don't want to do more than one really. You want to choose one and only one.
To help make that obvious, I put them all under a parent item in the sidebar that just says "installing"
Then, I revised the titles to make clear what you're installing and how, so hopefully people will understand these are choices where you only choose one option.
Now it looks like this
=> Visualize "install" options as options under parent category

sidebars.js
This PR moves the APIML advanced topic to be under the parent group "Advanced server-side configuration" because since the App Framework doc was renamed and updated to match within https://github.com/zowe/docs-site/pull/3939 it makes sense to have them follow the same pattern for a more intuitive sidebar layout.
=> Combine advanced topics under one parent

.github/workflows/build-docs.yml, .github/workflows/deploy-preview.yml
Describe your pull request here: See title
List the file(s) included in this PR: build-docs.yml, deploy-preview.yml
Example of passing workflows on my fork:
* Build - https://github.com/t1m0thyj/zowe-docs-site/actions/runs/11898365365/job/33154699954
* Deploy - https://github.com/t1m0thyj/zowe-docs-site/actions/runs/11898459592/job/33155003111
=> Update workflows to use latest versions of actions

docs/user-guide/api-mediation/api-mediation-caching-service.md, docs/user-guide/configure-caching-service-ha.md, versioned_docs/version-v2.18.x/user-guide/api-mediation/api-mediation-caching-service.md, versioned_docs/version-v2.18.x/user-guide/configure-caching-service-ha.md
Caching Service configuration doc for HA had wrong properties and/or wrong indentations.
Also add notes about recommended solution and VSAM deprecation and future removal.
- docs/user-guide/configure-caching-service-ha.md
- docs/user-guide/api-mediation/api-mediation-caching-service.md
- versioned_docs/version-v2.18.x/user-guide/configure-caching-service-ha.md
- versioned_docs/version-v2.18.x/user-guide/api-mediation/api-mediation-caching-service.md
=> fix caching service properties, add deprecations

versioned_docs/version-v2.18.x/user-guide/apf-authorize-load-library.md, versioned_docs/version-v2.18.x/user-guide/configure-zos-system.md, versioned_docs/version-v2.18.x/user-guide/configure-zowe-runtime.md, versioned_docs/version-v2.18.x/user-guide/configuring-overview.md, versioned_docs/version-v2.18.x/user-guide/configuring-security.md, versioned_docs/version-v2.18.x/user-guide/initialize-zos-system.md, versioned_docs/version-v2.18.x/user-guide/systemrequirements-zos.md, versioned_docs/version-v2.18.x/user-guide/verify-zowe-runtime-install.md, versioned_docs/version-v2.18.x/user-guide/zos-components-installation-checklist.md, versioned_docs/version-v2.18.x/user-guide/zwe-init-subcommand-overview.md, versioned_sidebars/version-v2.18.x-sidebars.json
Describe your pull request here: apply security config reorg to 2.18
List the file(s) included in this PR: 
=> apply security config reorg to 2.18

docs/troubleshoot/troubleshoot-apiml-error-codes.md
Update troubleshooting codes with the support for multiple certificate URLs. 
troubleshoot-apiml-error-codes.md
=> Support multiple certificate validation URLs

docs/user-guide/configure-sysplex.md, docs/user-guide/configuring-at-tls-for-zowe-server.md, docs/user-guide/install-zowe-pswi-acquire.md, docs/user-guide/install-zowe-pswi-deployment.md, docs/user-guide/install-zowe-pswi.md, versioned_docs/version-v2.18.x/user-guide/configure-sysplex.md, versioned_docs/version-v2.18.x/user-guide/configuring-at-tls-for-zowe-server.md, versioned_docs/version-v2.18.x/user-guide/install-zowe-pswi-acquire.md, versioned_docs/version-v2.18.x/user-guide/install-zowe-pswi-deployment.md, versioned_docs/version-v2.18.x/user-guide/install-zowe-pswi.md
Add recommendations based on testing for PSWI deployment
- docs/user-guide/install-zowe-pswi-acquire.md
- docs/user-guide/install-zowe-pswi-deployment.md
- docs/user-guide/install-zowe-pswi.md
- versioned_docs/version-v2.18.x/user-guide/install-zowe-pswi-acquire.md
- versioned_docs/version-v2.18.x/user-guide/install-zowe-pswi-deployment.md
- versioned_docs/version-v2.18.x/user-guide/install-zowe-pswi.md
=> Add recommendations based on testing for PSWI deployment

docs/user-guide/address-network-requirements.md, versioned_docs/version-v2.15.x/user-guide/address-network-requirements.md, versioned_docs/version-v2.16.x/user-guide/address-network-requirements.md, versioned_docs/version-v2.17.x/user-guide/address-network-requirements.md, versioned_docs/version-v2.18.x/user-guide/address-network-requirements.md
The table that shows which jobs to associate with which ports for Zowe server networking is missing detail on a quirk of NodeJS+zOS by which the jobname of the app-server that uses the stated port may not be what's intended, depending on configuration.
I've updated the table to show 2 jobnames for app-server, and then added a section directly below to clarify when and how these jobnames take affect, and what the defaults are.
=> Clarify jobname for app-server port

docs/appendix/zowe-yaml-configuration.md
With Zowe 2.17, there is a `defaults.yaml` file, which is always merged with current config. There are some consequences, which should be documented.
What might be confusing for users, is existing paragraph about **Configuration override**. This is using defaults defined inside the config only. With the `defaults.yaml` you have another sets of defaults, which makes it complicated to describe and use.
**Note:** The `defaults.yaml` file and the merging of configs was added in **2.17**.
docs/appendix/zowe-yaml-configuration.md
=> Add defaults to Zowe yaml configuration

docs/user-guide/mvd-configuration.md, versioned_docs/version-v2.15.x/user-guide/mvd-configuration.md, versioned_docs/version-v2.16.x/user-guide/mvd-configuration.md, versioned_docs/version-v2.17.x/user-guide/mvd-configuration.md, versioned_docs/version-v2.18.x/user-guide/mvd-configuration.md
The file docs/user-guide/mvd-configuration.md suggested users edit a file "allowedPlugins.json" within a directory 
<zowe.runtimeDirectory>/components/app-server/share/zlux-app-server/deploy/...
This directory does not exist. It was a developer directory long ago.
I have updated the incorrect references to the valid folder 
<zowe.workspaceDirectory>/app-server/ZLUX/pluginStorage/org.zowe.zlux.bootstrap/plugins
This is applicable for all of v2 and v3. It may be that the old directory was valid for v1, but as that is out of support now I'm not digging too deep into that.
=> Fix RBAC setup suggestion for wrong directory

versioned_docs/version-v2.18.x/troubleshoot/troubleshoot-zos-certificate.md
Closes #4015.
List the file(s) included in this PR: 
versioned_docs/version-v2.18.x/troubleshoot/troubleshoot-zos-certificate.md
Signed-off-by: Andrew Metzger andrew.metzger@ibm.com.
=> Fix additional steps for users of third-party cert. management tools

docs/user-guide/cli-db2plugin.md
Added info to address #1540 
cli-db2plugin.md
=> Added info to describe how to get the Db2 connection details from JES

.github/workflows/build-docs.yml
Updates build workflow to skips "Deploy to Netlify" step for Dependabot PRs. Since Dependabot doesn't have access to regular secrets, we can deploy w/o them same as we do for fork PRs.
The method for detecting that a PR is opened by Dependabot is based on [GitHub docs](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#fetching-metadata-about-a-pull-request).
List the file(s) included in this PR: build-docs.yml
=> Fix Netlify deploy for Dependabot PRs

docs/getting-started/user-roadmap-apiml.md, docs/user-guide/api-mediation-sso.md, docs/user-guide/api-mediation/api-mediation-caching-service.md, docs/user-guide/api-mediation/routing-requests-to-rest-apis.md, docs/user-guide/api-mediation/use-graphql-api.md, docs/user-guide/api-mediation/using-api-mediation-layer.md, docs/user-guide/authenticating-with-jwt-token.md, docs/user-guide/obtaining-information-about-api-services.md, versioned_docs/version-v2.17.x/getting-started/user-roadmap-apiml.md, versioned_docs/version-v2.17.x/user-guide/api-mediation/api-mediation-caching-service.md, versioned_docs/version-v2.17.x/user-guide/api-mediation/routing-requests-to-rest-apis.md, versioned_docs/version-v2.17.x/user-guide/api-mediation/use-graphql-api.md, versioned_docs/version-v2.17.x/user-guide/api-mediation/using-api-mediation-layer.md, versioned_docs/version-v2.17.x/user-guide/obtaining-information-about-api-services.md, versioned_docs/version-v2.18.x/getting-started/user-roadmap-apiml.md, versioned_docs/version-v2.18.x/user-guide/api-mediation-sso.md, versioned_docs/version-v2.18.x/user-guide/api-mediation/api-mediation-caching-service.md, versioned_docs/version-v2.18.x/user-guide/api-mediation/routing-requests-to-rest-apis.md, versioned_docs/version-v2.18.x/user-guide/api-mediation/use-graphql-api.md, versioned_docs/version-v2.18.x/user-guide/api-mediation/using-api-mediation-layer.md, versioned_docs/version-v2.18.x/user-guide/authenticating-with-jwt-token.md, versioned_docs/version-v2.18.x/user-guide/obtaining-information-about-api-services.md
Describe your pull request here: Fix syntax in links to include .md file type
=> fix link syntax to include .md file type

docs/whats-new/release-notes/v3_0_0.md, docs/whats-new/release-notes/v3_1_0.md
Describe your pull request here: Add features and bug fixes for 3.1 and additions in 3.0
List the file(s) included in this PR: v3_1_0.md and v3_0_0.md
=> Add features and bug fixes for 3.1 and additions in 3.0

docs/appendix/zowe-yaml-configuration.md, docs/user-guide/install-nodejs-zos.md, docs/user-guide/systemrequirements-zos.md, versioned_docs/version-v2.18.x/user-guide/install-nodejs-zos.md, versioned_docs/version-v2.18.x/user-guide/systemrequirements-zos.md
Because Zowe community infrastructure tests node v22, and no issues have been reported, it seems the only task left is to write into documentation that node v22 is allowed to be used with Zowe.
I have also removed node v16 from documentation where applicable as it is no longer in support.
I made doc changes for v3 and v2.18 because there are no changes that made 22 support possible, so, it will work for both just fine.
=> Document Node 22 server support

scripts/updateTypedoc.sh
Recently, the typedoc was updated so that a `.zip.bundle` file is packaged alongside the other files in the Zowe release folder. However, this broke the grep check in `updateTypedoc.sh` that looks for the typedoc ZIP and it grabs the bundle instead, causing `unzip` to fail on line 25 of the script. This PR updates the check so it grabs the ZIP rather than the `.zip.bundle` file.
`scripts/updateTypedoc.sh`
=> fix: look for typedoc ending in .zip

sidebars.js
Describe your pull request here: Relocating links to 3.0, 3.1 release notes in the sidebar to the correct location
List the file(s) included in this PR: sidebar.md
=> fixing sidebar links to release notes

docs/extend/extend-apiml/api-medation-sso-integration-extenders.md
Add docs to setup x509 client certificate forwarding for downstream services.
- docs/extend/extend-apiml/api-medation-sso-integration-extenders.md
=> chore: add x509 client certificate forwarding

docs/contribute/roadmap-contribute.md
I added the missing syntax (.md) to repair the issue of the broken links.
The syntax (.md) was added at the end of the following links:
- [Zowe Docs](./contributing.md)
- [General code guidelines](./guidelines-code/categories.md)
- [UI guidelines](./guidelines-ui/ui.md)
- [Zowe learning resources](../getting-started/zowe-resources.md)
roadmap-contribute.md
=> 6951_Update roadmap-contribute.md

docs/user-guide/address-network-requirements.md
1) Link to IBM doc for z/OS 2.5 (2.4 out of support)
2) There is a note with condition, when the TCP IP setting example will work.
docs/user-guide/address-network-requirements.md
=> TCP IP setting: better explanation of example

docs/appendix/zowe-glossary.md
Signed-off-by: Saurabh.saurabhsingh050806@gmail.com
This pull request updates the Zowe glossary documentation to clarify the explanation of team configuration and its context, specifically addressing whether the profiles are stored in VSCode or z/OS. Additionally, I have added a more detailed explanation to help users understand where these configurations are stored and how they are applied globally or per project.
docs/stable/appendix/zowe-glossary.md (Updated the section related to team configuration and clarified the storage locations of configuration files
* Review the changes made to the glossary documentation.
* Check the clarity of the explanation …
=> Clarify location of zowe.config.json and zowe.config.user.json in glossary

docs/user-guide/cli-using-integrating-apiml.md, docs/user-guide/ze-authentication-methods.md, sidebars.js
Describe your pull request here: Relocating doc on ZE auth methods from ZE Readme to Zowe Docs
List the file(s) included in this PR: docs\user-guide\ze-authentication-methods.md
=> relocating auth methods doc to Zowe Docs

docs/whats-new/release-notes/v3_2_0.md
Describe your pull request here: Removing old link for V2 system demos from release notes
List the file(s) included in this PR: docs\whats-new\release-notes\v3_2_0.md
=> removing V2 sys demo link

docs/user-guide/configmgr-using.md
This PR adds information and examples on how to use functions of configmgr to make a YAML more portable.
=> Add configmgr environment function documentation

docs/user-guide/configmgr-using.md
Now that https://github.com/zowe/zowe-common-c/pull/522 is merged there will no longer be a restriction on member names seen with PARMLIB entries of configmgr configuration files.
I am updating the configmgr documentation to remove references about such a limitation.
=> (Zowe 3.3) Remove notes on parmlib member limitation

docs/troubleshoot/troubleshoot-apiml-error-codes.md
troubleshoot-apiml-error-codes.md
The description of an error message (ZWEAG120E) was to be added in the file.
This error message is ZWEAG120E, and it is related to gateway.
The error message is ZWEAG120E is different from the error message, ZWEA**S**120E. 
The description of the error message ZWEA**S**120E is already written, and it is related to security.
=> Updated troubleshoot-apiml-error-codes.md

versioned_sidebars/version-v3.0.x-sidebars.json
Remove duplicate `mvd-server-config` entry in the 3.0.x sidebar file (already present on L973) to prevent PDF generation from looping infinitely.
versioned_sidebars/version-v3.0.x-sidebars.json
=> Remove duplicate mvd-server-config entry to fix PDF generation

docs/whats-new/release-notes/v2_18_2.md, versioned_docs/version-v2.18.x/whats-new/release-notes/v2_18_2.md
This adds a soft compatibility claim for z/OS 3.2 with Zowe version 2.18.2.
=> update release notes to call out z/os 3.2 support

docs/user-guide/systemrequirements-zos.md
Missing requirement, `zwe init security` and `zwe init vsam` always required `SDSF`.
docs/user-guide/systemrequirements-zos.md
=> `systemrequirements-zos.md`: SDSF is required for `zwe init security | vsam`

docs/user-guide/configuring-at-tls-for-zowe-server.md
Adding information about AT-TLS running with keyring that is backed by ICSF hardware module.
[docs/user-guide/configuring-at-tls-for-zowe-server.md](https://github.com/zowe/docs-site/compare/docs-staging...reboot/attls_load_keyring?expand=1#diff-08430cb4e9fa8f0e858d7cf5d97b92ba4fe47b35d1aa5cf0d99f45d7adb4c205)
=> API ML: Adding info about APIML_ATTLS_LOAD_KEYRING
