docs/extend/extend-apiml/api-mediation-personal-access-token.md
docs/extend/extend-apiml/api-mediation-security.md
docs/user-guide/api-mediation/api-mediation-personal-access-token.md

Document Personal Access Token feature of API ML

---

docs/extend/extend-apiml/certificate-management-in-zowe-apiml.md

fix typos in Certificate management in Zowe API ML

---

docs/extend/extend-apiml/certificate-management-in-zowe-apiml.md
docs/extend/extend-apiml/zowe-api-mediation-layer-security-overview.md

Fix typos and remove outdated link

Fix typo / remove outdated link to wiki

---

docs/extend/extend-apiml/api-mediation-caching-service.md
docs/extend/extend-apiml/onboard-direct-eureka-call.md
docs/extend/extend-apiml/onboard-nodejs-enabler.md

This PR fixes typos and formatting.

Fix typos and formatting inconsistencies 

---

docs/user-guide/api-mediation/api-mediation-personal-access-token.md

Add missing info to the PAT doc

---

docs/troubleshoot/app-framework/appserver-error-codes.md

Signed-off-by: Leanid Astrakou <lastrakou@rocketsoftware.com>

Added lines 150-175

---

docs/troubleshoot/app-framework/appserver-error-codes.md

Signed-off-by: Timothy Gerstel <tgerstel@rocketsoftware.com>

Add error codes 50-75

---

docs/troubleshoot/app-framework/appserver-error-codes.md

App-server error codes (100-125)

---

docs/getting-started/release-notes/v2_3_0.md
docs/getting-started/release-notes/v2_3_1.md
sidebars.js

Signed-off-by: MarkAckert <mark.ackert@broadcom.com>

brief release notes for 2.3.1 patch

---

docs/getting-started/release-notes/v2_3_0.md
docs/getting-started/release-notes/v2_3_1.md
sidebars.js

Bring 2.3.1 release notes to staging so we're in sync with main

---

docs/user-guide/api-mediation-standalone.md

Revert "change parm name"

---

docs/appendix/server-component-manifest.md

fix formatting basePackage

---

docs/getting-started/release-notes/v2_4_0.md

Release notes for Zowe 2.4 release

Zowe v2.4 release notes

---

docs/extend/extend-apiml/implement-new-saf-provider.md

Fix variable names for Saf IDT

---

docs/user-guide/onboard-wizard.md
sidebars.js

fix: relative paths

---

docs/troubleshoot/app-framework/appserver-error-codes.md

Signed-off-by: 1000TurquoisePogs <sgrady@rocketsoftware.com>

Update appserver-error-codes 201-225

---

docs/troubleshoot/zowe-chat-troubleshoot/troubleshooting.md
docs/user-guide/zowe-chat/chat-use-interact-methods.md
docs/user-guide/zowe-chat/chat_install_overview.md
docs/user-guide/zowe-chat/chat_use_interact_methods.md
docs/user-guide/zowe-chat/troubleshooting.md
docs/user-guide/zowe-chat/zowe_chat_command/help/help_plugin_list.md
docs/user-guide/zowe-chat/zowe_chat_command/help/help_plugin_status.md
docs/user-guide/zowe-chat/zowe_chat_command/help_plugin.md
docs/user-guide/zowe-chat/zowe_chat_command/zos_console/zos_console_action.md
docs/user-guide/zowe-chat/zowe_chat_command/zos_console/zos_console_issue.md
docs/user-guide/zowe-chat/zowe_chat_command/zos_console/zos_console_issue_console.md
docs/user-guide/zowe-chat/zowe_chat_command/zos_dataset/zos_dataset_action.md
docs/user-guide/zowe-chat/zowe_chat_command/zos_dataset/zos_dataset_list.md
docs/user-guide/zowe-chat/zowe_chat_command/zos_dataset/zos_dataset_list_member.md
docs/user-guide/zowe-chat/zowe_chat_command/zos_dataset/zos_dataset_list_status.md
docs/user-guide/zowe-chat/zowe_chat_command/zos_error/zos_err_action.md
docs/user-guide/zowe-chat/zowe_chat_command/zos_error/zos_err_list.md
docs/user-guide/zowe-chat/zowe_chat_command/zos_error/zos_err_list_status.md
docs/user-guide/zowe-chat/zowe_chat_command/zos_help/zos_help.md
docs/user-guide/zowe-chat/zowe_chat_command/zos_help/zos_help_list.md
docs/user-guide/zowe-chat/zowe_chat_command/zos_job/zos_job_action.md
docs/user-guide/zowe-chat/zowe_chat_command/zos_job/zos_job_list.md
docs/user-guide/zowe-chat/zowe_chat_command/zos_job/zos_job_list_status.md
docs/user-guide/zowe-chat/zowe_chat_command/zos_resource.md
docs/user-guide/zowe-chat/zowe_chat_command/zos_uss/zos_uss_action.md
docs/user-guide/zowe-chat/zowe_chat_command/zos_uss/zos_uss_list.md
docs/user-guide/zowe-chat/zowe_chat_command/zos_uss/zos_uss_list_mounts.md
docs/user-guide/zowe-chat/zowe_chat_command/zos_uss/zos_uss_list_status.md
docs/user-guide/zowe-chat/zowe_chat_command_reference.md
sidebars.js

Create some placeholder files with simple structures 

Zowe chat doc proposal

---

docs/getting-started/overview.md

Update the Zowe Chat overview 

---

docs/extend/extend-apiml/authentication-for-apiml-services.md
docs/user-guide/api-mediation/api-gateway-configuration.md

Add API ML doc for passticket in custom header 

---

docs/getting-started/overview.md
docs/troubleshoot/troubleshoot-intellij.md
docs/user-guide/intellij-using.md

Review the intellij docs

---

docs/troubleshoot/cli/known-cli.md

Signed-off-by: anaxceron <ana.ceron@broadcom.com>
- Added the git bash double slash solution to [Known CLI Issues](https://docs.zowe.org/stable/troubleshoot/cli/known-cli)
- Rearranged list of known issues to follow (mostly) alpha order

Git Bash Known Issue doc

---

docs/getting-started/overview.md

Remove the topic Zowe Workflow wiZard - Incubator as the squad addressing this was discontinued.

remove Zowe Workflow wiZard

---

docs/troubleshoot/cli/known-cli.md

Added troubleshooting help content in [Known CLI Issues](https://docs.zowe.org/stable/troubleshoot/cli/known-cli) for [Issue 2475](https://github.com/zowe/docs-site/issues/2475)

added chain commands failure troubleshooting

---

docs/getting-started/zowe-architecture.md

The architecture page has some info that's a little out of date, but also a little misleading versus what we often want to tell our users.
I've not only updated the webui sections, but added sections for each component that standardizes some important knowledge: where to find the servers, and what their jobnames are.

Standardize zowe architecture page

---

docs/appendix/zowe-yaml-configuration.md

Signed-off-by: Leanid Astrakou <lastrakou@rocketsoftware.com>

Add doc section for offline YAML validator

---

docs/troubleshoot/app-framework/appserver-error-codes.md

Signed-off-by: Leanid Astrakou <lastrakou@rocketsoftware.com>
See title

Added message ids 226-250

---

versioned_sidebars/version-v1.28.x-sidebars.json

- added the sidebar for 1.28.2 release notes

add the 1.28.2 release note to the sidebar

---

docs/troubleshoot/app-framework/appserver-error-codes.md

Signed-off-by: Himani1519 <paripathak80@gmail.com>

message ids 276-300

---

docs/troubleshoot/app-framework/appserver-error-codes.md

Signed-off-by: Leanid Astrakou <lastrakou@rocketsoftware.com>

Added ZSF lines 326-349

---

docs/user-guide/api-mediation/using-api-mediation-layer.md

Two new features:
- Personal Access Tokens
- SMF Records
should be added to the topic 'Using API Mediation Layer' under Other features when using API ML

add recent apiml features to Using API Mediation Layer

---

docs/troubleshoot/app-framework/appserver-error-codes.md

Signed-off-by: 1000turquoisepogs <sgrady@rocketsoftware.com>

Adding app server messages 351-375

---

docs/troubleshoot/app-framework/appserver-error-codes.md

Signed-off-by: Timothy Gerstel <tgerstel@rocketsoftware.com>

Add app server lines 376 to 381

---

release-handbook/release_handbook.md

Adding instructions for updating the CLI web help and type doc

adding instructions for CLI web help and type doc

---

docs/user-guide/api-mediation/api-catalog-configuration.md
docs/user-guide/api-mediation/discovery-service-configuration.md
sidebars.js

Document Catalog config to hide service info

---

docs/user-guide/api-mediation/api-catalog-configuration.md

API ML: change config format to hide service info

---

docs/getting-started/release-notes/v2_6_0.md

Working draft of release notes from changelogs for Zowe v2.6

release notes v2.6

---

docs/troubleshoot/cli/cli-use-curl-to-troubleshoot.md

Created a new page to document using cURL for troubleshooting, including the following topics:
- Understanding cURL commands
- Comparing cURL and Zowe CLI commands

using cURL for troubleshooting CLI

---

docs/troubleshoot/cli/cli-use-curl-to-troubleshoot.md
sidebars.js

Added the cURL article to the sidebar

Anax usingcurl cli

---

docs/getting-started/release-notes/v2_6_0.md

removed release notes for Zowe CLI b/c they're for the next Zowe release

fixing release notes

---

docs/troubleshoot/ze/known-ze.md

Added section on BiDI language support

Added BiDi lang section

---

docs/user-guide/configure-xmem-server.md
versioned_docs/_version-v1.16.x/user-guide/configure-xmem-server.md
versioned_docs/_version-v1.17.x/user-guide/configure-xmem-server.md
versioned_docs/_version-v1.18.x/user-guide/configure-xmem-server.md
versioned_docs/_version-v1.19.x/user-guide/configure-xmem-server.md
versioned_docs/_version-v1.20.x/user-guide/configure-xmem-server.md
versioned_docs/_version-v1.21.x/user-guide/configure-xmem-server.md
versioned_docs/_version-v1.22.x/user-guide/configure-xmem-server.md
versioned_docs/_version-v1.23.x/user-guide/configure-xmem-server.md
versioned_docs/_version-v1.24.x/user-guide/configure-xmem-server.md
versioned_docs/_version-v1.25.x/user-guide/configure-xmem-server.md
versioned_docs/_version-v1.26.x/user-guide/configure-xmem-server.md
versioned_docs/version-v1.27.x/user-guide/configure-xmem-server.md
versioned_docs/version-v1.28.x/user-guide/configure-xmem-server.md
versioned_docs/version-v2.0.x/user-guide/configure-xmem-server.md
versioned_docs/version-v2.1.x/user-guide/configure-xmem-server.md
versioned_docs/version-v2.2.x/user-guide/configure-xmem-server.md
versioned_docs/version-v2.3.x/user-guide/configure-xmem-server.md
versioned_docs/version-v2.4.x/user-guide/configure-xmem-server.md
versioned_docs/version-v2.5.x/user-guide/configure-xmem-server.md

- corrected the typo ZWESI00 on this page
fix #2635 
- corrected the typo ZWESI00 on this page

Corrected the typo ZWESI00

---

docs/troubleshoot/ze/known-ze.md

Minor edits to use the word "files"

updated to use word "files"

---

docs/getting-started/release-notes/v2_6_1.md
sidebars.js

Signed-off-by: MarkAckert <mark.ackert@broadcom.com>

doc(2.6.1): create 2.6.1 release notes and sidebar update

---

docs/user-guide/mvd-using.md

I was working on desktop code refactoring and checking what was in our documentation for the user guide. I wanted to add a little bit more info that I find helpful for people to know about a few of the apps.

Minor desktop app description updates

---

docs/troubleshoot/troubleshoot-apiml.md

Addresses Issue [2649](https://github.com/zowe/docs-site/issues/2649)

Add ZWED0148E message and solution to API ML Troubleshooting

---

docs/extend/extend-apiml/api-mediation-passtickets.md

Fix API ML passticket doc

---

docs/user-guide/initialize-security-configuration.md

This PR addresses https://github.com/zowe/docs-site/issues/2591

Add note Re: TLS version support

---

docs/user-guide/configure-certificates-keyring.md
versioned_docs/version-v2.0.x/user-guide/configure-certificates-keyring.md
versioned_docs/version-v2.1.x/user-guide/configure-certificates-keyring.md
versioned_docs/version-v2.2.x/user-guide/configure-certificates-keyring.md
versioned_docs/version-v2.3.x/user-guide/configure-certificates-keyring.md
versioned_docs/version-v2.4.x/user-guide/configure-certificates-keyring.md
versioned_docs/version-v2.5.x/user-guide/configure-certificates-keyring.md

Update doc to be more up-to-date with V2 configurations

---

docs/contribute/guidelines-code/documentation.md
docs/extend/extend-cli/cli-extending-a-plugin.md

Fixed two broken links found w/ the new Link Checker

fixed broken links found in link checker

---

docs/user-guide/api-mediation/api-gateway-configuration.md

APIML: document the ssl debug prop

---

release-handbook/release_handbook.md

Added a few steps to Release Handbook to add more information to the process.

added steps to vnext doc prep handbook

---

docs/user-guide/install-zowe-smpe.md

Update install-zowe-smpe.md [2.7]

---

docs/getting-started/release-notes/v2_7_0.md

minor style edits to v2.7 release notes

minor style edits to release notes

---

docs/getting-started/release-notes/v2_7_0.md

This PR adds new features and bug fixes of API ML for v2.7

add apiml features and bug fixes

---

docs/appendix/zowe-yaml-configuration.md
docs/extend/extend-apiml/onboard-plain-java-enabler.md
docs/extend/extend-apiml/onboard-spring-boot-enabler.md
docs/troubleshoot/app-framework/app-troubleshoot.md
docs/troubleshoot/troubleshoot-apiml.md
docs/user-guide/configure-certificates-keyring.md

API ML: reflect keyring fixes into the doc

---

docs/getting-started/release-notes/v2_7_0.md

Adding missing punctuation to release notes.

Adding missing punctuation in v2.7 release notes

---

docs/getting-started/release-notes/v2_0_0.md
docs/getting-started/zowe_faq.md
docs/user-guide/cli-install-cli-checklist.md
docs/user-guide/cli-using-initializing-team-configuration.md
docs/user-guide/cli-using-sharing-team-config-files.md
docs/user-guide/cli-using-team-configuration-application-developers.md
docs/user-guide/cli-using-team-configuration-team-leaders.md
docs/user-guide/cli-using-test-zosmf-connection.md
docs/user-guide/cli-using-understand-profiles-configs.md
docs/user-guide/cli-using-understanding-core-command-groups.md
docs/user-guide/cli-using-using-profiles-v1.md
docs/user-guide/cli-using-using-team-profiles.md
docs/user-guide/install-cli-via-proxy.md
docs/user-guide/ze-profiles.md
docusaurus.config.js
sidebars.js
static/stable/web_help/docs/zowe_profiles_delete_jclx-profile.html
static/stable/web_help/docs/zowe_profiles_list_jclx-profiles.html
static/stable/web_help/docs/zowe_profiles_set-default_jclx-profile.html
static/v2.6.x/web_help/docs/zowe_endevor_initialize.html
static/v2.6.x/web_help/docs/zowe_zos-jobs_modify.html
static/v2.6.x/web_help/docs/zowe_zos-jobs_modify_job.html
versioned_docs/version-v2.6.x/user-guide/configure-certificates-keyring.md

Anax 270 fixmergeconflictindocsstaging

---

docs/troubleshoot/troubleshoot-apiml.md

This PR is to add a troubleshooting section for SSL/TLS setup and links to the corresponding blog post.

Add troubleshooting ssl tls setup to apiml troubleshooting

---

docusaurus.config.js
package.json
src/components/SearchHeader/SearchHeader.js

Updating API key
limiting memory space in package.json file to test validation for Netlify build memory limits

updating API keys and limiting mem space

---

docusaurus.config.js

Adding API key for Search functionality fix

updating API key for Search functionality fix

---

docs/user-guide/configure-xmem-server.md

- corrected a load module name
fix #2768 

Correct a load module name

---

dco_signoffs/Timothy-Gerstel-docs-site.txt

Amend old DCO signoffs

---

versioned_docs/version-v1.28.x/getting-started/release-notes/v1_28_3.md

Added release notes and vulnerabilities fixed for Zowe v1.28.3

added release notes for v1.28.3

---

versioned_docs/version-v1.28.x/getting-started/release-notes/v1_28_3.md

Updated release notes per Fernando's feedback:
- minor rewording
- added missing PR links

updates to release notes per Fernando feedback

---

docs/user-guide/install-zowe-smpe.md

Broken link fix sam

---

docs/user-guide/cli-idfplugin.md
sidebars.js

new cli plugin for ID mapping

---

docs/extend/extend-apiml/custom-metadata.md
docs/extend/extend-apiml/onboard-direct-eureka-call.md
docs/extend/extend-apiml/onboard-overview.md
docs/getting-started/zowe-resources.md
docs/troubleshoot/troubleshoot-apiml.md
docs/user-guide/api-mediation/api-gateway-configuration.md
docs/user-guide/api-mediation/api-mediation-internal-configuration.md
docs/user-guide/mvd-using.md

fix API ML security links

---

docs/getting-started/release-notes/v2_8_0.md

Making minor edits to Zowe v2.8 release notes

editing v2.8 release notes

---

package-lock.json

Zowe v2.8 site PDF

---

docs/user-guide/api-mediation/api-gateway-configuration.md

This PR standardizes the format and language conventions across the whole document

Language/Formatting refactor of API Gateway Configuration

---

docs/getting-started/cli-getting-started.md
versioned_docs/version-v1.28.x/getting-started/cli-getting-started.md

Remove deprecated information

---

docs/troubleshoot/ze/ze-known-limits.md
sidebars.js

Added new section re: ZE known limitation surrounding credentials and virtual environments

ZE known limitation re: creds

---

docs/troubleshoot/cli/troubleshoot-cli-plugins.md
docs/user-guide/ze-use-cases.md

Minor updates based on feedback from Scott on [PR 2850](https://github.com/zowe/docs-site/pull/2850) and [PR 2837](https://github.com/zowe/docs-site/pull/2837).

minor updates based on Scott feedback

---

.github/workflows/netlify.yml

Workaround for https://github.com/actions/checkout/issues/881 - this should fix the Netlify check not showing up on fork PRs 🙂 

Fix Netlify workflow to pull correct Git ref

---

.github/workflows/build-docs.yml

Ports changes from #2913 to docs-staging branch.

[docs-staging] Fix Netlify preview missing for fork PRs

---

versioned_sidebars/version-v2.8.x-sidebars.json

Revert "Overwrite the config certificate section"

---

docs/user-guide/zowe-getting-started-tutorial.md

add Zowe croass memory server to server-side components

---

versioned_docs/version-v1.28.x/getting-started/release-notes/v1_28_4.md
versioned_sidebars/version-v1.28.x-sidebars.json

setting up doc for v1.28.4

---

release-handbook/release_notes_guide.md
versioned_docs/version-v1.28.x/getting-started/release-notes/v1_28_4.md

Release notes for Zowe CLI, Imperative Framework, CLI plug-ins for v1.28.4

release notes draft for v1.28.4

---

docs/user-guide/cli-idfplugin.md

Fix IDF Plugin name and markdown formatting

Fix IDF Plugin name and markdown formatting

---

versioned_docs/version-v1.28.x/getting-started/release-notes/v1_28_4.md

remove apiml section in v1_28_4 release notes

---

docs/user-guide/k8s-introduction.md
versioned_docs/version-v2.5.x/user-guide/k8s-introduction.md
versioned_docs/version-v2.6.x/user-guide/k8s-introduction.md
versioned_docs/version-v2.7.x/user-guide/k8s-introduction.md
versioned_docs/version-v2.8.x/user-guide/k8s-introduction.md

- Updated the instructions for `useConfigmgr` parameter

update the k8s instructions

---

docs/troubleshoot/ze/troubleshoot-ze.md

This PR addresses [Issue 2979
](https://github.com/zowe/docs-site/issues/2979)
- Completing the path listed in the [Before reaching out for support](https://docs.zowe.org/stable/troubleshoot/ze/troubleshoot-ze#before-reaching-out-for-support) section. 
- Adding note advising that paths could be different.
- Adding links to other articles for additional help/context
- Updating Note formatting

updating directory path; adding path note

---

docs/user-guide/systemrequirements-zos.md
versioned_docs/_version-v1.22.x/user-guide/systemrequirements-zos.md
versioned_docs/_version-v1.23.x/user-guide/systemrequirements-zos.md
versioned_docs/_version-v1.24.x/user-guide/systemrequirements-zos.md
versioned_docs/_version-v1.25.x/user-guide/systemrequirements-zos.md
versioned_docs/_version-v1.26.x/user-guide/systemrequirements-zos.md
versioned_docs/version-v1.27.x/user-guide/systemrequirements-zos.md
versioned_docs/version-v1.28.x/user-guide/systemrequirements-zos.md
versioned_docs/version-v2.3.x/user-guide/systemrequirements-zos.md
versioned_docs/version-v2.4.x/user-guide/systemrequirements-zos.md
versioned_docs/version-v2.5.x/user-guide/systemrequirements-zos.md
versioned_docs/version-v2.6.x/user-guide/systemrequirements-zos.md
versioned_docs/version-v2.7.x/user-guide/systemrequirements-zos.md
versioned_docs/version-v2.8.x/user-guide/systemrequirements-zos.md

porting #3000 to master and older versions

 Stop tracking specific browser versions

---

docs/getting-started/release-notes/v2_10_0.md

ZE, Zowe CLI release notes for Zowe v2.10

CLI, ZE v2.10 release notes

---

docs/user-guide/cli-idfplugin.md

- Correcting product names
- Style edits

correcting prod names, updating to follow style

---

docs/getting-started/release-notes/v2_10_0.md

Last minute addition of a new feature in API ML for 2.10.

Add API ML feature to 2.10 release notes

---

docs/troubleshoot/troubleshoot-apiml.md
docs/user-guide/initialize-zos-system.md

This PR fixes broken links in the area of API ML for 2.10.

Fix broken links for 2.10 (API ML)

---

docs/troubleshoot/troubleshoot-apiml-error-codes.md

- [ x] If the changes in this PR is part of the next future release, make this pull request against the **docs-staging** branch which will be published at the next release boundary. If the changes in this PR are part of the current release, use the default base branch, **master**. For more information about branches, see https://github.com/zowe/docs-site/tree/master#understanding-the-doc-branches. 

adding zosmf  and conformance error codes

---

docs/contribute/contributing.md
release-handbook/release_notes_guide.md

Made the following changes:
- Added "hotkeys" to the list of words to avoid
- Added listing on using punctuation in lists
- Added listing on release notes
- Other minor updates

updating style guide

---

docs/getting-started/release-notes/v2_10_0.md

Made minor fixes to the v2.10 release notes

minor edits to release notes

---

docs/troubleshoot/app-framework/appserver-error-codes.md

Updated links with the latest ones. 

link updates

---

docs/getting-started/release-notes/v2_10_0.md

Corrected release note for CLI Imperative

corrected CLI IF release note

---

docs/troubleshoot/troubleshoot-apiml-error-codes.md

Update message codes with recent gateway additions / removals

Update gateway message codes

---

docs/user-guide/systemrequirements-zos.md

Testing the tags feature in Algolia

testing tags1

---

docs/user-guide/systemrequirements-zos.md

Testing tag "monacat" to see how Algolia picks it up in search functionality

testing a new tag

---

docs/user-guide/k8s-introduction.md

- Removed the limitation since it's been GAed.

Update container limitations

---

docs/troubleshoot/troubleshoot-apiml-error-codes.md
docs/troubleshoot/upgrade-zowe-no-downtime.md

Signed-off-by: Pablo Hernán Carle <pablo.carle@broadcom.com>
Add a document with a procedure to perform an upgrade of Zowe without downtime, with focus on API Mediation Layer.

Procedure for Zowe upgrade in high availability without downtime

---

docs/user-guide/api-mediation/upgrade-zowe-no-downtime.md
sidebars.js

This PR adds the sidebars.js file for Upgrade Zowe server-side components in high availability
and moves the file under user-guide advanced configuration

Add sidebar.js ref for Upgrade Zowe with HA 

---

docs/appendix/zwe_server_command_reference/zwe/zwe-stop.md

fixed a parameter name

---

docs/user-guide/certificates-configuration-questionnaire.md

This PR offers an important tip to consult with your security admin if configuring certificates for production and removes numerous links previously included which pertain to each question in the flow.,

Refactor questionnaire

---

.github/workflows/build-docs.yml

Update Node.js version in build-docs.yml

---

release-handbook/pdf_generation_guide.md

- Adding site PDF for Zowe v2.11
- Updating instructions for [generating site PDFs](https://github.com/zowe/docs-site/blob/master/release-handbook/pdf_generation_guide.md#steps-to-manually-generate-pdf-recommended)

adding v2.11 PDF, updating PDF generating instructions

---

docusaurus.config.js
tpsr/tpsr-v1.28.5.md
versioned_docs/version-v1.28.x/getting-started/release-notes/v1_28_5.md

- Adding headers to the release notes file
- Adding placeholder file for 1.28.5 TPSRs

adding RN headers, TPSR placeholder file

---

docs/getting-started/zowe_faq.md
docs/user-guide/ze-usage.md

Documenting how to associate a language to a file extension type in VS Code:
- Added question to [ZE FAQs](https://docs.zowe.org/stable/getting-started/zowe_faq#zowe-explorer-faq)
- Added section to [Usage tips](https://docs.zowe.org/stable/user-guide/ze-usage#usage-tips)
Also turned bullet list in [Usage tips](https://docs.zowe.org/stable/user-guide/ze-usage#usage-tips) to a list w/ headers.

documenting how to associate languages, file extensions

---

versioned_docs/version-v1.28.x/getting-started/release-notes/v1_28_5.md

This PR adds the bug fixes for API ML for v1.28.5 to the release notes.

Add Release Notes for API ML bug fixes for v1.28.5

---

versioned_docs/version-v1.28.x/getting-started/release-notes/v1_28_5.md

There are no changes in App Framework for the release v 1.28.5.

Updated v 1.28.5 for App Framework

---

docs/getting-started/zowe-security-authentication.md

This PR addresses the broken link in Issue [#3110](https://github.com/zowe/docs-site/issues/3110)

Address broken link in Issue 3110

---

versioned_docs/version-v1.28.x/getting-started/release-notes/v1_28_5.md

Revised PR for bugfixes for API ML for 1.28.5

Revise apiml bug fixes for 1.28.5

---

docs/user-guide/api-mediation/upgrade-zowe-no-downtime.md
docs/user-guide/generate-certificates.md

This PR fixes links in API ML and certificate doc

Fix links in API ML and certificate doc

---

docs/extend/extend-cli/cli-devTutorials.md
docs/getting-started/zowe-security-authentication.md
docs/troubleshoot/cli/troubleshoot-cli-credentials.md
package-lock.json
package.json
sidebars.js

Adding documentation for authentication mechanisms:
- New section in [Developing for Zowe CLI](https://docs.zowe.org/stable/extend/extend-cli/cli-devTutorials)
- New page in the [Troubleshooting Zowe CLI](https://docs.zowe.org/stable/troubleshoot/cli/troubleshoot-cli)
- updated sidebar to include the new Troubleshoot page

documenting auth mechanisms

---

versioned_docs/version-v2.9.x/troubleshoot/troubleshoot-apiml.md

Fixing broken link from [Issue 3171](https://github.com/zowe/docs-site/issues/3171)

Fix for broken API ML link in v2.9 for Issue 3171

---

docs/getting-started/release-notes/v2_12_0.md
docusaurus.config.js
sidebars.js

- Bumping new release version
- Adding placeholder files for v2.12 release notes, TPSR

bumping new release version, adding placeholder files

---

docs/getting-started/release-notes/v2_12_0.md

This PR adds features and bug fixes for API ML for v2.12

API ML features and bugfixes for v2.12

---

docs/getting-started/release-notes/v2_12_0.md

- Adding link to Secrets SDK release note
- Removing Zowe Explorer

adding a link; removing ZE headers

---

docs/troubleshoot/app-framework/appserver-error-codes.md

fix the error msg

---

docs/getting-started/release-notes/v2_12_0.md

Removed headers that had no release notes under them

removed headers for missing release notes

---

docs/getting-started/release-notes/v2_12_0.md

Added notes for Application Framework section in the release notes for version 2.12.
Please review. I have also addressed the earlier comments.

updated release notes 2.12

---

docs/user-guide/ze-working-with-data-sets.md
docs/user-guide/ze-working-with-jobs.md
docs/user-guide/ze-working-with-uss-files.md

This PR returns the content to the chunked articles from the original ze-use-cases.

Add content back to ze chunked articles from ze-use-cases

---

sidebars.js

Adjust the advanced config section

---

docs/user-guide/install-zos.md

This PR is to improve the readability of the Installation overview and to list the zwe init subcommands in the order they are performed in zwe init.

Language refactor of Installation overview

---

.github/workflows/pull-request-checker.yml

non-doc-squad test

---

docs/extend/extend-apiml/api-mediation-message-service.md
docs/extend/extend-apiml/create-apiml-extension.md
docs/extend/extend-apiml/custom-metadata.md
docs/extend/extend-apiml/implement-new-saf-provider.md
docs/extend/extend-apiml/onboard-static-definition.md
docs/user-guide/api-mediation-change-password-via-catalog.md
docs/user-guide/api-mediation-standalone.md
docs/user-guide/api-mediation-view-service-information-and-api-doc.md
docs/user-guide/api-mediation/api-catalog-configuration.md
docs/user-guide/api-mediation/api-mediation-jwt-token-refresh.md
docs/user-guide/api-mediation/api-mediation-personal-access-token.md
docs/user-guide/api-mediation/api-mediation-update-password.md
sidebars.js

This PR updates titles according to Zowe doc standards and adds note adaminations.

fix api ml titles

---

docs/user-guide/address-authentication-requirements.md
docs/user-guide/address-browser-requirements.md
docs/user-guide/address-network-requirements.md
docs/user-guide/address-storage-requirements.md
docs/user-guide/configure-uss.md
docs/user-guide/install-nodejs-zos.md
docs/user-guide/systemrequirements-zos.md

This PR adds required roles for the Preparing for Installation section

Add user roles for preparing for Installation section

---

docs/extend/extend-apiml/websocket.md
docs/user-guide/zos-components-installation-checklist.md
sidebars.js

This PR updates the installation checklist following the reorganization/ refactoring of the install and configure documentation for Zowe server-side components.

Update installation checklist post install/config restructure

---

docs/getting-started/release-notes/v2_12_0.md

Adding release notes for ZE v 2.12

adding ZE v2.12 release notes

---

docs/user-guide/address-security-requirements.md
docs/user-guide/configure-sysplex.md
docs/user-guide/configure-uss.md
docs/user-guide/configure-zos-system.md
docs/user-guide/configure-zowe-zosmf-workflow.md
docs/user-guide/configuring-security.md
docs/user-guide/initialize-security-configuration.md
docs/user-guide/install-zowe-pswi-address-requirements.md
docs/user-guide/systemrequirements-zos.md
docs/user-guide/systemrequirements-zosmf.md
docs/user-guide/verify-zowe-runtime-install.md

This PR fixes adomnitions (notes, important, etc) and some minor formatting.

Fix adominitions

---

.github/workflows/pull-request-checker.yml

updating comment line breaks

---

.github/workflows/pull-request-checker.yml

updating comments

---

docs/user-guide/api-mediation/api-mediation-multi-tenancy.md
sidebars.js

The Pull request adds the documentation of new functionality focused on deployments of the API Mediation Layer in the service providers environment allowing them to properly handle multi-tenant setup with proper distinguishing between the tenants. 
**resolve**: https://github.com/zowe/api-layer/issues/2651

API Mediation Layer newly supports multi-tenant deployments

---

dco_signoffs/Lobhas-Paradkar-docs-site.txt

Uploaded a .txt file for DCO signoff.

Added .txt file for DCO signoff

---

docusaurus.config.js
sidebars.js

bumping to 2.13

---

docs/extend/extend-apiml/authentication-for-apiml-services.md

This PR is an initial refactor as a request by customer to clarify the procedure to authenticate with client certificates.

Initial refactor of Authentication with client certificates

---

docs/user-guide/api-mediation/configuration-routing.md
docs/user-guide/api-mediation/configuration-single-sign-on-user.md

This PR addresses a few broken links and missing functionality info in the bucket article Customizing routing behavior in Advanced API Ml config.

fix broken links and add routing behavior topics to bucket topic

---

docs/getting-started/release-notes/v2_13_0.md

minor fixes in API ML release notes for 2.13

minor typo and grammar fixes

---

docs/getting-started/release-notes/v2_13_0.md

Making minor fixes re: style, misplaced bullets, typos

fixing minor style items, typos, misplaced bullets

---

docs/whats-new/release-notes/v2_13_0.md
docusaurus.config.js
sidebars.js

Cherry-pick the 2.13.0 update from master to doc-staging

setting latest to 2.13.0 and updating whats-new

---

docs/getting-started/zowe_faq.md

adding FAQs re: MFA for ZE and Zowe CLI

adding FAQs re: MFA for ZE and Zowe CLI

---

docs/extend/extend-apiml/api-mediation-infinispan.md
docs/user-guide/configure-caching-service-ha.md
docs/user-guide/install-zos.md
sidebars.js

configure infinispan using zowe yaml

---

docs/extend/extend-apiml/api-mediation-oidc-authentication.md

Describe your pull request here: Add note Re: unavailability of OIDC feature on ACF2 systems.
List the file(s) included in this PR: https://docs.zowe.org/stable/extend/extend-apiml/api-mediation-oidc-authentication/
v2

Note re OIDC unavailability on ACF2 systems

---

docs/user-guide/api-mediation/routing-requests-to-rest-apis.md

Update the general description

---

docs/getting-started/zowe_faq.md

Describe your pull request here: Adding a new FAQ re: how to submit an enhancement idea for Zowe
List the file(s) included in this PR: zowe_faq.md

adding FAQ re: submitting enhancement requests

---

docs/troubleshoot/cli/troubleshoot-ibm-db2-database-plug-in.md
docs/user-guide/cli-db2plugin.md
sidebars.js

Describe your pull request here: Adding troubleshooting doc for IBM Db2 Database Plug-in
List the file(s) included in this PR: troubleshoot-ibm-db2-database-plug-in.md

Anax v2.13 odbctroubleshoot cli

---

docs/whats-new/release-notes/v2_14_0.md

Describe your pull request here: adding Zowe CLI release notes
List the file(s) included in this PR: v2_14_0.md

added Zowe CLI release notes

---

docs/whats-new/release-notes/v2_14_0.md

Describe your pull request here: This PR adds API ML release notes for 2.14 
List the file(s) included in this PR: v2_14_0.md

Add API ML release notes for 2.14 

---

docs/appendix/zowe-glossary.md
docs/appendix/zowe-security-glossary.md
sidebars.js

Describe your pull request here: Previously the glossary of security terminology was not shown in the sidebar. This PR adds it to the sidebar and consolidates API ML component descriptions in the larger glossary of terms
List the file(s) included in this PR: appendix/zowe-security-glossary.md, sidebars.js, appendix/zowe-glossary.md

Improve access to security terminology

---

docs/extend/extend-apiml/api-mediation-caching-service.md
docs/extend/extend-apiml/api-mediation-infinispan.md
sidebars.js

Describe your pull request here: infinispan was missing from the sidebar. This PR addresses this.
List the file(s) included in this PR: api-mediation-infinispan.md, using-caching-service.md

Add using infinispan to sidebar

---

docs/whats-new/release-notes/v2_13_0.md
docs/whats-new/release-notes/v2_14_0.md
release-handbook/release_notes_guide.md

Describe your pull request here: Updating release notes to include YouTube link
List the file(s) included in this PR: v2_12_0.md

updating release notes to include YouTube link

---

docs/troubleshoot/cli/troubleshoot-ibm-db2-database-plug-in.md
docs/user-guide/cli-db2plugin.md

Describe your pull request here: Addressing feedback from [PR 3352](https://github.com/zowe/docs-site/pull/3352)
List the file(s) included in this PR: troubleshoot-ibm-db2-database-plug-in.md

addressing post-merge feedback from PR 3352

---

docs/extend/extend-apiml/authentication-for-apiml-services.md
sidebars.js

Describe your pull request here: This PR creates the sidebar files for the single sign on authentication methods
List the file(s) included in this PR: sidebars.js, authentication-for-apiml-services (deprecated content)

Create sidebar for single sign on for API ML

---

docs/whats-new/release-notes/v2_14_0.md

Describe your pull request here: The PR adds the full list of bug fixes for v2.14 for API ML
List the file(s) included in this PR: v2_14_0.md

Add API ML bugfixes for v2.14

---

docs/getting-started/user-roadmap-apiml.md
docs/getting-started/zowe-security-overview.md
docs/user-guide/authenticating-with-client-certificates.md
sidebars.js

Describe your pull request here: This PR fixes links in API ML
List the file(s) included in this PR: user-roadmap-apiml

Janan07 fix security overview link

---

docs/user-guide/api-mediation-sso.md
sidebars.js

Describe your pull request here: Moves the landing page for SSO into the using section and fixes links where necessary.
List the file(s) included in this PR: sidebars.js, api-mediation-sso

Move API ML SSO landing page from extend to user guide

---

docs/user-guide/api-mediation-sso.md
docs/user-guide/authenticating-with-client-certificates.md
docs/user-guide/authenticating-with-jwt-token.md
docs/user-guide/initialize-zos-system.md

Describe your pull request here: Fixes formatting, broken links, required roles
List the file(s) included in this PR: authenticating-with-client-certificates, authenticating-with-jwt-token, initialize-zos-system, api-mediation-sso

link/format/user fixes to Using SSO with API ML articles

---

docs/user-guide/api-mediation/authenticating-with-personal-access-token.md
docs/user-guide/authenticating-with-client-certificates.md

Describe your pull request here: Link fix and minor formatting fixes
List the file(s) included in this PR: authenticating-with-client-certificates.md, authentication-with-personal-access-token.md

Link fix and other minor fixes in API ML SSO doc

---

sidebars.js

Describe your pull request here: Removing a duplicate APIML article from sidebar to fix infinity loop blocking the creation of the Zowe v2.14 site PDF.
List the file(s) included in this PR: api-mediation-infinispan.md

removing duplicate article in sidebar

---

docs/user-guide/systemrequirements-zos.md

This PR is for certifying new Java 17 system requirement for Zowe server side (APIML)
docs/user-guide/systemrequirements-zos.md

Update the required Java runtime version to 17 for v3

---

docs/user-guide/api-mediation/routing-requests-to-rest-apis.md
docs/user-guide/api-mediation/use-graphql-api.md
sidebars.js

Describe your pull request here: This PR fixes broken links and other fixes after  publication of the API routing section.
List the file(s) included in this PR: sidebars.js, routing-requests-to-rest-apis, use-graphql

Clean up API routing section

---

docs/user-guide/authenticating-with-client-certificates.md

Describe your pull request here: Initial edits to authenticating with client certs

Apply edits to authenticating with client certificate

---

docs/user-guide/authenticating-with-client-certificates.md

Describe your pull request here: Further edits from peer review of authenticating with client certificates

Additional edits to Authenticating with client certificates

---

docs/user-guide/authenticating-with-client-certificates.md

Describe your pull request here: This PR describes how to register the client certificate with the user ID

How to register the client certificate with the user ID

---

docs/user-guide/authenticating-with-client-certificates.md

Describe your pull request here: link and formatting fixes

Fix formatting and links for Authenticating with Client Certificates

---

docs/extend/zowe-conformance-program.md
docs/user-guide/ZE-install-checklist.md
docs/user-guide/install-zowe-client-side-components.md
docs/user-guide/user-roadmap-zowe-cli copy.md
docs/user-guide/user-roadmap-zowe-cli.md
sidebars.js

Updating the following topics for Zowe V3: 
- Installing Zowe client-side components (currently a sidebar header with no target content)
- [Zowe CLI](https://docs.zowe.org/stable/user-guide/user-roadmap-zowe-cli)
List the file(s) included in this PR: user-roadmap-zowe-cli.md, others

updating Zowe CLI installation topics for Zowe V3

---

docs/user-guide/api-mediation-sso.md

Describe your pull request here: address broken links and SSO term in SSO overview article
List the file(s) included in this PR: api-mediation-sso.md

Apply fixes to sso overview

---

docs/user-guide/address-authentication-requirements.md
package-lock.json
sidebars.js

Describe your pull request here: Incorporation comments from reviewer on Address Authentication requirements
List the file(s) included in this PR: address-authentication-requirements.md

Minor refactoring of MFA from review

---

docs/appendix/zowe-glossary.md
docs/user-guide/cli-using-integrating-apiml.md

Describe your pull request here: Updates to address [Issue 3440](https://github.com/zowe/docs-site/issues/3440)
List the file(s) included in this PR: cli-using-integrating-apiml.md

fixing commands, adding note, other edits

---

docs/user-guide/cli-using-using-daemon-mode.md

Describe your pull request here: Re-adding previously removed content re: daemon mode; removing other daemon mode content.
List the file(s) included in this PR: cli-using-using-daemon-mode

updating daemon mode examples

---

docs/appendix/zowe-glossary.md
docs/user-guide/cli-using-integrating-apiml.md

Describe your pull request here: Making minor edits from post-merge feedback from @sbohnert re: PR 3469
List the file(s) included in this PR: zowe-glossary.md

minor edits post merge of PR3469

---

docs/extend/extend-apiml/authentication-for-apiml-services.md
docs/user-guide/api-mediation-sso.md

Remove confusing information in the info on SSO. Linked to https://github.com/zowe/docs-site/issues/3445 and https://github.com/zowe/docs-site/issues/3447
- /docs/user-guide/api-mediation-sso.md

Remove private and public clients

---

docs/getting-started/user-roadmap-client-sdk.md
sidebars.js

Describe your pull request here: This PR add the User Roadmap Client SDK to the sidebar
List the file(s) included in this PR: sidebars.js, user-roadmap-client-sdk

Add client sdk info to sidebar

---

docs/troubleshoot/ze/known-ze.md

Describe your pull request here: Adding troubleshooting content for how to use certificates in ZE for API ML
List the file(s) included in this PR: known-ze.md

adding certificate troubleshoot

---

docs/user-guide/install-zos.md
docs/user-guide/install-zowe-smpe-overview.md
docs/user-guide/install-zowe-smpe.md
docs/user-guide/k8s-introduction.md

Describe your pull request here: fix links in user-guide
List the file(s) included in this PR: k8s-introduction.md

fix link syntax

---

docs/user-guide/k8s-introduction.md

Describe your pull request here: fix links in k8s-installation.md
List the file(s) included in this PR: k8s-installation.md

link fixes

---

tpsr/tpsr-v2.15.x.md

Describe your pull request here: adds TPSRs for v2.15
List the file(s) included in this PR: tpsr-v2.15

add v2.15 TPSRs

---

.github/workflows/build-docs.yml
.github/workflows/link-checker.yml
package-lock.json
package.json

* Hopefully fix "out of space" errors at end of Docusaurus build (ports b3f7e9ab8844b6a0863a154354495159478a883b and a3ae8300854085495202983a0e00dbbd64ebf0ad from the v3 branch)
* Make link checker workflow run more slowly to reduce "too many requests" errors - it's still not the bottleneck 🙂 
List the file(s) included in this PR: build-docs.yml workflow

Remove files when creating tars to save disk space

---

docs/extend/extend-apiml/authentication-for-apiml-services.md

Describe your pull request here: Add info about  auth provider recommendations
List the file(s) included in this PR: authentication-for-apiml-services.md

Add info about  auth provider recommendations

---

docs/user-guide/authenticating-with-client-certificates.md

Updating incorrect property name. 
- docs/user-guide/authenticating-with-client-certificates.md

Incorrect property name

---

docs/extend/extend-apiml/authentication-for-apiml-services.md

Describe your pull request here: Fix links in authentication for apiml services
List the file(s) included in this PR: authentication-for-apiml-services.md

link fixes in Authentication for API ML Services

---

docs/troubleshoot/troubleshoot-apiml-error-codes.md

add new APIML troubleshooting messages

---

docs/extend/extend-apiml/api-mediation-oidc-authentication.md

Describe your pull request here: Add tip and link re: CLI IDF plug-in
List the file(s) included in this PR: api-mediation-oidc-authentication.md

Add tip re: CLI IDF plug-in

---

docs/whats-new/release-notes/v2_15_0.md

Describe your pull request here: add 2.14 vulnerabilities fixed section
List the file(s) included in this PR: v2_15_0.md

Add 2.14 vulnerabilities fixed

---

sidebars.js

Describe your pull request here: move caching service config under install and config
List the file(s) included in this PR: sidebars.js

Move caching service config under installing in sidebar

---

docs/extend/extend-apiml/api-mediation-oidc-authentication.md
docs/user-guide/api-mediation/authenticating-with-personal-access-token.md
sidebars.js

Describe your pull request here: This PR addresses this task: https://rally1.rallydev.com/#/685948290539ud/iterationstatus?detail=%2Ftask%2F755408821495
List the file(s) included in this PR: Authenticating OIDC

Move Authenticating OIDC under SSO in Using

---

sidebars.js

Describe your pull request here: remove onboard-direct-eureka-call from sidebar
List the file(s) included in this PR: remove onboard-direct-eureka-call.md

Remove onboard-direct-eureka-call from sidebar

---

docs/extend/extend-apiml/api-mediation-layer-development-setup.md
docs/extend/extend-apiml/authentication-for-apiml-services.md
docs/user-guide/authentication-providers-for-apiml.md
sidebars.js

Describe your pull request here: This PR creates the article authentication-providers-for-apiml.md as a stand-alone article
List the file(s) included in this PR: authentication-providers-for-apiml.md, authentication-for-apiml-services.md, sidebars.js

Create Authentication providers for API ML

---

docs/user-guide/systemrequirements-zos.md

This is to include SDSF under ZOS requirements for Zowe installation 
systemrequirements-zos.md

Update systemrequirements-zos.md for sdsf

---

docs/user-guide/cli-db2plugin.md

Describe your pull request here: Updating the content for creating profiles w/ commands for Zowe V3.
List the file(s) included in this PR: cli-db2plugin.md

updated content for creating a profile w/ commands

---

docs/extend/extend-apiml/authentication-for-apiml-services.md
docs/user-guide/start-zowe-zos.md

Describe your pull request here: Fixes to Start Zowe z/OS and Authentication for API ML services from peer review
List the file(s) included in this PR: start-zowe-zos.md, authentication-for-apiml-services.md

Fixes to Start Zowe z/OS and Authentication for API ML services from peer review

---

docs/extend/dynamic-static-registration-overview.md
docs/extend/extend-desktop/mvd-extendingzlux.md
docs/extend/extend-zowe-overview.md

Describe your pull request here: This PR reorganizes the Extending Zowe overview
List the file(s) included in this PR: extend-zowe-overview.md, dynamic-static-registration-overview.md, mvd-extendingzlux.md

Clean up extend zowe overview

---

docs/user-guide/api-mediation/configuration-at-tls.md

Describe your pull request here: Fix admonition
List the file(s) included in this PR: configuration-at-tls.md

Fix admonition

---

docs/extend/extend-apiml/onboard-direct-eureka-call.md

Describe your pull request here: fix links in onboard-direct-eureka-call
List the file(s) included in this PR: onboard-direct-eureka-call.md

fix links in onboard-direct-eureka-call

---

docs/user-guide/authenticating-with-client-certificates.md

Describe your pull request here: Fix links in Authenticating with Client Certificate

Fix links in Authenticating with Client Certificate

---

docs/user-guide/authenticating-with-client-certificates.md

Describe your pull request here: Fix anchors in authenticating-with-client-certificates.md

fix anchors

---

docs/user-guide/obtaining-information-about-api-services.md

Fix incorrect URL
/docs/user-guide/obtaining-information-about-api-services.md

Fix the URL for specific service information

---

docs/troubleshoot/ze/troubleshoot-ze.md
docs/user-guide/ze-profiles.md

Describe your pull request here: Adding troubleshooting doc for proxy support
List the file(s) included in this PR: troubleshoot-ze.md

Proxy support doc for ZE

---

docs/user-guide/installandconfig.md

Add the notes about the standard behavior of /tmp
docs/user-guide/installandconfig.md

Add the information about /tmp

---

docs/user-guide/api-mediation/configuration-jwt.md
docs/user-guide/systemrequirements-zos.md

Describe your pull request here: Add Mainframe resource consumption section
List the file(s) included in this PR: systemrequirements-zos.md

Add Mainframe resource consumption section

---

docs/user-guide/api-mediation/api-mediation-personal-access-token.md

Return the page for personal access token. Linked to the #3558.
- docs/user-guide/api-mediation/api-mediation-personal-access-token.md

Return the page with info where the information moved

---

versioned_docs/version-v2.6.x/user-guide/systemrequirements-zos.md

Describe your pull request here: update service name for port 7553 in v2.6
List the file(s) included in this PR: systemrequirements-zos.md (for version-v2.6.x)

update service name for port 7553

---

docs/user-guide/initialize-zos-system.md

Describe your pull request here: add caution macro for validation
List the file(s) included in this PR: initialize-zos-system.md

add validate warning

---

docs/user-guide/cli-configure-scs-on-headless-linux-os.md
docs/user-guide/cli-using-using-environment-variables.md

Describe your pull request here: adding do re: using environment variables in CI/CD pipelines. resolves [Issue 3504](https://github.com/zowe/docs-site/issues/3504).
List the file(s) included in this PR: cli-using-environment-variables.md

adding CICD env variable example

---

docs/user-guide/cli-using-integrating-apiml.md

Describe your pull request here: Addresses [Issue 3492](https://github.com/zowe/docs-site/issues/3492).
List the file(s) included in this PR: cli-using-integrating-apiml.md

doc for client certificates in api ml, cli integration

---

docs/user-guide/install-zos.md

Describe your pull request here: fix link in install-zos
List the file(s) included in this PR:  install-zos

fix link in install-zos

---

docs/extend/extend-apiml/api-medation-sso-integration-extenders.md
docs/extend/extend-apiml/authentication-for-apiml-services.md
docs/extend/extend-apiml/onboard-static-definition.md
sidebars.js

Explain the methods that the extenders can use to participate in the Single Sign On. 
- docs/extend/extend-apiml/api-medation-sso-integration-extenders.md
- docs/extend/extend-apiml/authentication-for-apiml-services.md
- docs/extend/extend-apiml/onboard-static-definition.md
- sidebar.js

Create Single Sign On section for Extenders

---

docs/whats-new/release-notes/v2_15_0.md

Describe your pull request here: add pswi 2.15.0 release notes
List the file(s) included in this PR: whats-new/release_notes/v2_15_0.md
Signed-off-by: MarkAckert <mark.ackert@broadcom.com>
A second PR will be opened to cherry-pick this into docs-staging

added pswi bugfix note

---

docusaurus.config.js
release-handbook/creating_site_banner.md

Describe your pull request here: removing V3 delay banner per schedule in [banner request](https://github.com/zowe/docs-site/issues/3465)
List the file(s) included in this PR: files.md

removing V3 banner; adding banner instructions

---

docs/user-guide/cli-configure-scs-on-headless-linux-os.md

Describe your pull request here: minor edit for post-merge feedback on [PR 3563](https://github.com/zowe/docs-site/pull/3563)
List the file(s) included in this PR: cli-configure-scs-on-headless-linux-os.md

minor edit

---

docs/user-guide/api-mediation/configuration-multi-tenancy-routing.md
sidebars.js

API Mediation Layer supports more complex setups for multi tenant environments. 
- user-guide/api-mediation/configuration-multi-tenancy-routing.md

Add details about multi tenant configuration

---

docs/user-guide/cli-using-integrating-apiml.md

Describe your pull request here: Link fixes in Integrating with API Mediation Layer
List the file(s) included in this PR: cli-using-integrating-apiml.md

Link fixes in Integrating with API Mediation Layer

---

docs/getting-started/zowe-certificates-overview.md
sidebars.js

Describe your pull request here: Fix formatting / language in Zowe Certificate overview
List the file(s) included in this PR: zowe-certificates-overview.md, sidebars.js

Zowe certificate overview refactor

---

docs/extend/extend-cli/cli-developing-a-plugin.md
versioned_docs/version-v2.10.x/extend/extend-cli/cli-developing-a-plugin.md
versioned_docs/version-v2.11.x/extend/extend-cli/cli-developing-a-plugin.md
versioned_docs/version-v2.12.x/extend/extend-cli/cli-developing-a-plugin.md
versioned_docs/version-v2.13.x/extend/extend-cli/cli-developing-a-plugin.md
versioned_docs/version-v2.14.x/extend/extend-cli/cli-developing-a-plugin.md
versioned_docs/version-v2.6.x/extend/extend-cli/cli-developing-a-plugin.md
versioned_docs/version-v2.7.x/extend/extend-cli/cli-developing-a-plugin.md
versioned_docs/version-v2.8.x/extend/extend-cli/cli-developing-a-plugin.md
versioned_docs/version-v2.9.x/extend/extend-cli/cli-developing-a-plugin.md

Describe your pull request here: Updating file name to address [Issue 3582](https://github.com/zowe/docs-site/issues/3582).
List the file(s) included in this PR: cli-developing-a-plugin.md

updating file name for cli plug-in doc

---

docs/getting-started/zowe-architecture.md
docs/getting-started/zowe-certificates-overview.md
docs/getting-started/zowe-high-availability.md
docs/user-guide/api-mediation/api-mediation-caching-service.md

Describe your pull request here: Fix broken links/language refactor
List the file(s) included in this PR: zowe-certificates-overview.md, zowe-high-availability.md, zowe-architecture.md, api-mediation-caching-service.md

Janan07 general doc image refactoring

---

docs/user-guide/cli-using-setting-environment-variables-in-automation-server.md
docs/user-guide/cli-using-using-environment-variables.md

Describe your pull request here: Updating environment variables doc in Using tab for Zowe V3.
List the file(s) included in this PR: cli-using-using-environment-variables.md +

env vars doc updates for Zowe V3

---

sidebars.js

Finish the restructuring of the existing Extend documentation. 
List the file(s) included in this PR: sidebar.js

Restructure extending the API Mediation Layer

---

docs/troubleshoot/app-framework/zss-error-codes.md

Describe your pull request here: Adds ZSS error messages containing actions
List the file(s) included in this PR: zss-error-codes.md

Add complete zss error messages

---

docs/extend/extend-apiml/api-medation-sso-integration-extenders.md

List the file(s) included in this PR: api-mediation-sso-integration-extenders

minor typos/formatting

---

docs/user-guide/cli-using-global-storing-properties-automatically.md
docs/user-guide/cli-using-integrating-apiml.md
docs/user-guide/cli-using-team-managing-credential-security.md
docs/user-guide/cli-using-understand-profiles-configs.md
docs/user-guide/cli-using-working-certificates.md
docs/user-guide/cli-using-writing-scripts.md
sidebars.js

Describe your pull request here: Updating Zowe CLI content for Zowe V3 in Using tab
List the file(s) included in this PR: file.md

updates to Using content for Zowe CLI V3

---

docs/user-guide/api-mediation/api-mediation-overview.md
sidebars.js

Describe your pull request here: Add API ML Overview to sidebar
List the file(s) included in this PR: sidebars.js, api-mediation-overview.md

Add API ML Overview to sidebar.js

---

tpsr/tpsr-v1.28.6.md
versioned_docs/version-v1.28.x/getting-started/release-notes/v1_28_6.md

Describe your pull request here: adding Zowe CLI release notes for Zowe v1.28.6
List the file(s) included in this PR: v1_28_6.md

Zowe CLI notes, TPSRs for Zowe v1.28.6

---

docs/user-guide/cli-cicsplugin.md
docs/user-guide/cli-db2-install-m1.md
docs/user-guide/cli-db2plugin.md
docs/user-guide/cli-extending.md
docs/user-guide/cli-ftpplugin.md
docs/user-guide/cli-installplugins.md
docs/user-guide/cli-mqplugin.md
docs/user-guide/cli-swreqplugins.md
docs/user-guide/cli-using-usingcli.md

Describe your pull request here: Updated Zowe CLI plug-in Use content for Zowe V3
List the file(s) included in this PR: cli-extending.md +

updating Zowe CLI plug-ins content is Use tab for V3

---

docs/user-guide/authentication-providers-for-apiml.md

Describe your pull request here: Add link to dummy provider in authentication-providers-for-apiml.md
List the file(s) included in this PR: authentication-providers-for-apiml.md

Add link to dummy auth provider article

---

docs/extend/extend-apiml/onboard-direct-eureka-call.md
docs/extend/extend-apiml/onboard-plain-java-enabler.md

Describe your pull request here: Change links to API ML security overview now in api-layer
List the file(s) included in this PR: onboard-plain-java-enabler.md

Change links to API ML security overview now in api-layer

---

docs/extend/extend-apiml/zowe-api-mediation-layer-security-overview.md
sidebars.js

Revert "Add API ML security overview to sidebar"

---

sidebars.js

Add Troubleshooting startup on zOS to the Sidebar.
Close #3621
List the file(s) included in this PR: sidebar.js

Add Troubleshoot zOS Startup to Sidebar

---

sidebars.js

Describe your pull request here: Improve visibility of v3 breaking changes by adding a vNext section to sidebars.js file
List the file(s) included in this PR: sidebars.js

Add vNext section

---

docs/troubleshoot/troubleshoot-zos-certificate.md

certs troubleshooting minor fix

---

docs/troubleshoot/troubleshoot-apiml-error-codes.md

Adds message into the log that states that the API Mediation Layer is up. 
List the file(s) included in this PR: troubleshoot-apiml-error-codes.md

Add new message that API Mediation Layer is up

---

sidebars.js

Clean the sidebar with respect to the extension of the API Mediation Layer to reflect the actual current reality. 
List the file(s) included in this PR: sidebar.js

Clean the sidebar to reflect reality

---

docs/user-guide/cli-using-using-team-profiles.md

Describe your pull request here: Addresses [Issue 3618](https://github.com/zowe/docs-site/issues/3618)
List the file(s) included in this PR: cli-using-using-team-profiles.md

updating doc for config file types

---

docs/troubleshoot/troubleshoot-zos-certificate.md

Describe your pull request here: Fix typos in troubleshoot zos certificate
List the file(s) included in this PR: troubleshoot-zos-certificate.md

Fix typos in troubleshoot zos certificate

---

docs/whats-new/release-notes/v2_16_0.md

Describe your pull request here: This PR adds API ML release notes for v2.16.0
List the file(s) included in this PR: v2_16_0.md

Add API ML release notes for v2.16.0

---

docs/whats-new/zowe-announcements.md

Describe your pull request here: Adding announcement re:  upcoming Zowe Quarterly Update webinar; editing existing announcements; addresses [Issue 3647](https://github.com/zowe/docs-site/issues/3647)
List the file(s) included in this PR: zowe-announcements.md

new Zowe announcement

---

docusaurus.config.js
sidebars.js

Describe your pull request here: bumping release versions for Zowe v2.16
List the file(s) included in this PR: tpsr-2.16.x.md

bumping release versions

---

docs/user-guide/cli-using-usingcli.md

Describe your pull request here: Addressing[ Issue 3640](https://github.com/zowe/docs-site/issues/3640) to update admonition re: accessibility in Zowe CLI
List the file(s) included in this PR: cli-using-usingcli.md

updating accessibility tip admonition

---

tpsr/tpsr-v2.16.x.md

Describe your pull request here: Adding Zowe v2.16 TPSRs
List the file(s) included in this PR: tpsr-v2.16.x.md

Zowe v2.16 TPSRs

---

docs/extend/extend-apiml/api-mediation-routing.md
docs/user-guide/api-mediation/api-mediation-multi-tenancy.md

- Provide correct URLs with service id in case of Routing
- Provide correct URL parameters for registry endpoint. 
api-mediation-routing.md, api-mediation-multi-tenancy.md

Fix issues find during the demo

---

docs/whats-new/zowe-announcements.md

Describe your pull request here: Removing Zowe Quarterly Update announcement per [Issue 3647](https://github.com/zowe/docs-site/issues/3647)
List the file(s) included in this PR: zowe-announcements.md

removing outdated announcement

---

docs/user-guide/configmgr-using.md

Fix typos found in the article
configmgr-using.md
Linked to https://github.com/zowe/docs-site/issues/3693 and https://github.com/zowe/docs-site/issues/3694

Fix minor typos

---

docs/user-guide/api-mediation/configuration-connection-limits.md

Typo: user-guide/apiml/configuration-connection-limits.md

---

tpsr/tpsr-v1.28.7.md
versioned_docs/version-v1.28.x/getting-started/release-notes/v1_28_7.md

Describe your pull request here: Adding TPSRs, removing unnecessary headers from release notes
List the file(s) included in this PR: v1_28_7.md

Anax v1.28.7 newtpsrs docs

---

.github/workflows/build-docs.yml

Fix the issue with last updated on the page. 
build-docs.yml

Build with git depth to get correct last updated

---

docs/troubleshoot/cli/known-cli.md

Describe your pull request here: Documenting known issue w/ `zowe zos-files search data-sets` command for Zowe V3 content
List the file(s) included in this PR: known-cli.md

documenting known CLI issue

---

docs/extend/extend-apiml/custom-metadata.md

Describe your pull request here: Link fixes
List the file(s) included in this PR: custom-metadata.md

Fix broken links in Custom Metadata

---

docs/user-guide/api-mediation/configuration-api-mediation-standalone.md
sidebars.js

Describe your pull request here: Add start API ML as a standalone to sidebar 
List the file(s) included in this PR: sidebars.js

Add start API ML as a standalone to sidebar

---

docs/extend/extend-apiml/api-medation-sso-integration-extenders.md
docs/extend/extend-apiml/api-mediation-layer-development-setup.md
docs/extend/extend-apiml/certificate-management-in-zowe-apiml.md

Describe your pull request here: This PR brings Certificate Managaement article to compliance with title standards
List the file(s) included in this PR: api-mediation-sso-integration-extenders.md, api-mediation-layer-development-setup.md, certificate-management-in-apiml.md

Fix title for cert mngmnt doc 

---

docs/user-guide/ze-install.md
docs/user-guide/ze-usage-tips.md
docs/user-guide/ze-usage.md
docs/user-guide/ze-working-with-commands.md
docs/user-guide/ze-working-with-data-sets.md
docs/user-guide/ze-working-with-jobs.md
docs/user-guide/ze-working-with-uss-files.md
sidebars.js

Describe your pull request here: Updating the Use section for Zowe Explorer for the Zowe v3 release
List the file(s) included in this PR: ze-install.md + more

Anax v3 use v3changes ze

---

docs/user-guide/api-mediation/configuration-client-certificates.md
docs/user-guide/api-mediation/configuration-connection-limits.md

Add new parameter to customize API ML websocket request buffer size

add request buffer size doc

---

docs/troubleshoot/app-framework/app-return-codes.md
docs/troubleshoot/app-framework/appserver-error-codes.md
docs/troubleshoot/app-framework/zis-error-codes.md

App server minor update

---

docs/user-guide/api-mediation/configuration-connection-limits.md

Update default value for websocket client connect timeout

chore: update defaults for connect timeout

---

docs/user-guide/api-mediation/authenticating-with-personal-access-token.md

correct status code for empty body

---

docs/user-guide/api-mediation/configuration-personal-access-token.md

Describe your pull request here: Fix typo in Enabling Personal Access Tokens
List the file(s) included in this PR: configuration-personal-access-tokens.md

Fix typo in Enabling Personal Access Tokens

---

docs/user-guide/api-mediation/configuration-gateway-timeouts.md

As follow-up to implementation of https://github.com/zowe/api-layer/issues/3471 document the newly added and accepted property. 
configuration-gateway-timeouts.md

Add request timeout for gateway property

---

docs/user-guide/api-mediation/configuration-extender-passtickets.md

Describe your pull request here: Fixes typos in enabling PassTickets
List the file(s) included in this PR: configuration-extender-passtickets.md

Fix typo in enabling PassTickets

---

docs/getting-started/install-ze-extensions.md
docs/getting-started/install-zowe-sdks.md
docs/user-guide/providing-feedback-and-contributing-client-side.md
docs/user-guide/sdks-using.md
docs/user-guide/ze-ftp-supported-functions.md
docs/user-guide/ze-ftp-using-ze-ftp-ext.md
docs/user-guide/ze-using-zowe-explorer-cics-ext.md
sidebars.js

- Updating the ZE FTP extension and Zowe SDKS Use content for Zowe V3. 
- Creating a new "Providing feedback and contributing" page to consolidate/house all provide-feedback information for client-side components.
List the file(s) included in this PR: sdks-using.md +

Anax v3 ftpuse v3changes ze

---

docs/getting-started/overview.md
docs/user-guide/sdks-using.md
docs/whats-new/release-notes/v2_16_0.md

Add documentation for the Java SDK. It is ready to be marked as GA status.
modified: docs/getting-started/overview.md
modified: docs/user-guide/sdks-using.md

Add Java SDK documentation 

---

docs/whats-new/release-notes/v2_17_0.md
docusaurus.config.js
sidebars.js

Describe your pull request here: Setting up release notes, tpsrs file, etc.
List the file(s) included in this PR: many.md

setting up release notes, tpsrs

---

tpsr/tpsr-v2.17.x.md

Describe your pull request here: Updating tpsrs for Zowe v2.17
List the file(s) included in this PR: tpsr-v2.17.x.md

Zowe 2.17 tpsrs

---

docs/extend/extend-cli/cli-authentication-mechanisms.md
docs/extend/extend-cli/cli-creating-plug-in-lifecycle-actions.md
docs/extend/extend-cli/cli-devTutorials.md
docs/extend/extend-cli/cli-developing-a-plugin.md
docs/extend/extend-cli/cli-extending-a-plugin.md
docs/extend/extend-cli/cli-implement-profiles.md
docs/extend/extend-cli/cli-installing-sample-plugin.md
docs/extend/extend-cli/cli-setting-up.md
docs/extend/extend-cli/cli-tutorials.md
docs/extend/extend-sdks.md
docs/extend/extend-zowe-overview.md
sidebars.js

Describe your pull request here: Updated content on extending Zowe CLI for Zowe V3 doc
List the file(s) included in this PR: extend-cli.md and more

first draft of Extending Zowe CLI for Zowe V3

---

docs/extend/extend-cli/cli-creating-plug-in-lifecycle-actions.md

Describe your pull request here: fixing typo
List the file(s) included in this PR: cli-creating-plug-in-lifecycle-actions.md

fixing typo

---

versioned_docs/version-v2.16.x/extend/extend-apiml/api-mediation-oidc-authentication.md

updates the oidc authentication doc with endpoint config details

Update api-mediation-oidc-authentication.md for endpoint configuration 

---

docs/appendix/zowe-glossary.md

Describe your pull request here: general language refactor of Zowe Glossary
List the file(s) included in this PR: zowe-glossary.md

general language refactor - glossary

---

docs/troubleshoot/cli/cli-issue.md
docs/troubleshoot/ze/known-ze.md
docs/troubleshoot/ze/troubleshoot-ze.md
docs/troubleshoot/ze/ze-issues.md
docs/troubleshoot/ze/ze-known-limits.md

Describe your pull request here: Updating troubleshooting ZE content for Zowe V3.
List the file(s) included in this PR: ze-issues.md +

Updating troubleshooting ZE content for Zowe V3 - first draft

---

docs/whats-new/release-notes/v2_18_0.md

Describe your pull request here: Add API ML release notes for 2.18
List the file(s) included in this PR: v2_18_0.md

API ML release notes 2.18

---

docs/whats-new/release-notes/v2_18_0.md

Describe your pull request here: Added release notes for ZSS in Zowe release version 2.18.0
List the file(s) included in this PR: v_2_18_0.md

Added release notes for ZSS in Zowe release version 2.18.0

---

docs/user-guide/api-mediation/configuration-extender-passtickets.md

Describe your pull request here: Fix formatting of codeblocks in PassTicket config
List the file(s) included in this PR: configuration-extender-passtickets.md

Fix formatting of codeblocks

---

docs/getting-started/zowe-security-authentication.md

zowe-security-authentication.md

Remove incorrect reference to CA

---

docs/getting-started/zowe-security-authentication.md

Describe your pull request here: Fix anchor link in Zowe security authentication
List the file(s) included in this PR: zowe-security-authentication.md

Fix anchor link

---

docs/extend/extend-apiml/custom-metadata.md
docs/extend/extend-apiml/onboard-direct-eureka-call.md

Describe your pull request here: Allow URL encoded characters
List the file(s) included in this PR: custom-metadata.md, onborad-direct-eureka-call.md

Allow url encoded chars by default - master

---

docs/troubleshoot/troubleshoot-apiml-error-codes.md

Update APIML error codes with ZWEAC105W

Update troubleshoot-apiml-error-codes.md with ZWEAC105W

---

docs/user-guide/address-storage-requirements.md

Describe your pull request here: Fix links in Address storage requirements.md
List the file(s) included in this PR: Address storage requirements.md

fix links in address storage requirements

---

docs/extend/extend-apiml/api-mediation-infinispan.md
docs/extend/extend-apiml/api-mediation-redis.md
docs/extend/extend-apiml/api-mediation-vsam.md

VSAM storage option is going to be deprecated in the v3. These changes are intended to provide a better user experience of the recommended solution.

update infinispan docs according to the current configuration

---

docs/user-guide/initialize-zos-system.md
versioned_docs/_version-v2.13.x/user-guide/initialize-zos-system.md
versioned_docs/_version-v2.14.x/user-guide/initialize-zos-system.md
versioned_docs/version-v2.15.x/user-guide/initialize-zos-system.md
versioned_docs/version-v2.16.x/user-guide/initialize-zos-system.md
versioned_docs/version-v2.17.x/user-guide/initialize-zos-system.md

Describe your pull request here: fix typo in zwe trace option
List the file(s) included in this PR: initialize-zos-system.md (and previous 2.x versions)

fix typo in zwe trace option

---

docs/user-guide/api-mediation/api-mediation-multi-tenancy.md
docs/user-guide/api-mediation/configuration-logging.md

replace cloud-gateway with gateway

---

.github/workflows/deploy-preview.yml
.github/workflows/pr-comment-trigger.yml
.github/workflows/pull-request-checker.yml

Update workflows to have additional required permissions.
List the file(s) included in this PR: blah.md
.github/workflows/deploy-preview.yml
.github/workflows/pr-comment-trigger.yml
.github/workflows/pull-request-checker.yml

Fix workflows on Master

---

.github/workflows/build-docs.yml
.github/workflows/deploy-preview.yml
.github/workflows/pr-comment-trigger.yml
.github/workflows/pull-request-checker.yml

Update workflows to have additional required permissions.
.github/workflows/build-docs.yml
.github/workflows/deploy-preview.yml
.github/workflows/pr-comment-trigger.yml
.github/workflows/pull-request-checker.yml

Update workflows to have more correct permissions

---

docs/user-guide/configuring-security.md
docs/user-guide/initialize-zos-system.md

Describe your pull request here: Address next steps during Zowe config
List the file(s) included in this PR: initialize-zos-system.md, configuring-security.md

Address next steps during Zowe config

---

docs/user-guide/mvd-configuration.md

added note to "[Defining the RACF ZOWE class](https://docs.zowe.org/stable/user-guide/mvd-configuration/#defining-the-racf-zowe-class)"
mvd-configuration.md

added note to Defining the RACF ZOWE class

---

docs/whats-new/zowe-v3-migration.md

This PR clarifies the action items for the prerequisite section of the v3 migration documentation

Prereq Updates for Migration doc

---

.github/workflows/link-checker.yml
.github/workflows/pr-comment-trigger.yml

* Fixes PR label checker wrongly detecting some labels as invalid (https://github.com/zowe/docs-site/pull/3922#issuecomment-2396269445)
* Fixes broken link checker failing when .md files include space in name
List the file(s) included in this PR: pr-comment-trigger.yml and misc .md

Fix PR label checker and broken link checker

---

sidebars.js

- Collapsing the V2 release notes ToC in the left-side sidebar
- Opening up the V3 release notes ToC in the left-side sidebar
List the file(s) included in this PR: sidebars.js

collapsing; opening release notes ToC

---

docs/user-guide/cli-configuringcli-ev.md

Describe your pull request here: Documenting the ZOWE_SHOW_SECURE_ARGS env variable to address [Issue 3862](https://github.com/zowe/docs-site/issues/3862).
List the file(s) included in this PR: cli-configuringcli-ev.md

adding new env variable

---

docs/extend/extend-apiml/api-mediation-infinispan.md
docs/user-guide/configure-sysplex.md
versioned_docs/version-v1.28.x/user-guide/configure-sysplex.md
versioned_docs/version-v2.18.x/extend/extend-apiml/api-mediation-infinispan.md

* fix notes for sysplex configuration
* update Infinispan config section in v2

Update documentation about  Infinispan config

---

docs/user-guide/authenticating-with-client-certificates.md

guide for the java sample client certificate authentication

---

docs/user-guide/address-authentication-requirements.md

Describe your pull request here: Fix SSO links
List the file(s) included in this PR: address-authentication-requirements.md

Fix SSO links

---

versioned_docs/version-v2.18.x/user-guide/api-mediation/wto-message-on-startup.md
versioned_sidebars/version-v2.18.x-sidebars.json

Copying the valid article also to 2.18 documentation 
wto-message-on-startup.md

Add WTO Message on startup configuration guide.

---

docs/getting-started/zowe-certificates-overview.md
docs/user-guide/advanced-apiml-configuration.md
docs/user-guide/configuring-at-tls-for-zowe-server.md
sidebars.js

Fix for sidebars for AT-TLS doc
- configuring-at-tls-for-zowe-server.md

Fix AT-TLS sidebars in docs-staging

---

docs/user-guide/sdks-using.md

Describe your pull request here: Address [Issue 3966](https://github.com/zowe/docs-site/issues/3966)
List the file(s) included in this PR: sdks-using.md

fixing header in SDK doc

---

docs/getting-started/user-roadmap-client-sdk.md
docs/user-guide/user-roadmap-zowe-cli.md

Describe your pull request here: Fixing links for issuing issues in CLI repo; addressing [Issue 3942](https://github.com/zowe/docs-site/issues/3942)
List the file(s) included in this PR: docs\user-guide\user-roadmap-zowe-cli.md, docs\getting-started\user-roadmap-client-sdk.md

updating links to CLI issue template

---

docs/user-guide/ze-usage-tips.md
docusaurus.config.js

Describe your pull request here: Documenting how to access resources w/ virtual workspaces in ZE; Minor update to docusaurus.config.js file to prevent local build errors
List the file(s) included in this PR: ze-usage-tips.md, docusaurus.config.js

Doc for virtual workspaces resources in ZE

---

docs/extend/extend-apiml/api-mediation-oidc-authentication.md
docs/extend/extend-apiml/zaas-client.md
docs/whats-new/zowe-v3-office-hours.md
versioned_docs/version-v2.18.x/extend/extend-apiml/api-mediation-oidc-authentication.md

Documentation for a new zaas client method for OIDC token validation.

validate OIDC token with zaas client

---

docs/extend/extend-apiml/custom-metadata.md
docs/user-guide/api-mediation/customizing-gateway-rate-limiter.md

Description of the configuring a rate limiter per particular service in custom-metadata.md. Also, an update of routes in the existing rate limiter documentation in customizing-gateway-rate-limiter.md.

rate limit per service

---

docs/user-guide/zos-components-installation-checklist.md

Describe your pull request here: Update installation checklist post security config reorg
List the file(s) included in this PR: z/OS components installation checklist

Update installation checklist post security config reorg

---

versioned_docs/version-v2.18.x/troubleshoot/troubleshoot-zos-certificate.md

Describe your pull request here: Address issue 4015 - troubleshooting tip for Zowe config
List the file(s) included in this PR: troubleshooting-zos-certificates.md in v2.18

Address issue 4015 - troubleshooting tip for Zowe cert config

---

docs/getting-started/ZE-system-reqs.md
docs/user-guide/ze-ftp-install-ze-ftp-ext.md

Describe your pull request here: Fixing broken links in ZE doc
List the file(s) included in this PR: docs\getting-started\ZE-system-reqs.md; docs\user-guide\ze-ftp-install-ze-ftp-ext.md

fixing broken links in ZE doc

---

docs/user-guide/api-mediation/configuration-multi-tenancy-routing.md

Describe your pull request here: fix intro to config routing in multi-tenant env
List the file(s) included in this PR: config routing in multi-tenant environment.md

fix intro to config routing in multi-tenant env

---

docs/troubleshoot/cli/troubleshoot-ibm-db2-database-plug-in.md
sidebars.js
versioned_docs/_version-v2.14.x/troubleshoot/cli/troubleshoot-ibm-db2-database-plug-in.md
versioned_docs/version-v2.15.x/troubleshoot/cli/troubleshoot-ibm-db2-database-plug-in.md
versioned_docs/version-v2.16.x/troubleshoot/cli/troubleshoot-ibm-db2-database-plug-in.md
versioned_docs/version-v2.17.x/troubleshoot/cli/troubleshoot-ibm-db2-database-plug-in.md
versioned_docs/version-v2.18.x/troubleshoot/cli/troubleshoot-ibm-db2-database-plug-in.md

Describe your pull request here: For Zowe V3 and V2 doc, adding a troubleshooting scenario for IBM Db2 Database Plug-in 
List the file(s) included in this PR: troubleshoot-ibm-db2-database-plug-in.md +

adding troubleshoot scenario

---

docs/troubleshoot/cli/troubleshoot-ibm-db2-database-plug-in.md
versioned_docs/version-v2.15.x/troubleshoot/cli/troubleshoot-ibm-db2-database-plug-in.md
versioned_docs/version-v2.16.x/troubleshoot/cli/troubleshoot-ibm-db2-database-plug-in.md
versioned_docs/version-v2.17.x/troubleshoot/cli/troubleshoot-ibm-db2-database-plug-in.md
versioned_docs/version-v2.18.x/troubleshoot/cli/troubleshoot-ibm-db2-database-plug-in.md

Describe your pull request here: Minor style edit to current and past versions of `troubleshoot-ibm-db2-database-plug-in.md` file
List the file(s) included in this PR: troubleshoot-ibm-db2-database-plug-in.md

minor edit to cli db2 doc

---

docs/whats-new/release-notes/v3_1_0.md
docusaurus.config.js
sidebars.js

Describe your pull request here: bumping release to 3.1
List the file(s) included in this PR: many.md

bumping to 3.1 release

---

docs/whats-new/release-notes/v3_1_0.md

Describe your pull request here: Adding Zowe CLI release notes for Zowe v3.1 release
List the file(s) included in this PR: docs\whats-new\release-notes\v3_1_0.md

adding CLI release notes

---

.github/workflows/report-least-recent-modified-files.yml

Updates one workflow's upload-artifact to v4. This is not doc-facing.
see: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/ 

Update Github upload action

---

docs/whats-new/release-notes/v3_1_0.md

Describe your pull request here: Add 2 more bug fixes for API ML
List the file(s) included in this PR: v3_1_0.md

Add 2 more bug fixes for API ML

---

docs/extend/extend-apiml/api-medation-sso-integration-extenders.md

Describe your pull request here: Fix headers/links/typos in api-mediation-sso-integration-extenders.md
List the file(s) included in this PR: api-mediation-sso-integration-extenders.md

Fix headers/links/typos in api-mediation-sso-integration-extenders.md

---

docs/user-guide/api-mediation/configuration-extender-passtickets.md
versioned_docs/version-v2.16.x/user-guide/api-mediation/configuration-extender-passtickets.md
versioned_docs/version-v2.17.x/user-guide/api-mediation/configuration-extender-passtickets.md
versioned_docs/version-v2.18.x/user-guide/api-mediation/configuration-extender-passtickets.md

Revert back note and command about the replay protection requirement

---

docs/extend/extend-apiml/api-medation-sso-integration-extenders.md
versioned_docs/version-v2.18.x/extend/extend-apiml/api-medation-sso-integration-extenders.md

Describe your pull request here: Fix links and methods for extenders to utilize SSO
List the file(s) included in this PR:  api-mediation-sso-integration-extenders.md

fix sso for extenders 

---

docs/user-guide/ze-managing-profiles.md
docs/user-guide/ze-usage-tips.md
sidebars.js

Describe your pull request here: Documenting how ZE project configurations work in VS Code multi-root workspaces. Addresses [Issue 3786](https://github.com/zowe/docs-site/issues/3786).
List the file(s) included in this PR: ze-managing-profiles.md

initial draft of multiroot workspace project configuration

---

docs/whats-new/release-notes/v3_1_0.md

Describe your pull request here: Update v3_1_0.md with API ML additions
List the file(s) included in this PR: v3_1_0.md 

Update v3_1_0.md with API ML additions

---

docs/user-guide/install-zowe-pswi.md

Upgrade needed z/OSMF version
install-zowe-pswi.md
Closing #4026

Update minimum z/OSMF version required

---

docs/user-guide/authentication-providers-for-apiml.md

Correct the property to reflect the actually used one
authentication-providers-for-apiml.md
Close #4095

Correct the property used

---

docs/user-guide/systemrequirements-zos.md

Change from milibits to MegaBytes
systemrequirements-zos.md

Change from milibits to MegaBytes

---

docs/whats-new/release-notes/v3_0_0.md
docs/whats-new/release-notes/v3_1_0.md

Describe your pull request here: Minor updates to Zowe v3.1 release notes
List the file(s) included in this PR: docs\whats-new\release-notes\v3_1_0.md

Minor edits to 3.1 release notes

---

docs/whats-new/release-notes/v3_0_0.md
tpsr/tpsr-v3.1.x.md

Describe your pull request here: Adding 3.1 tpsrs; fixing redirect links in 3.0 release notes
List the file(s) included in this PR: tpsr\tpsr-v3.1.x.mdtpsr\tpsr-v3.1.x.mdvtpsr\tpsr-v3.1.x.md

adding tprs; fixing redirect links in 3.0 RNs

---

sidebars.js

Describe your pull request here: Deleting a duplicate entry in the sidebar
List the file(s) included in this PR: mvd-server-config.md

deleting duplicate entry in sidebar

---

.github/ISSUE_TEMPLATE/---doc-site-banner-request.md
.github/ISSUE_TEMPLATE/troubleshooting-tip.md
docs/contribute/contributing.md

Describe your pull request here: updating the style guide; also updating repo GitHub issue templates
List the file(s) included in this PR: docs\contribute\contributing.md

changes to issue templates, zowe style guide

---

src/theme/DocVersionBanner/index.js

Describe your pull request here: Updating the alert message that displays in the static Zowe v1 documentation pages
List the file(s) included in this PR: blah.md

updating V1.28 alert message

---

docs/user-guide/cli-configuringcli-ev.md

Describe your pull request here: Documenting `zowe config list` in env variables doc.
List the file(s) included in this PR: docs\user-guide\cli-configuringcli-ev.md

adding note re: zowe config list command  to env variable

---

docs/user-guide/authenticating-with-client-certificates.md

Update documentation to run the client certificate sample application

Update client cert sample doc

---

docs/extend/extend-apiml/onboard-nodejs-enabler.md

onboard-nodejs-enabler.md]
Modify npm dependency cmd in onboard-nodejs-enabler.md
This is to fix the issue #4145

fix: Modify npm dependency cmd in onboard-nodejs-enabler.md

---

docs/user-guide/configure-zos-system.md
versioned_docs/version-v2.18.x/user-guide/configure-zos-system.md
versioned_docs/version-v3.0.x/user-guide/configure-zos-system.md

This PR removes one section that was duplicate in a couple of versions of doc as a result of a merge issue.
List the file(s) included in this PR: configure-zos-system.md in v3.1, v3.0, and v2.18

Remove duplicared article `Configure multi-user address space`

---

docs/extend/extend-apiml/api-medation-sso-integration-extenders.md
docs/extend/extend-apiml/authentication-for-apiml-services.md
docs/getting-started/zowe-security-authentication.md
docs/user-guide/api-mediation/api-mediation-jwt-token-refresh.md
docs/user-guide/api-mediation/configuration-extender-jwt.md
docs/user-guide/api-mediation/configuration-jwt.md
docs/user-guide/authenticating-with-jwt-token.md
versioned_docs/version-v2.18.x/extend/extend-apiml/api-medation-sso-integration-extenders.md
versioned_docs/version-v2.18.x/getting-started/zowe-security-authentication.md
versioned_docs/version-v2.18.x/user-guide/api-mediation/configuration-extender-jwt.md
versioned_docs/version-v2.18.x/user-guide/api-mediation/configuration-jwt.md
versioned_docs/version-v3.0.x/extend/extend-apiml/api-medation-sso-integration-extenders.md
versioned_docs/version-v3.0.x/getting-started/zowe-security-authentication.md
versioned_docs/version-v3.0.x/user-guide/api-mediation/configuration-extender-jwt.md
versioned_docs/version-v3.0.x/user-guide/api-mediation/configuration-jwt.md

Describe your pull request here: fix jwt refs in v3.1 v3.0 and v2.18
List the file(s) included in this PR: api-medation-sso-integration-extenders.md, zowe-security-authentication.md, configuration-extender-jwt.md, configuration-jwt.md in all three versions

fix jwt refs in v3.1 v3.0 and v2.18

---

versioned_sidebars/version-v2.18.x-sidebars.json

Describe your pull request here: remove configure-apiml-zosmf-workflow-2-18 from 2-18 sidebar
List the file(s) included in this PR: version-v2.18.x-sidebars.json.md

remove configure-apiml-zosmf-workflow-2-18 from 2-18 sidebar

---

docs/user-guide/cli-using-creating-profiles.md

Describe your pull request here: Addressing [Issue 3808](https://github.com/zowe/docs-site/issues/3808)
List the file(s) included in this PR: docs\user-guide\cli-using-creating-profiles.md

Updating doc for multiple api gateways

---

versioned_docs/version-v2.18.x/whats-new/release-notes/v2_18_0.md

Describe your pull request here: add additional bugfixes to API ML release notes v2.18
List the file(s) included in this PR: v2_18_0.md

add additional bugfixes to API ML release notes v2.18

---

docs/user-guide/api-mediation/configuration-jwt.md
versioned_docs/version-v2.18.x/user-guide/api-mediation/configuration-jwt.md
versioned_docs/version-v3.0.x/user-guide/api-mediation/configuration-jwt.md

Describe your pull request here: fix formatting for workaround in configuration-jwt
List the file(s) included in this PR: configuration-jwt

fix formatting for workaround in configuration-jwt

---

docs/user-guide/configuring-at-tls-for-zowe-server.md

Describe your pull request here: Address [issue #4208](https://github.com/zowe/docs-site/issues/4208)
List the file(s) included in this PR: configuring-at-tls-for-zowe-server.md

Fix AT-TLS rules example

---

docs/contribute/contributing.md
docs/user-guide/cli-install-verify-your-installation.md

- Fixing broken links to address [Issue 4159](https://github.com/zowe/docs-site/issues/4159). 
- Updating empty links in contributing.md so they're not flagged as broken links by the link checker.
List the file(s) included in this PR: docs\user-guide\cli-install-verify-your-installation.md

fixing broken links

---

docs/user-guide/api-mediation/using-multi-factor-authentication.md
versioned_docs/version-v2.18.x/user-guide/api-mediation/using-multi-factor-authentication.md
versioned_docs/version-v3.0.x/user-guide/api-mediation/using-multi-factor-authentication.md

Describe your pull request here: fix mfa link in using-multi-factor-authentication
List the file(s) included in this PR: using-multi-factor-authentication.md for v3.1, v3.0, and v2.18

fix link in using mfa

---

docs/user-guide/install-zowe-smpe-overview.md
docs/user-guide/install-zowe-smpe.md
versioned_docs/version-v3.0.x/user-guide/install-zowe-smpe-overview.md
versioned_docs/version-v3.0.x/user-guide/install-zowe-smpe.md

- Correct name of the packages to AZWE003
- Update sizes of the files
Closes https://github.com/zowe/docs-site/issues/4230 
install-zowe-smpe.md

Correct names and sizes for V3

---

docs/troubleshoot/app-framework/appserver-error-codes.md

I removed the following line from the description:
Review the configuration of components.app-server.node.port to see if it has a value and set one to fix the issue.
appserver-error-codes.md

Edited the description of ZWED0003E

---

docs/extend/extend-apiml/authentication-for-apiml-services.md

Add link to the ZAAS in the authentication documentation and clarify the documentation for SSO
Closes https://github.com/zowe/docs-site/issues/4187 
authentication-for-apiml-services.md

Add link to the ZAAS

---

docs/user-guide/install-zowe-zos-convenience-build.md
versioned_docs/version-v2.18.x/user-guide/install-zowe-zos-convenience-build.md
versioned_docs/version-v3.0.x/user-guide/install-zowe-zos-convenience-build.md

Describe your pull request here: address issue [4192](https://github.com/zowe/docs-site/issues/4192)
List the file(s) included in this PR: install-zowe-zos-convenience-build.md

address issue 4192

---

docs/extend/extend-apiml/api-mediation-vsam.md
versioned_docs/version-v3.0.x/extend/extend-apiml/api-mediation-vsam.md

Fix link to the Infinispan. 
Closes #4113 
api-mediation-vsam.md

Fix link in VSAM

---

docs/troubleshoot/troubleshoot-apiml.md
versioned_docs/version-v3.0.x/troubleshoot/troubleshoot-apiml.md

Add details about how to restart services. 
Closes #4093 
troubleshoot-apiml.md

Add notes on how to restart service

---

docs/whats-new/release-notes/v2_18_1.md
sidebars.js
tpsr/tpsr-v2.18.1
versioned_docs/version-v2.18.x/whats-new/release-notes/v2_18_1.md
versioned_sidebars/version-v2.18.x-sidebars.json

anaxceron <ana.ceron@broadcom.com>
Describe your pull request here: Adding release notes for Zowe 2.18.1
List the file(s) included in this PR: docs\whats-new\release-notes\v2_18_1.md +

adding back release notes for 2.18.1

---

docs/extend/extend-cli/cli-setting-up.md
docs/extend/extend-desktop/mvd-uribroker.md
docs/whats-new/zowe-v3-conformance-criteria.md

Box links are being broken. Use the ones owned by LF. 
zowe-v3-conformance-criteria.md

Use Google Drive links for conformance

---

docs/whats-new/release-notes/v2_18_2.md
sidebars.js
tpsr/tpsr-v2.18.2.md
versioned_docs/version-v2.18.x/whats-new/release-notes/v2_18_2.md
versioned_sidebars/version-v2.18.x-sidebars.json

Describe your pull request here: adding Zowe v 2.18.2 doc to docs-staging
List the file(s) included in this PR: versioned_docs\version-v2.18.x\whats-new\release-notes\v2_18_2.md

release notes, tpsrs

---

versioned_docs/_version-v2.13.x/troubleshoot/troubleshoot-zowe-release.md
versioned_docs/_version-v2.14.x/troubleshoot/troubleshoot-zowe-release.md
versioned_docs/version-v2.15.x/troubleshoot/troubleshoot-zowe-release.md
versioned_docs/version-v2.16.x/troubleshoot/troubleshoot-zowe-release.md
versioned_docs/version-v2.17.x/troubleshoot/troubleshoot-zowe-release.md
versioned_docs/version-v2.18.x/troubleshoot/troubleshoot-zowe-release.md
versioned_docs/version-v3.0.x/troubleshoot/troubleshoot-zowe-release.md

In the Zowe releases section, a word change is done. 
List the file(s) included in this PR: troubleshoot-zowe-release.md (The affected file appears to be the same file, but it is across different versions.)

April_2_Troubleshoot_UnderstZoweRelVersWordChange

---

docs/troubleshoot/launcher/launcher-error-codes.md

Typo.
docs/troubleshoot/launcher/launcher-error-codes.md

Typo: update launcher-error-codes.md

---

docs/whats-new/release-notes/v3_1_1.md
sidebars.js
tpsr/tpsr-v3.1.1.md

Describe your pull request here: publishing Zowe v3.1.1 doc to the live site
List the file(s) included in this PR: docs\whats-new\release-notes\v3_1_1.md +

Anax v3.1.1 r ns tpsrs docs

---

docs/whats-new/zowe-v3-migration.md

Incorrect pre-req in V3 migration. 
zowe-v3-migration.md

Remove JWT as requirement for z/OSMF

---

docs/troubleshoot/ze/troubleshoot-ze.md

Closing #4286 
troubleshoot-ze.md

Add .md to the correct link

---

versioned_sidebars/version-v2.18.x-sidebars.json

Describe your pull request here: Add zosmf apiml workflows to sidebar for 2.18
List the file(s) included in this PR: version-v2.18.x-sidebars.json

Add zosmf apiml workflows to sidebar for 2.18

---

docs/whats-new/release-notes/v3_1_0.md

Some links point to wrong issue/PR.
docs/whats-new/release-notes/v3_1_0.md

Update What's new 3.1.0

---

dco_signoffs/Aroosh-Lele-docs-site.txt

The objective is to see whether I can avoid clicking the Set DCO to pass button.

To resolve the issue of manual DCO-Sign-Off

---

versioned_docs/version-v2.18.x/whats-new/release-notes/v2_18_1.md

Describe your pull request here: readd apiml new features and bug fixes for 2.18.1
List the file(s) included in this PR: v2_18_1.md

readd apiml new features and bug fixes for 2.18.1

---

docs/user-guide/configure-zos-system.md
versioned_docs/version-v2.18.x/user-guide/configure-zos-system.md
versioned_docs/version-v3.0.x/user-guide/configure-zos-system.md

Describe your pull request here: Propagate improvements from v2.18 into v3.0 and v3.1
List the file(s) included in this PR: configure-zos-system

Propagate improvements from v2.18 into v3.0 and v3.1

---

docs/appendix/server-datasets.md

Address the #4229, changing the sizes and adding missing members.
docs/appendix/server-datasets.md

Server datasets - sizes and missing members

---

docs/whats-new/release-notes/v3_2_0.md
docusaurus.config.js
sidebars.js

Describe your pull request here: Adding placeholder files for v3.2 release notes, TPSRs
List the file(s) included in this PR: tpsr\tpsr-v3.2.x.md +

adding placeholders for v3.2 doc

---

docs/user-guide/configure-caching-service-ha.md
docs/whats-new/zowe-announcements.md
versioned_docs/version-v2.15.x/user-guide/cli-configuringcli-ev.md
versioned_docs/version-v2.16.x/user-guide/cli-configuringcli-ev.md
versioned_docs/version-v2.17.x/user-guide/cli-configuringcli-ev.md
versioned_docs/version-v2.18.x/user-guide/cli-configuringcli-ev.md
versioned_docs/version-v2.18.x/user-guide/configure-caching-service-ha.md
versioned_docs/version-v3.0.x/user-guide/configure-caching-service-ha.md

Describe your pull request here: Addressing [Issue 4321](https://github.com/zowe/docs-site/issues/4321) + fixing syntax errors
List the file(s) included in this PR: zowe-announcements.md

Minor edit to Announcements page; fixing syntax

---

docs/extend/extend-desktop/mvd-mvdandwindowmgt.md

Typo: missing char.
docs/extend/extend-desktop/mvd-mvdandwindowmgt.md

Typo: mvd-mvdandwindowmgt.md

---

docs/extend/extend-apiml/libraries-for-onboarding-apis.md
docs/extend/extend-apiml/onboard-micronaut-enabler.md
docs/extend/extend-apiml/onboard-nodejs-enabler.md
docs/extend/extend-apiml/onboard-overview.md
docs/extend/extend-apiml/onboard-plain-java-enabler-external-configuration.md
docs/extend/extend-apiml/onboard-plain-java-enabler.md
docs/extend/extend-apiml/onboard-spring-boot-enabler.md
docs/extend/extend-apiml/onboard-static-definition.md
docs/extend/extend-apiml/optional-features-to-use-with-onboarded-apis.md
docs/extend/extend-apiml/zowe-api-mediation-layer-security-overview.md
sidebars.js

Describe your pull request here: Add roles and improve style consistency  between onboarding guides
List the file(s) included in this PR: libraries-for-onboarding-apis.md, onboard-micronaut-enabler.md, onboard-node.js-enabler.md, onboard-plain-java-enabler-external-configuration.md, onboard-spring-boot-enabler.md, onboard-statis-definition.md, sidebar.js

Add roles and improve style consistency  between onboarding guides

---

docs/user-guide/systemrequirements-zos.md

Describe your pull request here: Clarify node.js requirement
Addresses [Doc enhancement request for docs.zowe.org/stable/user-guide/systemrequirements-zos/ #4320](https://github.com/zowe/docs-site/issues/4320)
List the file(s) included in this PR: systemrequirements-zos.md

Clarify node.js requirement

---

docs/troubleshoot/app-framework/app-troubleshoot.md
docs/user-guide/authentication-providers-for-apiml.md
docs/user-guide/mvd-using.md

Describe your pull request here: Add notes and troubleshooting topic for required z/OSMF for some plug-ins
List the file(s) included in this PR: troubleshoot/app-framework/app-troubleshoot.md, authentication-providers-for-apiml.md,
mvd-using.md

add notes and troubleshooting topic

---

docs/user-guide/start-zowe-zos.md

Fixes https://github.com/zowe/docs-site/issues/3534 and https://github.com/zowe/docs-site/issues/4383
List components eligible for start and stop.
The note at the end was kept, it is still valid.
docs/user-guide/start-zowe-zos.md

`start-zowe-zos.md`: list components eligible for start and stop

---

tpsr/tpsr-v3.2.x.md

Describe your pull request here: Adding TPSRs for Zowe v3.2
List the file(s) included in this PR: tpsr\tpsr-v3.2.x.md

adding V3.2 tpsrs

---

docs/user-guide/ze-install-configuring-ze.md

- Provides steps on how to change number of DS/PDS members per page
- Note on how to disable pagination
- Removes outdated section on changing the temporary file path (no longer exists in ZE v3)
- `docs/user-guide/ze-install-configuring-ze.md`

Update "Configuring Zowe Explorer"

---

docs/extend/extend-apiml/libraries-for-onboarding-apis.md

Describe your pull request here: add Python enabler to overview enabler topic
List the file(s) included in this PR: libraries-for-onboarding-apis

add Python enabler to overview enabler topic

---

docs/user-guide/ze-install-configuring-ze.md

Adds documentation detailing the Zowe Explorer for VSCode REST timeout settings. This setting will be available in Zowe 3.3.
docs/user-guide/ze-install-configuring-ze.md

Add REST timeout settings for Zowe Explorer

---

docs/whats-new/release-notes/v3_2_0.md

Removed a duplicate bullet from the Zowe Application Framework section.
v3_2_0.md

Updated v3_2_0.md file

---

docs/user-guide/start-zowe-zos.md

Fixes #4090.
docs/user-guide/start-zowe-zos.md

Small start update

---

docs/user-guide/mvd-using.md

Fixes https://github.com/zowe/docs-site/issues/4370
docs/user-guide/mvd-using.md

Update links in mvd-using.md

---

docs/whats-new/release-notes/v2_18_2.md

Describe your pull request here: Add API ML release notes for 2.18.2
List the file(s) included in this PR: v2_18_2.md

Add API ML release notes for 2.18.2

---

docs/user-guide/configure-certificates.md
versioned_docs/_version-v2.13.x/user-guide/configure-certificates.md
versioned_docs/_version-v2.14.x/user-guide/configure-certificates.md
versioned_docs/version-v2.15.x/user-guide/configure-certificates.md
versioned_docs/version-v2.16.x/user-guide/configure-certificates.md
versioned_docs/version-v2.17.x/user-guide/configure-certificates.md
versioned_docs/version-v2.18.x/user-guide/configure-certificates.md
versioned_docs/version-v3.0.x/user-guide/configure-certificates.md
versioned_docs/version-v3.1.x/user-guide/configure-certificates.md

This PR is based on issue #https://github.com/zowe/api-layer/issues/4109
The new paragraph is valid for all version of the APIML.
List the file(s) included in this PR: configure-certificates.md in multiple versions

Add information about certificate requirements to support JWT generation

---

versioned_docs/version-v2.18.x/whats-new/release-notes/v2_18_2.md

Describe your pull request here: Add API ML release notes for v2.18.2 to versioned doc v2.18.x
List the file(s) included in this PR: v2.18.x/whats-new/release-notes/v2_18_2

Add API ML release notes for v2.18.2 to versioned doc v2.18.x

---

docs/user-guide/address-storage-requirements.md

Documentation about memory assumption and limitation

---

docs/whats-new/upgrade-from-convenience-build-to-pswi-smpe.md
sidebars.js

Describe your pull request here: recreate upgrade from convenience to pswi or smpe
List the file(s) included in this PR: upgrade-from-convenience-to-pswi-smpe.md, sidebars.js

recreate upgrade from convenience to pswi or smpe

---

docs/troubleshoot/app-framework/app-troubleshoot.md

* Examples of ZIS status message are wrong
* `Instance.env` replaced by `zowe.yaml`
docs/troubleshoot/app-framework/app-troubleshoot.md

`app-troubleshoot`: configuration in yaml

---

docs/user-guide/configuring-at-tls-for-zowe-server.md

Fixing port range for AT-TLS
configuring-at-tls-for-zowe-server.md

Fix the ports in the client part of AT-TLS

---

src/theme/DocVersionBanner/index.js

Describe your pull request here: Fixing link syntax in version banner message
List the file(s) included in this PR: index.md

fixing link syntax in version banner message

---

docs/troubleshoot/launcher/launcher-troubleshoot.md

Minor changes, example with couple more lines, tip how to comment the line.
docs/troubleshoot/launcher/launcher-troubleshoot.md

Launcher troubleshoot - minor changes

---

docs/user-guide/authenticating-with-jwt-token.md

The actual URLs needs to contain the serviceId in this case gateway to work properly. 
authenticating-with-jwt-token.md

Fix the URLs in the documentation 

---

versioned_docs/version-v2.18.x/appendix/zowe-yaml-configuration.md

Update reference for apiml.security.forwardHeader.trustedProxies in multitenancy configuration
List the file(s) included in this PR: 
zowe-yaml-configuration.md

Update reference for apiml.security.forwardHeader.trustedProxies in multitenancy configuration

---

docs/user-guide/configure-zos-system.md
versioned_docs/version-v2.18.x/user-guide/configure-zos-system.md
versioned_docs/version-v3.0.x/user-guide/configure-zos-system.md
versioned_docs/version-v3.1.x/user-guide/configure-zos-system.md

Describe your pull request here: fix error Re: ZWESIUSR which is not a group command
List the file(s) included in this PR: configure-zos-system.md for v2.18, 3.0, 3.1 and current master versions

fix error Re: ZWESIUSR which is not a group command

---

versioned_sidebars/version-v2.18.x-sidebars.json

Describe your pull request here: Deleting duplicate reference of an article in the sidebar for Zowe Docs v2.18.x
List the file(s) included in this PR: one.md

sidebar fix

---

docs/whats-new/release-notes/v2_18_2.md

Describe your pull request here: remove apiml release notes for 2.18.2
List the file(s) included in this PR: whats-new/release-notes/v2_18_2.md

remove apiml release notes for 2.18.2

---

docs/whats-new/release-notes/v2_18_2.md

Updates Zowe 2.18.2 release notes for APIML
- docs/whats-new/release-notes/v2_18_2.md

Updates Zowe 2.18.2 release notes for APIML

---

docs/appendix/zowe-yaml-configuration.md

Describe your pull request here: remove apiml.security.forwardHeader.trustedProxies in v3.2
List the file(s) included in this PR: zowe-yaml-configuration.md

remove apiml.security.forwardHeader.trustedProxies in v3.2

---

versioned_docs/version-v2.18.x/whats-new/release-notes/v2_18_2.md

Updated the release notes for 2.18.2 to say July 2025 release

update 2.18.2 release notes to july

---

docs/extend/extend-cli/cli-authentication-mechanisms.md
docs/user-guide/cli-authentication-methods.md
docs/user-guide/ze-authentication-methods.md

Describe your pull request here: Documenting new client config property `authOrder`
List the file(s) included in this PR: docs\user-guide\ze-authentication-methods.md +

authOrder property doc - first draft

---

docs/whats-new/release-notes/v2_18_2.md

List the file(s) included in this PR: v2_18_2.md
Updated the Release notes for Zowe version 2.18.2.

Updated v2_18_2.md

---

docs/user-guide/cli-using-creating-profiles.md

Describe your pull request here: Updating basePath names to address [Issue 4637](https://github.com/zowe/docs-site/issues/4637)
List the file(s) included in this PR: docs\user-guide\cli-using-creating-profiles.md

correcting basePath names

---

docs/user-guide/ze-table-view-guide.md
sidebars.js

Describe your pull request here: Documenting the ZE table view functionality for data sets
List the file(s) included in this PR: docs\user-guide\ze-table-view-guide.md

Documenting the ZE table view

---

docs/troubleshoot/ze/troubleshoot-ze.md
docs/user-guide/ze-data-set-table-view-guide.md
docs/user-guide/ze-jobs-table-view-guide.md
sidebars.js

- Documenting the jobs table view
- Editing data set table view doc for style consistency
- Moved troubleshooting content to troubleshooting section
List the file(s) included in this PR: docs\user-guide\ze-jobs-table-view-guide.md

jobs table view doc

---

docs/appendix/server-datasets.md

Describe your pull request here: add ZWERMVS, ZWERMVS1, and ZWERMVS2 to docs-staging
List the file(s) included in this PR: server-datasets.md

add ZWERMVS, ZWERMVS1, and ZWERMVS2

---

docs/whats-new/release-notes/v3_3_0.md
docusaurus.config.js
sidebars.js

Describe your pull request here: Bumping version to v.3; adding placeholders for release notes, TPSRs
List the file(s) included in this PR: many.md

bumping version, adding release notes, tpsr placeholders

---

versioned_docs/version-v3.0.x/whats-new/upgrade-from-convenience-build-to-pswi-smpe.md
versioned_docs/version-v3.1.x/whats-new/upgrade-from-convenience-build-to-pswi-smpe.md
versioned_sidebars/version-v3.0.x-sidebars.json
versioned_sidebars/version-v3.1.x-sidebars.json

Describe your pull request here: Address issue 4652 - 2nd PR
List the file(s) included in this PR: version-v3.0.x-sidebars and version-v3.1.x-sidebars

Address issue 4652 - 2nd PR

---

docs/whats-new/release-notes/v3_3_0.md

Describe your pull request here: minor punctuation fix
List the file(s) included in this PR: v3_3_0.md

minor punctuation fix

---

docs/getting-started/cli-getting-started.md
docs/whats-new/release-notes/release-notes-overview.md
sidebars.js

Describe your pull request here: Removing CLI quick start content; minor edits to Release notes overview page
List the file(s) included in this PR: docs\getting-started\cli-getting-started.md +

Anax v3.3 removequickstart cli

---

docs/user-guide/api-mediation/api-mediation-modulith.md

Describe your pull request here: fix grammar and note formatting
List the file(s) included in this PR: api-mediation-modulith.md

fix grammar and note formatting
