docs/guides/ReactJSUI.md
docs/guides/libertyAPI.md

Misc spellings and update links

---

docs/.vuepress/config.js

typos fix config file

---

docs/user-guide/introduction.md

Added a list of the APIML TPSRs that are required for the component to the introduction article..

APIML TPSRs (list)

---

docs/user-guide/introduction.md
docs/user-guide/mvd-desktopandwindowmgt.md
docs/user-guide/mvd-plugincreateappplugin.md
docs/user-guide/mvd-zluxplugindefandstruct.md
docs/user-guide/usingmvd.md

Some peer edits
I think that the topic mvd-mvdandwindowmgt.md can be deleted as I don't see it being used in the ditamap.

Some peer edits

---

docs/user-guide/mvd-zluxconfiguration.md
docs/user-guide/uninstall.md

Add clarification to logging section and uninstall

Add clarification to logging section and uninstall

---

docs/google24787859230c742d.html

Upload a verification file to use google webmaster to tell Google about this new website and to speed up the indexing process.

Upload a verification file to use google webmaster 

---

docs/user-guide/api-mediation/api-mediation-onboard-an-existing-java-rest-api-service.md

Update instruction for usage of plain Java enabler.

Update configuration for plain java enabler

---

docs/user-guide/overview.md
docs/user-guide/usingapis.md

Signed-off-by: jordan cain <jordan.cain1@uk.ibm.com>

remove persistent data store and cpu usage api documentation

---

docs/user-guide/api-mediation/api-mediation-onboard-an-existing-java-rest-api-service.md

Plain java change configuration

change configuration for plain java enabler

---

docs/.vuepress/config.js
yarn.lock

When the build fails, it says what is wrong with the table of contents. Apparently that was the only issue.

Fixed build errors by fixing toc

---

docs/user-guide/cli-cicsplugin.md

correct typo

---

docs/.vuepress/config.js
docs/user-guide/cli-installplugins.md

Docs staging

---

docs/.vuepress/config.js

Declutter API onboarding TOC

---

docs/guides/cli-devTutorials.md

Cli dev staging

---

docs/user-guide/api-mediation/api-mediation-onboard-an-existing-rest-api-service-without-code-changes.md
docs/user-guide/api-mediation/api-mediation-onboard-overview.md
docs/user-guide/api-mediation/api-mediation-overview.md
docs/user-guide/api-mediation/diagrams/rest-api-components-sample.plantuml
docs/user-guide/api-mediation/diagrams/rest-api-components-sample.svg

Provides restructured guide for static onboarding.

Split the API overview to new topic and describe steps for identification

---

docs/guides/api-mediation-onboard-an-existing-rest-api-service-without-code-changes.md

One more grammar fix in line 286.

Fix grammar in line 286.

---

docs/user-guide/cli-installcli.md

revert anchor test

---

docs/user-guide/install-zos.md
docs/user-guide/troubleshootinstall.md
docs/user-guide/usingapis.md

Name changes for Atlas API before API Mediation

---

docs/user-guide/troubleshootinstall.md

Changed the CSRF section

---

docs/user-guide/cli-cicsplugin.md

fix prereqs

---

docs/guides/api-mediation-onboard-a-sprint-boot-rest-api-service.md

Refactor article title

---

docs/guides/api-mediation-onboard-an-existing-java-jersey-rest-api-service.md

Changes to Externalize Parameters to clarify file location.

Refactor Externalize Parameters

---

docs/user-guide/troubleshootinstall.md

Part of the script is not correctly displayed. Fix it by wrapping the scripts in codeblock.

Fix a display issue

---

docs/user-guide/cli-cicsplugin.md
docs/user-guide/cli-installcli.md

Updated details of CLI install from package and CICS plug-in install from package.

Cics package

---

docs/README.md
docs/user-guide/install-zos.md
docs/user-guide/summaryofchanges.md
docs/user-guide/systemrequirements.md

docs-staging contain changes for 0.9.2

Merge docs-staging branch to master

---

docs/user-guide/cli-installcli.md

fix formatting

---

docs/user-guide/cli-db2plugin.md

Signed-off by: Mark Ackert <Mark.Ackert@ca.com>

Review DB2 Plugin Install

---

docs/user-guide/cli-db2plugin.md

Signed-off by: Mark Ackert <Mark.Ackert@ca.com>

Small wording changes

---

docs/user-guide/summaryofchanges.md

Changed heading to reflect Nov in the Rel Notes
Signed-off-by: bauja03 <bauja03@ca.com>

change 093 rel date from oct 2018 to nov 2018

---

docs/user-guide/mvd-configuration.md
docs/user-guide/summaryofchanges.md

Fixes for #214

---

docs/user-guide/installandconfig.md
docs/user-guide/mvd-appfilesystem.md
docs/user-guide/mvd-apptoappcommunication.md
docs/user-guide/mvd-configdataservice.md
docs/user-guide/mvd-dataservices.md
docs/user-guide/mvd-desktopandwindowmgt.md
docs/user-guide/mvd-extendingzlux.md
docs/user-guide/mvd-logutility.md
docs/user-guide/mvd-plugindefandstruct.md
docs/user-guide/mvd-uribroker.md
docs/user-guide/overview.md
docs/user-guide/summaryofchanges.md

More clean-up for issue 214; fixed issue 187

More clean-up for issue 214; fixed issue 187

---

docs/user-guide/install-zos.md
docs/user-guide/mvd-using.md

Fixed URL link in installzos and mvd-using topics

Fixed URL link

---

docs/.vuepress/config.js
docs/extend/extend-apiml/api-mediation-security.md
docs/extend/extend-cli/cli-developing-a-plugin.md
docs/extend/extend-cli/cli-extending-a-plugin.md
docs/extend/extend-cli/cli-installing-sample-plugin.md
docs/extend/extend-desktop/mvd-errorreportingui.md
docs/getting-started/zowe-architecture.md

These were the last to get the build to work properly.

finishing link issues

---

docs/guides/api-mediation-onboard-an-existing-rest-api-service-without-code-changes.md
docs/user-guide/install-zos.md

Janan07 install zos

---

.github/ISSUE_TEMPLATE/---doc-error-report.md
.github/ISSUE_TEMPLATE/---doc-site-enhancement-request.md

Update issue templates

---

docs/.vuepress/config.js
docs/extend/extend-api/existingAPI.md
docs/extend/extend-api/existingApp.md
docs/extend/extender-architecture.md

Ashley. I thought I would create a pull request to what was the docs-new branch first of all. I can merge with master if and when you are happy with the changes here. I am excluding the two files from the config.js because they are not yet complete

docs-new-colin: deployment references

---

docs/.vuepress/theme/NavLink.vue
docs/.vuepress/theme/NavLinks.vue

issue #268 add text back for top-left corner menu dropdown

---

docs/user-guide/zosmf-lite.md

Update links to CA security product, update results verification for IZUMKFS, update common messages etc....

Update code drop 3

---

docs/extend/extend-desktop/iframe-sample.md
docs/extend/extend-desktop/mvd-desktopandwindowmgt.md
docs/extend/extend-desktop/mvd-mvdandwindowmgt.md
docs/extend/extend-desktop/mvd-plugindefandstruct.md
docs/extend/extend-desktop/mvd-uribroker.md
docs/extend/extend-desktop/ui-intro.md
docs/extend/extend-desktop/zlux-workshop-user-browser.md

I updated old references of RocketMVD to ZoweZLUX in the extending section and fixed some wording.

updated old references of RocketMVD

---

docs/extend/extend-desktop/angular-sample.md
docs/extend/extend-desktop/iframe-sample.md
docs/extend/extend-desktop/mvd-apptoappcommunication.md
docs/extend/extend-desktop/mvd-configdataservice.md
docs/extend/extend-desktop/mvd-dataservices.md
docs/extend/extend-desktop/mvd-logutility.md
docs/extend/extend-desktop/mvd-plugindefandstruct.md
docs/extend/extend-desktop/mvd-uribroker.md
docs/extend/extend-desktop/react-sample.md
docs/extend/extend-desktop/ui-intro.md
docs/extend/extend-desktop/zlux-example-server.md
docs/extend/extend-desktop/zlux-tutorials.md
docs/extend/extend-desktop/zlux-workshop-starter-app.md

Doc-site name clarifications for issue 214

Doc-site names for issue 214

---

docs/extend/extend-apiml/api-mediation-security.md

Signed-off-by: Petr Plavjanik <petr.plavjanik@broadcom.com>
Resolves https://github.com/zowe/zowe-install-packaging/issues/231

Security commands to read z/OSMF keyring

---

docs/.vuepress/config.js
docs/extend/extend-apiml/api-mediation-security.md

- added a topic to the TOC
- removed extra idents that cause the code to display in white on doc site

Add a missing topic to TOC

---

Jenkinsfile

use new agent label

---

Jenkinsfile
docs/.pdf/build.sh

fix an issue on archiving; clean pdf tmp folder

---

docs/user-guide/install-zos.md

stop start updated

---

docs/user-guide/install-zos.md

Added ICSF changes

---

docs/user-guide/install-zos.md

Signed-off-by: Nayer Najafi <nayer.najafi@ibm.com>

Fix Command

---

docs/user-guide/install-zos.md

Signed-off-by: MarkAckert <Mark.Ackert@ca.com>
TODO: Review command conversions with experts; review CSF security commands in particular.
TODO: Review document flow with doc squad

WIP - draft of tss/acf2 commands for ZSS

---

docs/extend/extend-apiml/api-mediation-onboard-a-sprint-boot-rest-api-service.md

Improve/fix spring onboarding guidelines.

Fix springv1 guidelines

---

docs/README.md

proper link to latest pdf

---

docs/user-guide/install-zos.md

Signed-off-by: MarkAckert <Mark.Ackert@ca.com>

minor fixes to zss security

---

docs/.vuepress/versions.json

show version dropdown for 0.9.x doc

---

docs/.pdf/Zowe_Documentation.ditamap.template

Fixed typo in PDF title

---

docs/user-guide/install-zos.md

Update how to view the ZWES.IS users

---

docs/user-guide/systemrequirements.md

do some fixes to change size of the file

---

docs/user-guide/install-zos.md

Update for the Manual installation of the cross memory server to include the RACF BPX.SERVER and BPX.DAEMON FACILITY classes

Zwes.is doc updates

---

docs/user-guide/cli-installcli.md

- updated the name of the CLI install package.
- generic ref so that we dont have to update it every refresh
Close issue #410

updated the name of the CLI install package

---

docs/getting-started/summaryofchanges.md

added item to summary of changes to zowe CLI for the CICS plug-in

added item to summary of changes to zowe CLI for the CICS plug-in

---

docs/.vuepress/config.js

issue #405 add nps survey code

---

docs/user-guide/cli-usingcli.md

Remove dup content in cli-usingcli > Create a profile to access an API Mediation Layer.
TO address issue #423

issue #423

---

docs/user-guide/cli-installplugins.md

Fixed typos...
example syntax was missing 's'

to address CLI plug-in command error #427

---

docs/troubleshoot/troubleshoot-cli.md

Based on feedback from engineers, added a note to verify that Node JS is on your PATH (in addition to just making sure that npm/node are installed).

Add info to CLI troubleshooting

---

docs/user-guide/systemrequirements.md

Fix for https://github.com/zowe/docs-site/issues/435

Remove z/OS PT from system requiements

---

docs/troubleshoot/troubleshoot-app-framework.md

Troubleshoot Zowe Application Server

---

docs/user-guide/install-zos.md

Fix for https://github.com/zowe/docs-site/issues/442

ZOWE_EXPLORER_HOST and hostname -c problem documented

---

docs/troubleshoot/troubleshoot-app-framework.md

Added note for ZWES.IS

---

docs/getting-started/summaryofchanges.md

This include most/all new features from 2.8.0 up to 2.15.1

Add Zowe CLI enhancements since Zowe 1.0.1

---

docs/.vuepress/config.js
docs/user-guide/cli-installcli.md
docs/user-guide/cli-updatingcli.md

- added (new) article: Updating CLI
- added updating CLI to the config.js file
- fixed inline links in cli-installcli.md
@BrandonJenkins14; Please review the syntax in the new article

Merge updating cli

---

docs/extend/extend-apiml/api-mediation-onboard-a-spring-boot-rest-api-service.md
docs/extend/extend-apiml/api-mediation-onboard-an-existing-java-jersey-rest-api-service.md
docs/extend/extend-apiml/api-mediation-onboard-an-existing-java-rest-api-service-without-spring-boot-with-zowe-api-mediation-layer.md

Update artifact version to the last one '1.1.0' and add `environment` parameters for local testing which were missing in the documentation.

Update artifact version and add yml sample for dev mode

---

docs/getting-started/summaryofchanges.md

Installer 1.1.1 changes

---

docs/README.md

Add link to Zowe Overview PPT in Box.

Update overview pdf

---

docs/.vuepress/config.js

update description to 1.2.x

---

docs/extend/extend-apiml/api-mediation-security.md

Add a new subsection to the API ML security doc

Add ciphers configuration

---

docs/.vuepress/config.js
docs/.vuepress/theme/Page.vue
docs/.vuepress/theme/styles/clipboard.styl
docs/.vuepress/theme/styles/code.styl
docs/.vuepress/theme/styles/theme.styl
docs/.vuepress/theme/styles/tooltip.styl

issue #434 copy to clipboard

---

docs/getting-started/overview.md
docs/user-guide/cli-cicsplugin.md
docs/user-guide/cli-db2plugin.md
docs/user-guide/cli-installplugins.md
docs/user-guide/cli-swreqplugins.md
docs/user-guide/cli-vscodeplugin.md

replaced all instances of Prerequisites with Software Requirements
*** Only CLI content

replaced all instances of Prerequisites with Software Requirements

---

docs/user-guide/api-mediation/api-mediation-overview.md
docs/user-guide/install-zos.md

Add TSS / ACF2 manual commands for BPX

---

docs/getting-started/summaryofchanges.md

Signed-off-by: Ashley <nannanli@cn.ibm.com>
Include all post-1.0 version release notes

Update release notes

---

docs/extend/extend-apiml/api-mediation-security.md
docs/extend/extend-desktop/zlux-app-server.md
docs/user-guide/cli-configuringcli.md
docs/user-guide/cli-usingcli.md
docs/user-guide/mvd-configuration.md
docs/user-guide/systemrequirements-zosmf-lite.md

Fixed all broken links in latest. 
Signed-off-by: BrandonJenkins14 <brandon.jenkins@broadcom.com>

Fix remaining links

---

docs/troubleshoot/troubleshoot-apiml.md

Changed to enable debug mode introduction

---

package.json

extend timeout to 2 minutes

---

dco_signoffs/Colin Stone-docs-site.txt

Colin Stone-docs-site

---

docs/user-guide/mvd-configuration.md

(MVD-2892).
Signed-off-by: jasonenglish2039 <jasone@rocketsoftware.com>

Configuring the Zowe App Server as Mediation Layer client

---

docs/extend/extend-apiml/api-mediation-security.md
docs/user-guide/install-zos.md

Update install zos and API ML docs

Update zowe docs - API ML Security section + Identifier for Zowe address spaces

---

docs/.vuepress/config.js

Extend the NPS popup interval

---

docs/user-guide/install-zos.md

Fix a typo

---

docs/user-guide/install-zos.md

ICSF and BPX clarification

---

docs/getting-started/zowe-architecture.md

add space to fix arch diagram

---

docs/user-guide/mvd-configuration.md

Signed-off-by: jasonenglish2039 <jasone@rocketsoftware.com>
Worked with the Vitek (community contributor) and Irek (Rocket developer) to vet and polish this doc.

New task topic to address #581.

---

docs/user-guide/systemrequirements-zosmf-lite.md

Signed-off-by: chentingcathy 974362914@qq.com

#596 More detail on where IZUTSSEC download location is

---

docs/user-guide/install-zos.md
docs/user-guide/installandconfig.md

Remove three references to /var/zowe from the install docs

Remove /var/zowe references

---

docs/.vuepress/versions.json

Update release version number for 1.2.x

---

docs/.vuepress/theme/styles/config.styl

update convert point to wrap navbar

---

docs/user-guide/install-zos.md

update doc to match install template change

---

docs/troubleshoot/cli/cli-issue.md
docs/troubleshoot/cli/troubleshoot-cli.md

- Fix typo
- add npm/node.js to "minimal info to gather"
- correct "git issue" to "GitHub Issue". 

Small addition to cli troubleshooting

---

docs/getting-started/cli-getting-started.md
docs/getting-started/freqaskques.md

Removed non-essential content from quick-start and added it to FAQ instead. 

remove section from quickstart

---

docs/troubleshoot/cli/mustgather-cli.md
docs/troubleshoot/cli/troubleshoot-cli.md

update troubleshooting path

---

docs/extend/extend-apiml/api-mediation-security.md

Documentation for the new `security-service-client-spring` module and for authentication.

Security-Client doc

---

docs/extend/extend-apiml/api-mediation-security.md

Signed-off-by: Igor Kazmyr <igor.kazmyr@broadcom.com>

Update the security doc

---

docs/user-guide/install-nodejs-zos.md
docs/user-guide/systemrequirements.md

Added back description about node.js v8 support

---

docs/extend/extend-cli/cli-devTutorials.md
docs/getting-started/cli-getting-started.md
docs/getting-started/summaryofchanges.md
docs/user-guide/cli-cicsplugin.md
docs/user-guide/cli-installplugins.md

Just some minor changes related to CLI plug-in branding.

Rebrand plug-ins

---

docs/README.md
docs/user-guide/cli-installcli.md
docs/user-guide/install-zos.md

Fix the Download link in v1.0 doc

---

docs/README.md
docs/user-guide/cli-installcli.md
docs/user-guide/install-zos.md

Fix the Download link in v1.1 doc

---

docs/README.md
docs/user-guide/cli-installcli.md
docs/user-guide/install-zos.md

Fix the Download link in v1.2 doc

---

docs/README.md
docs/getting-started/freqaskques.md
docs/user-guide/cli-installcli.md
docs/user-guide/install-zos.md

Fix the download link in v1.3.x doc

---

docs/.vuepress/config.js
docs/extend/zowe-conformance-program.md

Add Zowe Conformance Program link #654

---

docs/.vuepress/theme/components/AlgoliaSearchBox.vue
docs/.vuepress/theme/index.js

Also issue created on Vuepress Algolia search box: https://github.com/vuejs/vuepress/issues/1802

fix algolia search redirect

---

docs/extend/extend-apiml/api-mediation-onboard-an-existing-rest-api-service-without-code-changes.md
docs/extend/extend-apiml/api-mediation-security.md

Documentation to describe authentication in Discovery Service for HTTP and HTTPS

Discovery service authentication

---

.github/ISSUE_TEMPLATE/---doc-error-report.md
.github/ISSUE_TEMPLATE/---doc-site-enhancement-request.md
Jenkinsfile
docs/.vuepress/config.js
docs/.vuepress/public/sitemap.xml
docs/.vuepress/theme/NavLinks.vue
docs/.vuepress/versions.json
docs/README.md
docs/contributing.md
docs/extend/extend-apiml/api-mediation-security.md
gh-pages-default/404.html
gh-pages-default/index.html
package.json

- fix some links to https://zowe.github.io/
- remove /docs-site/
- convert /latest/ to /stable/
**NOTE: This PR should be coordinated with other PRs and merge at the time of migrating domains.**

WIP: Issue #650 prepare for migration to docs.zowe.org - V1.1.x 

---

.github/ISSUE_TEMPLATE/---doc-error-report.md
.github/ISSUE_TEMPLATE/---doc-site-enhancement-request.md
Jenkinsfile
docs/.vuepress/config.js
docs/.vuepress/public/sitemap.xml
docs/.vuepress/theme/NavLinks.vue
docs/.vuepress/versions.json
docs/README.md
docs/contribute/contributing.md
docs/contributing.md
docs/extend/extend-apiml/api-mediation-onboard-an-existing-java-rest-api-service-without-spring-boot-with-zowe-api-mediation-layer.md
docs/extend/extend-apiml/api-mediation-security.md
docs/getting-started/summaryofchanges.md
docs/troubleshoot/troubleshoot-app-framework.md
docs/user-guide/mvd-configuration.md
gh-pages-default/404.html
gh-pages-default/index.html
package.json

- fix some links to https://zowe.github.io/
- remove /docs-site/
- convert /latest/ to /stable/
**NOTE: This PR should be coordinated with other PRs and merge at the time of migrating domains.**

WIP: Issue #650 prepare for migration to docs.zowe.org - V1.2.x

---

.github/ISSUE_TEMPLATE/---doc-error-report.md
.github/ISSUE_TEMPLATE/---doc-site-enhancement-request.md
Jenkinsfile
docs/.vuepress/config.js
docs/.vuepress/public/sitemap.xml
docs/.vuepress/public/web_help/docs/zowe.html
docs/.vuepress/theme/NavLinks.vue
docs/.vuepress/versions.json
docs/README.md
docs/contribute/contributing.md
docs/contribute/guidelines-code/documentation.md
docs/extend/extend-apiml/api-mediation-onboard-an-existing-java-rest-api-service-without-spring-boot-with-zowe-api-mediation-layer.md
docs/extend/extend-apiml/api-mediation-security.md
docs/getting-started/summaryofchanges.md
docs/troubleshoot/troubleshoot-app-framework.md
docs/user-guide/mvd-configuration.md
gh-pages-default/404.html
gh-pages-default/index.html
package.json

Signed-off-by: nannanli <nannanli@cn.ibm.com> 
- fix some links to https://zowe.github.io/
- remove /docs-site/
- convert /latest/ to /stable/
**NOTE: This PR should be coordinated with other PRs and merge at the time of migrating domains.**

WIP: Issue #650 prepare for migration to docs.zowe.org - V1.3.x

---

docs/user-guide/install-zos.md

Add note about user dir permissions

---

docs/user-guide/install-zowe-smpe.md

Fix broken links

---

docs/user-guide/configure-zowe-runtime.md
docs/user-guide/install-zowe-zos-convenience-build.md

Incorporate Steve's changes in PR 701 and 703

---

docs/user-guide/install-zowe-smpe.md

Add description information about using default #csivol in sample installation job ZWE1SMPE per issue #702.

#702 Add information about using default #csivol

---

docs/user-guide/install-zowe-smpe.md

#717 Fix an incorrect description

---

docs/extend/extend-cli/cli-setting-up.md

Describe why there are different versions of CLI, corresponding sample branches, and the benefit of developing for both. 
Also add step to switch to `lts-incremental` branch for this version of tutorial. 

add background about branches and add step to switch branches

---

docs/user-guide/install-zowe-smpe.md
gh-pages-default/404.html

fix broken link to https://zowe.github.io/docs-site/latest

---

Jenkinsfile

set memory for build

---

docs/extend/extend-cli/cli-setting-up.md

fixes zowe/zowe-cli-sample-plugin#41

remove outdated text

---

Jenkinsfile

lock building pdf step

---

Jenkinsfile

lock pdf build step

---

docs/user-guide/cli-installcli.md

Describe location of download button 

---

docs/troubleshoot/troubleshoot-apiml.md

remove - bullet

---

docs/user-guide/configure-zowe-runtime.md

Signed-off-by: nannanli <nannanli@cn.ibm.com> 
Fixes: #727

doc: Added description for the tssFacilityOwner parm

---

docs/troubleshoot/troubleshoot-apiml.md

Signed-off-by: Vsevolod Khanin <vsevolod.khanin@broadcom.com>

loglevel parameter for apiml

---

docs/user-guide/configure-zowe-runtime.md

Updates to reflect new code for auxiliary address spaces, including ZWESAUX load module etc.

Cross Mem Server installation updates

---

docs/user-guide/configure-zowe-runtime.md

Fixes: https://github.com/zowe/docs-site/issues/787
- Updated the script path
- Improved the wording

doc: Correct the script path

---

docs/user-guide/systemrequirements-zosmf-lite.md

Fix link in z/OSMF Lite doc

---

docs/appendix/tpsr.md

fix copyright symbols in tpsrs

---

docs/user-guide/configure-zowe-runtime.md

Sync a change

---

docs/getting-started/summaryofchanges.md

Signed-off-by: jasonenglish <jasone@rocketsoftware.com>
Issue number: N/A

1.7.x app server release notes updates

---

docs/user-guide/cli-vscodeplugin.md

Need to update the Zowe Explorer in Zowe Docs. So far blocked by https://github.com/zowe/vscode-extension-for-zowe/pull/301 Please do not merge until that pr is merged.
Issue number: https://github.com/zowe/vscode-extension-for-zowe/issues/297

Update Zowe Explorer (VSC extension) doc

---

docs/troubleshoot/troubleshoot-apiml.md

Missed documentation about how to enable debug mode for apiml added
Signed-off-by: Vsevolod Khanin <vsevolod.khanin@broadcom.com>

minor change in the debug apiml section

---

docs/user-guide/cli-vscodeplugin.md

Add the rename and copy feature and add minor edits to the doc
Issue number: https://github.com/zowe/vscode-extension-for-zowe/issues/323

ZE Zowe doc update (add the rename feature + minor edits)

---

docs/.vuepress/config.js
docs/README.md
docs/getting-started/summaryofchanges.md
docs/user-guide/cli-vscodeplugin.md

Docs for V1.7.1

---

docs/user-guide/configure-zowe-runtime.md

User did not know where to find an alias of certificate
Signed-off-by: Vitek Vlcek <vitezslavvit.vlcek@broadcom.com>

how to find alias name

---

docs/extend/extend-apiml/api-mediation-onboard-an-existing-java-rest-api-service_plain-java-enabler.md
docs/extend/extend-apiml/api-mediation-onboard-plain-java-enabler-external-configuration.md
docs/extend/extend-apiml/api-mediation-onboard-rest-service-direct-eureka-call.md

Signed-off-by: janda06 <david.janda@broadcom.com>
Documentation to plain java enabler

extract of pza/plain-java-enabler for merging

---

docs/.vuepress/pages.json

@janan07 Thought I'd move this to a fresh branch for you, the previous was not DCO signed, and I slightly adjusted the titles in the TOC for consistentcy. We can merge this whenever you like. 

Add API ML topics to TOC

---

.gitignore
docs/extend/extend-apiml/api-mediation-onboard-an-existing-java-rest-api-service_plain-java-enabler.md

Pje acceptance review

---

dco_signoffs/Ashley Li-docs-site.txt

Upload DCO signoff for a previous commit

---

docs/extend/extend-apiml/api-mediation-onboard-an-existing-rest-api-service-without-code-changes.md

Fixes #867 - Removes the smiley face from our doc

Fix URL formatting for #867 

---

docs/troubleshoot/app-framework/app-known-issues.md
docs/user-guide/configure-zowe-runtime.md
docs/user-guide/mvd-configuration.md

ZWEX to ZWES

---

docs/.vuepress/public/google68b44a91473a6cd7.html

Upload the file that will enable google search console. It will allow us to see more information about the search behavior. 
Issue number:

Enable Google Search Console

---

docs/extend/extend-apiml/api-mediation-onboard-an-existing-java-rest-api-service_plain-java-enabler.md
docs/extend/extend-desktop/mvd-buildingplugins.md

Fixes 2 broken links. Updating other branches from staging will fix some failed PRs.

Fix links in staging

---

docs/getting-started/summaryofchanges.md

The release notes updates for v.1.8.0 correspond to the following stories:
US618074
https://rally1.rallydev.com/#/detail/userstory/337998326208
US601301
https://rally1.rallydev.com/#/72725828452d/detail/userstory/319402674588
US606606
https://rally1.rallydev.com/#/72725828452d/detail/userstory/326928402212

Api ml release notes 1.8.0

---

docs/user-guide/configure-zowe-runtime.md
docs/user-guide/install-zowe-zos-convenience-build.md

#48 ## Is there a related issue for this PR? 
https://github.com/zowe/zowe-install-packaging/issues/862

Zowe Install Packaging - 862 - Document zowe-install-proc.sh 

---

docs/user-guide/install-nodejs-zos.md

Node 8.16.2 is available which fixes the 8.16.1 issue so update the docs to remove the ref to need 8.16.0
Issue number: #890 
Node 8.16.2 is available which fixes the 8.16.1 issue so update the docs to remove the ref to need 8.16.0

docs: Update description about node v8.16.1 issue and workaround in v1.7.x

---

docs/extend/extend-apiml/api-mediation-onboard-a-sprint-boot-rest-api-service.md
docs/extend/extend-apiml/api-mediation-onboard-an-existing-java-jersey-rest-api-service.md
docs/extend/extend-apiml/api-mediation-onboard-an-existing-java-rest-api-service-without-spring-boot-with-zowe-api-mediation-layer.md

switch to zowe artifactory (issue #853)

---

docs/extend/extend-apiml/api-mediation-onboard-a-spring-boot-rest-api-service.md
docs/extend/extend-apiml/api-mediation-onboard-an-existing-java-jersey-rest-api-service.md
docs/extend/extend-apiml/api-mediation-onboard-an-existing-java-rest-api-service-without-spring-boot-with-zowe-api-mediation-layer.md

switch to zowe artifactory for v1.1.x (issue #853)

---

docs/extend/extend-apiml/api-mediation-onboard-a-spring-boot-rest-api-service.md
docs/extend/extend-apiml/api-mediation-onboard-an-existing-java-jersey-rest-api-service.md
docs/extend/extend-apiml/api-mediation-onboard-an-existing-java-rest-api-service-without-spring-boot-with-zowe-api-mediation-layer.md

switch to zowe artifactory for v1.2.x (issue #853)

---

docs/extend/extend-apiml/api-mediation-onboard-a-spring-boot-rest-api-service.md
docs/extend/extend-apiml/api-mediation-onboard-an-existing-java-jersey-rest-api-service.md
docs/extend/extend-apiml/api-mediation-onboard-an-existing-java-rest-api-service-without-spring-boot-with-zowe-api-mediation-layer.md

switch to zowe artifactory for v1.3.x (issue #853)

---

docs/extend/extend-apiml/api-mediation-onboard-a-spring-boot-rest-api-service.md
docs/extend/extend-apiml/api-mediation-onboard-an-existing-java-jersey-rest-api-service.md
docs/extend/extend-apiml/api-mediation-onboard-an-existing-java-rest-api-service-without-spring-boot-with-zowe-api-mediation-layer.md

switch to zowe artifactory for v1.4.x

---

docs/extend/extend-apiml/api-mediation-onboard-a-spring-boot-rest-api-service.md
docs/extend/extend-apiml/api-mediation-onboard-an-existing-java-jersey-rest-api-service.md
docs/extend/extend-apiml/api-mediation-onboard-an-existing-java-rest-api-service-without-spring-boot-with-zowe-api-mediation-layer.md

switch to zowe artifactory for v1.5.x

---

docs/extend/extend-apiml/api-mediation-onboard-a-spring-boot-rest-api-service.md
docs/extend/extend-apiml/api-mediation-onboard-an-existing-java-jersey-rest-api-service.md
docs/extend/extend-apiml/api-mediation-onboard-an-existing-java-rest-api-service-without-spring-boot-with-zowe-api-mediation-layer.md

switch to zowe artifactory for v1.6.x

---

docs/extend/extend-apiml/api-mediation-onboard-a-spring-boot-rest-api-service.md
docs/extend/extend-apiml/api-mediation-onboard-an-existing-java-jersey-rest-api-service.md
docs/extend/extend-apiml/api-mediation-onboard-an-existing-java-rest-api-service-without-spring-boot-with-zowe-api-mediation-layer.md

switch to zowe artifactory for v1.7.x

---

docs/extend/extend-apiml/api-mediation-onboard-a-spring-boot-rest-api-service.md
docs/extend/extend-apiml/api-mediation-onboard-an-existing-java-jersey-rest-api-service.md
docs/extend/extend-apiml/api-mediation-onboard-an-existing-java-rest-api-service-without-spring-boot-with-zowe-api-mediation-layer.md

switch to zowe artifactory for active-development

---

docs/user-guide/cli-installcli.md

docs: Fixed two links in Zowe CLI

---

docs/getting-started/summaryofchanges.md

Signed-off-by: jasonenglish <jasone@rocketsoftware.com>
Issue number:

Zowe App Server 1.8 release notes

---

docs/user-guide/configure-instance-directory.md
docs/user-guide/configure-xmem-server.md
docs/user-guide/configure-zos-system.md
docs/user-guide/configure-zowe-server.md
docs/user-guide/install-zos.md
docs/user-guide/install-zowe-zos-convenience-build.md

Edits to the 1.8.0 installation doc

---

docs/user-guide/mvd-configuration.md

Signed-off-by: jasonenglish <jasone@rocketsoftware.com>
Issue number:

Removed links to topic that is no longer there!

---

docs/user-guide/mvd-configuration.md

Signed-off-by: jasonenglish <jasone@rocketsoftware.com>
Issue number:

app visibility updates

---

docs/.vuepress/pages.json
docs/user-guide/configure-xmem-server.md
docs/user-guide/install-zos.md

make the diagram clickable

---

docs/.vuepress/versions.json

add v1.7.x to versions

---

docs/user-guide/zowe-getting-started-tutorial.md

Adjusted the 3270 naming to be more technically accurate.
Issue number: #977

Update zowe-getting-started-tutorial.md: 3270

---

dco_signoffs/Onno-Van-den-Troost.txt

Issue number: 
Signed-off-by: Onno Van den Troost <onno@us.ibm.com>

add dco for updates via browser

---

docs/extend/extend-apiml/api-mediation-onboard-a-spring-boot-rest-api-service.md
docs/extend/extend-apiml/api-mediation-onboard-an-existing-java-rest-api-service-without-spring-boot-with-zowe-api-mediation-layer.md
docs/extend/extend-apiml/api-mediation-onboard-an-existing-java-rest-api-service_plain-java-enabler.md
docs/extend/extend-apiml/api-mediation-onboard-an-existing-rest-api-service-without-code-changes.md
docs/extend/extend-apiml/api-mediation-onboard-rest-service-direct-eureka-call.md
docs/extend/extend-apiml/api-mediation-security.md
docs/troubleshoot/troubleshoot-apiml-error-codes.md
docs/user-guide/configure-instance-directory.md
docs/user-guide/install-zos.md

Add documentation for tomcat slash configuration

Add documentation for tomcat slash configuration

---

docs/user-guide/configure-certificates.md

Signed-off-by: OnnoVdT <49648041+OnnoVdT@users.noreply.github.com>
Issue number: 
Signed-off-by: Onno Van den Troost <onno@us.ibm.com>

typo in path

---

docs/.vuepress/pages.json
docs/contribute/guidelines-code/categories.md
docs/extend/extend-apiml/onboard-direct-eureka-call.md
docs/extend/extend-apiml/onboard-overview.md
docs/extend/extend-apiml/onboard-plain-java-enabler-external-configuration.md
docs/extend/extend-apiml/onboard-plain-java-enabler.md
docs/extend/extend-apiml/onboard-spring-boot-enabler.md
docs/extend/extend-apiml/onboard-static-definition.md
docs/extend/extender-architecture.md
docs/getting-started/freqaskques.md
docs/getting-started/overview.md
docs/user-guide/api-mediation-api-catalog.md
docs/user-guide/api-mediation/api-mediation-api-catalog.md
docs/user-guide/api-mediation/api-mediation-overview.md
docs/user-guide/zowe-getting-started-tutorial.md

Fix the broken links.

---

docs/user-guide/configure-instance-directory.md

Issue number: 
Signed-off-by: Onno Van den Troost <onno@us.ibm.com>

fix typos in configure-instance-directory.md

---

docs/extend/extend-apiml/onboard-static-definition.md

Clean the explanations for the necessary steps.
Issue number:

Add all necessary prerequisites for the process

---

docs/user-guide/configure-instance-directory.md

Signed off by: 1000TurquoisePogs <sgrady@rocketsoftware.com>

Incorrect instance.env path

---

docs/.vuepress/styles/details.styl
docs/getting-started/freqaskques.md
docs/getting-started/summaryofchanges.md
docs/user-guide/configure-instance-directory.md

Fix conflicts

---

docs/troubleshoot/troubleshoot-diagnostics.md

Signed-off-by: John Davies <daviesja@uk.ibm.com>
#1107 in install-packaging

Add note about TSO exit

---

docs/user-guide/installandconfig.md

Fix an incorrect JCL name

---

docs/troubleshoot/troubleshoot-diagnostics.md

Lift jobname restriction on TSO OUTPUT

---

docs/user-guide/configure-zos-system.md

fixes #1063
Issue number: #1063

Fix the commands for creating Zowe Group&Userids

---

docs/.vuepress/config.js
docs/.vuepress/versions.json
docs/README.md
docs/getting-started/summaryofchanges.md

Bump version to 1.10

---

docs/getting-started/summaryofchanges.md

Fixing broken links in the release notes TOC.

Fix Release Notes TOC

---

docs/user-guide/install-nodejs-zos.md

- Added the high-level steps for configuring ICSF. It's a prereq for node.js.
- Removed out-of-date download link.
- Refactored the whole topic to better organize the information.
Issue number: #1073

Improve the Node.js install doc

---

docs/extend/extend-apiml/onboard-direct-eureka-call.md
docs/user-guide/configure-instance-directory.md

Corrected that DT doesn't exist, and DS is the app server
More problems I found that I don't have a solution for yet listed here: https://github.com/zowe/docs-site/issues/1101

Subcomponent meaning fix

---

docs/README.md
docs/extend/extend-apiml/onboard-direct-eureka-call.md
docs/user-guide/configure-instance-directory.md
docs/user-guide/mvd-using.md

Update v1.9.x from master branch

---

.github/ISSUE_TEMPLATE/troubleshooting-tip.md

Add issue template for troubleshooting tips

---

docs/user-guide/configure-xmem-server.md
docs/user-guide/configure-zowe-server.md

Issue number: #1054 
Docs updates in the next release (post 1.10) of zowe

Update doc to match scripts

---

docs/getting-started/summaryofchanges.md

Update to 1.10 release notes

---

docs/troubleshoot/troubleshoot-diagnostics.md

Update doc info

---

docs/troubleshoot/troubleshoot-diagnostics.md
docs/user-guide/configure-instance-directory.md

Sync PR#1129 updates to live version

---

docs/user-guide/configure-certificates.md
docs/user-guide/configure-xmem-server.md
docs/user-guide/configure-zowe-server.md
docs/user-guide/install-zowe-zos-convenience-build.md

1133 - document log directory parameter

---

docs/troubleshoot/troubleshoot-apiml-error-codes.md

zaas client and gateway retry messages

---

docs/getting-started/summaryofchanges.md

Placeholder section for 1.11 release notes 

---

docs/user-guide/cli-vscodeplugin.md

Update the Zowe Explorer docs. Add a section on how to work with user profiles, and how to use Secure Credential Store.
Update the Release Notes.
Issue number:

Update the Zowe Explorer doc

---

docs/getting-started/summaryofchanges.md

Add release notes for sso changes to explorer components

---

docs/.vuepress/pages.json
docs/getting-started/summaryofchanges.md
docs/getting-started/zowe-resources.md

Add resource page

---

docs/user-guide/systemrequirements.md

documentation for using webtokens for sso

---

docs/extend/extend-apiml/api-mediation-security.md
docs/user-guide/configure-certificates.md

Configure security certificates with the z/OSMF workflow

[z/OSMF Workflow] Include instructions to configure certificates with z/OSMF Workflow

---

docs/extend/lifecycling-with-zwesvstc.md
docs/troubleshoot/troubleshooting.md

To be merged after https://github.com/zowe/zowe-install-packaging/pull/1335
Issue number: #1180

[Post-v1.11] Add validate mode info

---

docs/extend/extend-apiml/api-mediation-security.md
docs/user-guide/install-zowe-zos-convenience-build.md

Added a new procude on how to install runtime with z/OSMF workflows.

[z/OSMF Workflow] Information on how to install zowe runtime with z/OSMF workflows

---

docs/user-guide/configure-zowe-server.md

Provides information on how to configure zowe instance and start the Zowe started task.

[z/OSMF Workflow] Document how to start the zowe started task with the z/OS workflows

---

docs/user-guide/configure-zos-system.md

Configure Security Manager with z/OSMF Workflow

[z/OSMF Workflow] Configure zowe sercure

---

docs/user-guide/install-zowe-smpe.md

Issue number: #1193
Same fix as in #1217

Update SMP/E PTF information in v1.10

---

docs/troubleshoot/troubleshoot-apiml.md

fixes #1223 
https://github.com/zowe/api-layer/issues/272

Add a new troubleshooting tip

---

docs/user-guide/install-zowe-smpe.md

updated extract job example with missing archid and newname entry for AZWE001.F3
Issue number: 
Signed-off by: Leo Khan <lkhan@skywarditsolutions.com>

extract job example missing entry for AZWE001.F3

---

docs/user-guide/configure-certificates.md

Fixed an incorrect location in doc

---

docs/getting-started/summaryofchanges.md

Updated to be user-focussed and arranged sections

1.12 install release notes updates

---

docs/README.md
docs/user-guide/configure-certificates.md

Update 1.11 PDF

---

docs/getting-started/summaryofchanges.md
docs/user-guide/install-nodejs-zos.md
docs/user-guide/systemrequirements.md

added note: starting Sept, node v6 is no longer supported 

---

docs/getting-started/summaryofchanges.md
docs/user-guide/ze-install.md
docs/user-guide/ze-profiles.md
docs/user-guide/ze-usage.md

It's quite self-explanatory PR.

Fix the gif's misalignment

---

docs/user-guide/install-zowe-smpe.md

- Added the PTF numbers for v1.12 SMP/E.
- updated the download links

Added PTF info for v1.12

---

docs/getting-started/summaryofchanges.md

Update the Zowe Installation sub-section with the z/OSMF Workflows release note (Version 1.12.0 LTS (June 2020))
Update the Version 1.12.0 LTS (June 2020) > Zowe Installation sub-section. Add the note about the z/OSMF Workflows.

Update the RNs with the z/OSMF Workflows information (Zowe Installation section)

---

docs/getting-started/summaryofchanges.md

Added summary of installation changes in the v1.13 release to the release notes. 

Zowe v1.13 installation updates

---

docs/extend/extend-apiml/onboard-plain-java-enabler.md

Option to prefer IP address at registration to eureka for enablers.

prefer IP address option for enablers

---

docs/troubleshoot/verify-fingerprint.md

Edits to fingerprint doc

---

docs/getting-started/summaryofchanges.md

Zowe Explorer release notes for Zowe (1.13) update

---

docs/getting-started/overview.md
docs/getting-started/summaryofchanges.md
docs/user-guide/cli-installcli.md
docs/user-guide/install-zos.md
docs/user-guide/install-zowe-smpe.md
docs/user-guide/install-zowe-zos-convenience-build.md
docs/user-guide/update-zos.md

- Fixed an incorrect link
- Updated the download URL to https://www.zowe.org/download.html

Fix arch link and update download URL

---

docs/getting-started/summaryofchanges.md

- Updated the date to July
- Removed an unused section title

Fix the date in the release notes

---

docs/user-guide/configure-xmem-server.md

Fix an incorrect task name

---

docs/getting-started/summaryofchanges.md

Updated 1.13 release notes

---

docs/extend/extend-desktop/mvd-apptoappcommunication.md

docu for Cross-launch via URL

---

docs/user-guide/zowe-getting-started-tutorial.md

updated getting started tutorial

---

docs/extend/extend-apiml/onboard-static-definition.md

The PR is linked to the issue: https://github.com/zowe/api-layer/issues/405
Add example for calling of the static api reload using the curl as well as httpie

Use Curl in the API ML Example

---

docs/getting-started/summaryofchanges.md

- Document changes for the 1.14 release. 

Add fingerprint to notable changes for 1.14

---

docs/appendix/bill-of-materials.md

Added a meta section to one topic to test SEO performance enhancement.  

Added meta for SEO test

---

dco_signoffs/Carson-Cook-docs-site.txt

Add Carson Cook dco signoff

---

dco_signoffs/Jakub-Balhar-docs-site.txt

Sign off via document for non signed off commit.

Provide SignOff for v 1.14

---

docs/getting-started/summaryofchanges.md

Add Summary of Changes for API ML v1.14.

Add Summary of Changes for API ML v1.14

---

docs/getting-started/summaryofchanges.md

fix cli bug section

---

docs/user-guide/configure-xmem-server.md
docs/user-guide/configure-zowe-server.md
docs/user-guide/scripted-configure-server.md

**fix** https://github.com/zowe/docs-site/issues/1328
Separate scripted from manual install chapters (following user feedback it was confusing they were in the same chapter) and also incorporated changes from Onno where the cross memory install script has been updated for 1.13

Corrections

---

docs/getting-started/summaryofchanges.md

This PR Updates the Zowe CLI release notes for the Zowe 1.14 release.
Signed-off-by: MikeBauerCA <Michael.Bauer2@broadcom.com>

Update Zowe CLI release notes

---

docs/getting-started/summaryofchanges.md

Update the Zowe Explorer RN section in 1.14.

Update Zowe Explorer release notes for Zowe 1.14

---

docs/extend/extend-apiml/api-mediation-components-of-URL.md

Adds examples for the URL path pattern as implemented in [APIML PR #779](https://github.com/zowe/api-layer/pull/779) and discussed in [APIML Issue #688](https://github.com/zowe/api-layer/issues/688).

Add new URL path pattern examples

---

docs/README.md

Fix pdf and update two buttons

---

docs/user-guide/api-mediation/api-gateway-configuration.md

With the change to the default behavior update the configuration. 

Update documentation for encoding

---

docs/user-guide/mvd-using.md

updates to plugins overview

---

docs/user-guide/api-mediation/api-gateway-configuration.md
docs/user-guide/api-mediation/discovery-service-configuration.md
docs/user-guide/install-zos.md

Enhancement of the API GW and DS configuration
Fix https://github.com/zowe/api-layer/issues/720

Document properly configuration of the API Mediation Layer

---

docs/getting-started/summaryofchanges.md

Pulled information from CHANGELOGs into release notes for the following components: 
- APIML
- Zowe CLI
- Zowe Explorer (no updates this time) 
- Zowe installation (no updates available) 

Pull release notes entries from CHANGELOGs

---

docs/getting-started/summaryofchanges.md

Release notes updates

---

docs/appendix/tpsr.md

Populates the TPSR file for upcoming release.

v1.15.0 TPSRs

---

docs/.vuepress/config.js

The favicon does not appear live site. Added a link from head so that it can publish the icon.  Addresses #1399

Fix favicon

---

docs/.vuepress/pages.json
docs/appendix/zowe-api-reference.md
docs/appendix/zowe-cli-commannd-reference.md

Updated the navigation of the reference section. 

Edits to reference doc TOC

---

docs/troubleshoot/troubleshoot-apiml-error-codes.md

Update apiml error codes

---

docs/getting-started/zowe-resources.md

Bloggers wanted to find information on how to contribute to medium.com/zowe, so added a link in the docs to the publication guidelines.
Also included links to the youtube video channels for Mainframe Bytes (from @jellypuno) and the Zowe Demos playlist (from Bill Pereria)

Link to medium.com/zowe guidelines + external

---

docs/user-guide/systemrequirements.md

Signed-off-by: Jordan Cain <jordan.cain1@uk.ibm.com>
APIML now always tries to use the z/OSMF jwt endpoints for login/logout so ensure customers have the apar related PR from api-layer: https://github.com/zowe/api-layer/pull/809

Add refrence to zosmf JWT support apar

---

docs/extend/extend-apiml/onboard-plain-java-enabler.md

Fix the TOC and remove duplicate API info section

---

docs/getting-started/summaryofchanges.md

Direct PR against the summary of changes for 1.16 covering certificate documentation and keyring support

Keyring update for 1.16 new and noteworthy

---

docs/troubleshoot/app-framework/app-troubleshoot.md

#1377 Add a troubleshooting tip

---

docs/user-guide/systemrequirements.md

fixes #1389 
z/OS V2.2 reaches EOS on Sep 30. Update the doc to reflect this change. 

Update z/OS support statement in system requirements

---

docs/getting-started/summaryofchanges.md

My changelog PRs did not merge in time to get picked up by Release Notes automation. Adding the changes to Release Notes here. 
Lesson learned, I need merge these PRs earlier/faster.

Edit CLI changes for 1.16.0

---

docs/getting-started/summaryofchanges.md

app server release notes for 1.16

---

docs/appendix/tpsr.md

Updated TPSRs and re-archived PDF for 1.16.0

Update tpsrs and PDF

---

docs/README.md

Fix a version issue on the homepage

---

docs/troubleshoot/cli/mustgather-cli.md
docs/user-guide/systemrequirements.md

Needed to open this PR with `master` as the base. Contains the same changes that were already reviewed and approved for Node LTS support w/ CLI.
Closing #1454

Reapply changes from #1454 for CLI node requirement

---

docs/user-guide/systemrequirements.md

- Change link to point to Node.js wbsite "Releases" page. 
- Fixed typo in website name.

Update node.js link

---

docs/getting-started/summaryofchanges.md

Incorporate comments on 1.16 release notes

---

docs/user-guide/sdks-using.md

Fix syntax in SDK doc

---

docs/.vuepress/config.js
docs/.vuepress/versions.json
docs/README.md
docs/getting-started/summaryofchanges.md

Bump release version to v1.17

---

docs/extend/extend-cli/cli-devTutorials.md

Easy navigation and easy reading for others

Fix broken url in docs

---

docs/user-guide/cli-db2plugin.md

updated docs as per
https://github.com/zowe/zowe-cli-db2-plugin/issues/61
Signed-off-by: M P <mpanch59@hotmail.com>
Fixes https://github.com/zowe/zowe-cli-db2-plugin/issues/61

Incorrect license location in doc : Update cli-db2plugin.md

---

docs/user-guide/cli-db2plugin.md

https://github.com/zowe/zowe-cli-db2-plugin/issues/62

Update docs#62 cli-db2plugin.md

---

docs/user-guide/configure-certificates-keystore.md

minor edits to enabling sso doc

---

docs/getting-started/summaryofchanges.md

additional notes for app server 1.17 release

---

docs/user-guide/mvd-configuration.md

In the "Configuring the Zowe App Server for HTTPS communication with ZSS" section. Step 1 should use the same sample-path as step 3
See https://github.com/zowe/docs-site/issues/1300#issue-652533031
fixes #1300 

Fix - Update mvd-configuration.md

---

Jenkinsfile

Related to https://github.com/zowe/zlc/issues/199

use new build agent

---

docs/troubleshoot/troubleshoot-apiml-error-codes.md
docs/user-guide/api-mediation/api-gateway-configuration.md
docs/user-guide/api-mediation/api-mediation-internal-configuration.md

Document new log messages introduced in https://github.com/zowe/api-layer/pull/1030

Add new log messages for connection limits

---

docs/troubleshoot/troubleshoot-apiml-error-codes.md

Improve description of connection limit log messages as per https://github.com/zowe/api-layer/issues/987.

APIML connection limit logging enhancement

---

docs/user-guide/cli-db2plugin.md

**fix** https://github.com/zowe/zowe-cli-db2-plugin/issues/68

Mac and license updates

---

docs/user-guide/api-mediation/api-gateway-configuration.md

The API Mediation Layer is occasionally run as a separate component within the Zowe project. This documentation explains how to properly start only the API Mediation Layer. 
Related to the https://github.com/zowe/api-layer/issues/856

Explain the changes for the standalone setup of the API Mediation Layer

---

docs/getting-started/summaryofchanges.md

https://github.com/zowe/api-layer/issues/856

Add install API ML as a standalone component

---

docs/getting-started/summaryofchanges.md

app server release notes for 1.18

---

docs/.vuepress/config.js
docs/README.md
docs/getting-started/summaryofchanges.md

Doc site basic setup for new release

---

docs/getting-started/summaryofchanges.md

1.19 appserver release notes

---

docs/user-guide/mvd-editor.md

added additional hotkeys to editor doc

---

docs/extend/extend-apiml/api-mediation-security.md

X509 enhance prerequisities - Zowe user password set

---

docs/user-guide/mvd-editor.md

Signed-off-by: ajinrocket <56607160+ajinrocket@users.noreply.github.com>

updates to the hotkeys doc for the editor

---

docs/getting-started/summaryofchanges.md

Refactor X.509 client certificate authentication in Notable Changes

---

docs/getting-started/summaryofchanges.md

Minor edit to x.509 notable change

---

docs/getting-started/summaryofchanges.md

Improve description of API ML changes in r1.19

---

docs/extend/extend-apiml/api-mediation-security.md

This PR should be merged prior to 1.19 documentation gets published. Apologies for the late submission.

Client cert auth add zosmf rights prerequisite

---

docs/getting-started/summaryofchanges.md

Fix the release date

---

docs/.vuepress/pages.json
docs/extend/extend-apiml/onboard-direct-eureka-call.md
docs/extend/extend-apiml/onboard-nodejs-enabler.md
docs/extend/extend-apiml/onboard-overview.md
docs/extend/extend-apiml/onboard-plain-java-enabler-external-configuration.md
docs/extend/extend-apiml/onboard-plain-java-enabler.md
docs/extend/extend-apiml/onboard-spring-boot-enabler.md
docs/extend/extend-apiml/onboard-static-definition.md
docs/getting-started/overview.md

API ML Onboarding Node.js Enabler doc

---

docs/extend/extend-apiml/onboard-nodejs-enabler.md

Small update of the npm package name of nodejs enabler

---

docs/.vuepress/config.js
docs/README.md
docs/getting-started/summaryofchanges.md

prepare for v1.19.1

---

docs/user-guide/systemrequirements-zosmf-lite.md

This PR updates the link to ACF2 documentation. The existing one leads to 404.

Use correct link to ACF2 documentation

---

docs/extend/extend-apiml/onboard-plain-java-enabler.md
docs/user-guide/api-mediation/api-mediation-internal-configuration.md

https://github.com/zowe/api-layer/issues/1159

New authentication scheme

---

docs/.vuepress/public/Zowe_introduction_video_script.txt
docs/getting-started/overview.md

Updated the Zowe overview video link and upload deck/script

---

docs/getting-started/summaryofchanges.md

Updating the Zowe Explorer release notes for the upcoming release.

Update Zowe Explorer Release Notes in Zowe Docs

---

docs/extend/extend-apiml/api-mediation-security.md
docs/user-guide/install-zowe-zos-convenience-build.md

Fixes: #1604 , #1600 
@nannanli for review

Fixed typos in  z/OSMF workflow doc, Manual

---

docs/extend/extend-apiml/onboard-micronaut-enabler.md

Minor fixes for API doc

---

docs/getting-started/overview.md

Fixes issue: https://github.com/zowe/api-layer/issues/1287

fix broken link

---

docs/troubleshoot/troubleshoot-apiml-error-codes.md

Update message to indicate Gateway will shut down after the error causing the log.

Update apiml jwt initialization error message

---

docs/.vuepress/config.js
docs/README.md
docs/getting-started/summaryofchanges.md

Fixes https://github.com/zowe/zowe-install-packaging/issues/2032

prepare for v1.20.1 release

---

docs/user-guide/api-mediation/api-gateway-configuration.md

changes for latest round of externalized variables

Apiml start script variables

---

docs/user-guide/configuring-docker.md

Signed-off-by: ajinrocket <56607160+ajinrocket@users.noreply.github.com>

updated directories for customization

---

docs/getting-started/summaryofchanges.md

Minor formatting fixes to API ML Summary of Changes for r1.21

---

docs/user-guide/systemrequirements-zosmf.md

Signed-off-by: chinmaym07 <b418020@iiit-bh.ac.in>
fix : #1613 

Updated the link of ACF2 z/OSMF setup

---

docs/extend/install-configure-zos-extensions.md

Add documentation for the Zowe component upgrade script

---

docs/user-guide/api-mediation/api-gateway-configuration.md

change password using SAF

---

docs/user-guide/api-mediation/api-gateway-configuration.md

Signed-off-by: jandadav <janda.david@gmail.com>

Missing prop for saf check endpoint

---

docs/user-guide/install-zowe-smpe.md

Added a list of Zowe releases in the SMP/E doc. 

Fix SMP/E doc to add Zowe releases

---

docs/getting-started/summaryofchanges.md

Added Zowe CLI information for release 1.22.0
Adding release note information for 1.22.

Update summaryofchanges.md with Zowe CLI

---

src/css/custom.css

After #1747 PR, duplicate headings are visible on each doc page.
This PR temporarily fixes the issue. The might be caused due to some of the package updates.

Fix duplicate headings issue in Doc

---

docs/getting-started/zowe-getting-started.md

Notice about versions

---

_versioned_docs/version-v1.22.x/extend/extend-apiml/onboard-direct-eureka-call.md
docs/extend/extend-apiml/onboard-direct-eureka-call.md

Document issue when omitting vipAddress during manual Eureka registration

---

docs/user-guide/install-nodejs-zos.md
docs/user-guide/systemrequirements-zos.md

We identified failures with node v14.17.2 release, exclude support of this node version.
Part of fix of https://github.com/zowe/zowe-install-packaging/issues/2291

exclude support of node v14.17.2

---

docs/extend/extend-apiml/api-mediation-security.md
docs/user-guide/api-mediation/api-gateway-configuration.md

GH1625 Refresh endpoint documentation

---

docs/user-guide/install-docker.md
docs/user-guide/install-ha-sysplex.md
docs/user-guide/install-zos.md

fix: attempt to fix the broken links

---

docs/extend/extend-apiml/onboard-plain-java-enabler.md
sidebars.js

Fix link to custom metadata page

---

docs/user-guide/install-zowe-smpe.md

add cyl size/note

---

docs/extend/extend-desktop/mvd-authentication-api.md
docs/extend/extend-desktop/mvd-logutility.md

Edited two files for resolving merge conflicts listed in 1788.

Resolved merge conflicts for 1788

---

docs/extend/extend-apiml/custom-metadata.md

Add description of `customMetadata.apiml.headersToIgnore`.

Add headersToIgnore metadata

---

docs/user-guide/cli-db2plugin.md

Signed-off-by: MikeBauerCA <Michael.Bauer2@broadcom.com>
Update `zowe plugins install` command to use the current db2 plug-in .tgz package name. 

Update plug-in install syntax

---

docs/user-guide/cli-installcli.md

Updated cli-installcli.md to fix missing tip and note tags.

Update cli-installcli.md To fix tips and note

---

docs/extend/k8s-extend.md
docs/troubleshoot/k8s-troubleshoot.md
docs/user-guide/k8s-config.md
docs/user-guide/k8s-downloading.md
docs/user-guide/k8s-introduction.md
docs/user-guide/k8s-prereqs.md
docs/user-guide/k8s-using.md

- Improve some descriptions related to k8s setup.
- Add example to create "plugin" image and K8s Job object.

k8s doc improvements

---

docs/getting-started/release-notes/v1_24.md
docs/getting-started/release-notes/v1_25.md

Add release demo and blog links

---

docs/user-guide/systemrequirements-zosmf.md

**fix** https://github.com/zowe/api-layer/issues/1835

describe workaround for stuck JWT in zosmf

---

docs/getting-started/zowe-architecture.md

Remove duplicate section/general language refactor

---

docs/extend/extend-apiml/implement-new-saf-provider.md
docs/user-guide/configure-zos-system.md

Signed-off-by: Vit Tomica <vit.tomica@broadcom.com>
Related PRs:
https://github.com/zowe/zowe-install-packaging/pull/2475
https://github.com/zowe/zowe-common-c/pull/257
https://github.com/zowe/zss/pull/370

Add SAF IDT configuration description

---

docs/user-guide/systemrequirements-zos.md

-Modified the invalid link of Creating a PKC#11 Token.
Fixes #1917 
Modified the link to be the valid one. 

modify-link

---

docs/user-guide/api-mediation-metrics-service.md

Fix note formatting

---

docs/user-guide/systemrequirements-zos.md

API ML memory requirements

---

docs/extend/extend-apiml/create-apiml-extension.md

Document the API ML sample extension

---

docs/user-guide/api-mediation-metrics-service.md
package-lock.json

- added the demo video for APIML metrics service
- added the demo video for APIML metrics service
close #1953 

added the demo for APIML metrics service

---

docs/user-guide/configure-certificates-keystore.md
docs/user-guide/systemrequirements-zos.md

This PR removes all PKCS#11 token mentions because ZSS doesn't use it anymore(see https://github.com/zowe/zss/issues/365)

Remove PKCS#11 token mentions

---

docs/extend/extend-apiml/create-apiml-extension.md

Include new extension variables in the apiml extension documentation, and generalize the documentation so future documentation can easily be added.

Add apiml extension paths documentation

---

docs/troubleshoot/app-framework/app-mustgather.md
docs/troubleshoot/app-framework/app-troubleshoot.md

- add an error message code for loopback issue
Close #1480 by adding a new error message code section. 

add troubleshoot tip for SWED0171W not having a loopback address issue

---

docs/getting-started/user-roadmap-app-framework.md
docs/troubleshoot/app-framework/app-troubleshoot.md

- add a troubleshooting tip to application framework
- correct a typo
- Add a troubleshooting tip about the slow performance of VT terminal on SSH. 
- Correct a typo
I think there can be more specific steps about how to use telnet to connect the system for users. If necessary, please let me know and I will add them up. 
fix #1226 

add troubleshooting tip for the slow performance of VT terminal on SSH

---

docs/getting-started/release-notes/v1_27.md

Updated Zowe Application Framework based on changelogs.

Have updated v1_27.md

---

docs/extend/extend-apiml/websocket.md
sidebars.js

stomp support

---

docs/extend/extend-api/existingAPI.md
docs/extend/extend-apiml/api-mediation-components-of-URL.md
docs/extend/extend-apiml/api-mediation-routing.md
docs/extend/extend-apiml/api-mediation-security.md
docs/extend/extend-apiml/api-mediation-versioning.md
docs/extend/extend-apiml/onboard-direct-eureka-call.md
docs/extend/extend-apiml/onboard-plain-java-enabler.md
docs/extend/extend-apiml/onboard-static-definition.md
docs/extend/extend-apiml/service-information.md
docs/extend/extend-apiml/websocket.md
docs/getting-started/zowe-architecture.md
docs/troubleshoot/troubleshoot-apiml.md
docs/troubleshoot/troubleshoot-zos.md
docs/user-guide/api-mediation-api-catalog.md
docs/user-guide/api-mediation/api-gateway-configuration.md
docs/user-guide/api-mediation/api-mediation-internal-configuration.md
docs/user-guide/configure-instance-directory.md
docs/user-guide/verify-zowe-runtime-install.md
docs/user-guide/zowe-getting-started-tutorial.md

Fix inconsistencies around API ML in v2

---

docs/extend/extend-apiml/create-apiml-extension.md

Fix API ML extension doc

---

docs/user-guide/cli-install-cli-checklist.md
docs/user-guide/cli-using-configuring-global-profiles.md
docs/user-guide/cli-using-creating-global-team-profiles.md
docs/user-guide/cli-using-creating-global-user-profiles.md
docs/user-guide/cli-using-initializing-global-configuration.md
docs/user-guide/cli-using-using-daemon-mode.md
sidebars.js

checking in work-in-progress

---

docs/user-guide/cli-install-cli-next.md
docs/user-guide/cli-install-cli-nodejs-windows.md
docs/user-guide/systemrequirements-cli.md
sidebars.js

PR to replace PR #2016

---

docs/user-guide/configure-instance-directory.md

Add description of port offset configuration for components.

Add doc of port offset

---

docs/user-guide/configure-sysplex.md
docs/user-guide/install-nodejs-zos.md
docs/user-guide/install-zowe-smpe.md
docs/user-guide/systemrequirements-zos.md

- remove node v8 support information
- add node v16 support informaiton

introduce node v16 support

---

docs/getting-started/release-notes/v1_23.md
docs/getting-started/release-notes/v1_24.md
docs/getting-started/release-notes/v1_25.md
docs/getting-started/release-notes/v1_26.md
docs/getting-started/release-notes/v1_27.md
docs/getting-started/release-notes/v1_27_1.md
sidebars.js

explain v1.27.1

---

docs/user-guide/api-mediation/api-gateway-configuration.md

Add zosmf change pw doc

---

docs/user-guide/cli-install-cli-checklist.md
docs/user-guide/cli-using-configuring-global-profiles.md
docs/user-guide/cli-using-creating-global-team-profiles.md
docs/user-guide/cli-using-creating-global-user-profiles.md
docs/user-guide/cli-using-using-profiles.md
docs/user-guide/systemrequirements-cli.md
sidebars.js

Work in Progress

---

docs/user-guide/api-mediation-api-catalog.md
docs/user-guide/api-mediation/api-gateway-configuration.md

Add note for the sysprog about password change 

---

docs/user-guide/api-mediation-api-catalog.md
docs/user-guide/api-mediation/api-gateway-configuration.md

Add pw change note to v2

---

docs/getting-started/release-notes/v1_27_2.md

Signed-off-by: Tom Zhang <tom.yczhang@gmail.com>

remove 1.27.2 server component changes

---

docs/extend/extend-apiml/api-mediation-security.md

Refactors the language describing one of the client certification authentication methods.

refactor client certification authentication methods

---

docs/appendix/zowe-cli-command-reference.md

Added a statement that describes the content in the help also includes help for zowe conformant plug-ins
@MikeBauerCA: SME Review
@nannanli: To approve the merge to master

Update to Reference > Zowe CLI command reference guide

---

docs/extend/extend-apiml/api-mediation-vsam.md
docs/troubleshoot/troubleshoot-apiml-error-codes.md

Review API ML content in v2 doc

---

docs/appendix/server-component-manifest.md

Signed-off-by: Pablo Hernán Carle <pablo.carle@broadcom.com>
Resolve https://github.com/zowe/api-layer/issues/1986
Add `basePackage` attribute for Zowe API ML extensions

Add base package attribute for extensions

---

api_definitions/gateway.json
docs/extend/extend-apiml/api-mediation-message-service.md
docs/extend/extend-apiml/custom-metadata.md
docs/user-guide/api-mediation/diagrams/rest-api-components-sample.svg

Upgrade onboarding overview

---

docs/user-guide/api-mediation-metrics-service.md

Update config variables for v2 for the metrics service.

Update metrics service documentation for v2

---

docs/user-guide/ze-usage.md

- corrected two punctuation marks in the doc as shown
Corrected some punctuation marks for the Using Zowe Explorer doc. 

corrected the punctuation

---

docs/user-guide/cli-using-daemon-mode.md

see the comments in the commits.
Add Mike B. as approver after we finalize the content.

Jabauman us785469 daemon mode testfix

---

docs/user-guide/ze-ftp.md
sidebars.js

adding ftp ext to v2

---

docs/extend/extend-cli/cli-devTutorials.md
docs/extend/extend-cli/cli-installing-sample-plugin.md
docs/extend/extend-cli/cli-setting-up.md
docs/extend/migrate-extensions.md
docs/getting-started/cli-getting-started.md
docs/getting-started/migrate-cli.md
docs/getting-started/migrate-instance.md
docs/getting-started/user-roadmap-zowe-cli.md
docs/user-guide/cli-db2plugin.md
docs/user-guide/cli-install-cli-checklist.md
docs/user-guide/cli-installcli.md
docs/user-guide/cli-updatingcli.md
docs/user-guide/cli-using-initializing-team-configuration.md
docs/user-guide/cli-using-integrating-apiml.md
docs/user-guide/cli-using-using-profiles.md
docs/user-guide/install-cli-via-proxy.md
docs/user-guide/systemrequirements-cli.md
package-lock.json
sidebars.js

@JTonda  - i am checking work into the v2 preview branch.  Can you please OK my PR?
Thx!

checking in work in progress

---

docs/extend/extend-apiml/onboard-static-definition.md
docs/user-guide/configure-instance-directory.md

Update v1 documentation on adding static definition directories for v2.

Update v1 static defs file var to v2

---

docs/user-guide/api-mediation/discovery-service-configuration.md

Document service prefix mapper for v2 conformance compatibility

---

docs/getting-started/cli-getting-started.md

fixed broken links in the CLI Quick Start article

fixed broken links

---

docs/appendix/zowe-yaml-configuration.md
docs/user-guide/api-mediation/discovery-service-configuration.md

Fix the service id prefix replacer doc

---

docs/extend/extend-apiml/api-mediation-caching-service.md
docs/extend/extend-apiml/implement-new-saf-provider.md
docs/troubleshoot/troubleshoot-apiml-error-codes.md
docs/troubleshoot/troubleshoot-apiml.md
docs/user-guide/api-mediation/api-gateway-configuration.md
docs/user-guide/api-mediation/api-mediation-internal-configuration.md

Update apiml variables to v2 version and instance.env to zowe.yaml for pages that will be kept in v2.

Update apiml documentation for v2

---

docs/getting-started/cli-getting-started.md
docs/user-guide/cli-using-sharing-team-config-files.md
docs/user-guide/cli-using-team-configuration-team-leaders.md
sidebars.js

@t1m0thyj 
Request review so that we can push the new topic into the preview branch.

added new topic: Sharing team configuration files

---

docs/appendix/server-component-manifest.md
docs/extend/packaging-zos-extensions.md
docs/extend/server-schemas.md

The logic that enforces this is not yet in the codebase, but it will be quite soon, so I'm putting this PR out as a line in the sand to describe how things will work, and I suggest we get this into the doc sooner than later as a disclaimer that it is coming.

Server schema explanation

---

docs/user-guide/cli-configuringcli-ev.md

@gejohnston 
Updated the EV's for the daemon mode.  You can preview the file here:
https://github.com/zowe/docs-site/blob/jabauman-daemon-EV/docs/user-guide/cli-configuringcli-ev.md

updated daemon mode EV's per #1365

---

docs/extend/extend-cli/cli-devTutorials.md
docs/extend/extend-cli/cli-extending-a-plugin.md
docs/extend/extend-cli/cli-implement-profiles.md
docs/extend/extend-cli/cli-setting-up.md
docs/user-guide/systemrequirements-cli.md

@t1m0thyj 
Please review the cli extending articles.
thx

updates to the extending section

---

docs/user-guide/cli-db2-install-m1.md
docs/user-guide/cli-db2plugin.md
sidebars.js

@awharn 
Please review....
You can view previews here:
https://github.com/zowe/docs-site/blob/jabauman-cli-m1-processor/docs/user-guide/cli-db2plugin.md
https://github.com/zowe/docs-site/blob/jabauman-cli-m1-processor/docs/user-guide/cli-db2-install-m1.md
Please review the description for why you need to configure on M1

new m1 article.  Rally: US811759

---

docs/troubleshoot/app-framework/zss-error-codes.md
sidebars.js

This PR adds ZSS error messages.

ZSS error messages

---

docs/user-guide/mvd-configuration.md

Removing TODOs by adding descriptions, this was just missed in the last PR.

Removing TODOs 

---

docs/user-guide/ze-profiles.md

Hi @zFernand0 - 
Please review this PR based on your comments re #2112 
Please base your review on technical accuracy and proper references to global configuration and team config,  After we get the content technically correct, i'll do a deep grammar review.  So please dont approve the PR (yet).
You can preview the file here: https://github.com/zowe/docs-site/blob/jabauman-issue-2112/docs/user-guide/ze-profiles.md

per issue #2112

---

docs/getting-started/release-notes/v2_0.md

Signed-off-by: Jakub Balhar <jakub.balhar@broadcom.net>
There were some changes to the API ML release log that I believe improve the understandability and remove pieces irrelevant to users and extenders.

Clean and update release log for API ML

---

docs/extend/extend-desktop/mvd-auth-plugins.md
docs/extend/extend-desktop/mvd-server-config.md
docs/user-guide/mvd-configuration.md

Signed-off-by: Himani1519 <paripathak80@gmail.com>

server.json --> zowe.yaml

---

docs/user-guide/certificates-setup.md

Small fix - lowercased the uppercased words in the title.

(fix; title) Set up Zowe cert with workflows

---

docs/getting-started/zowe-office-hours.md

Added the Zowe office hours videos for extenders. 
Thanks for your review. 

Add zowe office hours

---

sidebars.js

Add discovery service configuration to sidebars.js

add discovery service config to sidebars.js

---

docs/appendix/bill-of-materials.md

Minor tweaks for SBOMS in v2; howto use hash, modified component list, and updated SBOMs for final, promoted artifacts. Minor differences as compared to RC2 SBOM.
Signed-off-by: MarkAckert <mark.ackert@broadcom.com>

update bom with tweaks for 2.0

---

docs/troubleshoot/cli/zosmf-cli.md
docs/user-guide/cli-using-sharing-team-config-files.md

previous PR did not correct the formatting in "Sharing team config files"
@JTonda  Resubmitting PR

Jabauman v2 fix formats

---

docs/appendix/zowe-yaml-configuration.md
versioned_docs/version-v1.28.x/troubleshoot/troubleshoot-apiml.md

Add information about enabling debug logging for explorer APIs.

Add explorer APIs debug logging

---

docs/user-guide/ze-ftp.md

Preview:
https://github.com/zowe/docs-site/blob/jabauman-z-exp-fix/docs/user-guide/ze-ftp.md#unsupported-data-set-functionalities

updated bullets in ## Unsupported data set functionalities

---

docs/troubleshoot/cli/mustgather-cli.md

@KevinLoesch1 >  please approve and i'll merge ASAP.

fixed broken link in Gathering information to troubleshoot Zowe CLI

---

docs/getting-started/zowe-office-hours.md

- updated the video recording for CLI
updated the recording link on https://docs.zowe.org/stable/getting-started/zowe-office-hours 

update the video recording link

---

docs/user-guide/k8s-using.md

The doc is inaccurate which was applicable for v1. Updated for v2.

fix kubectl apply workload command

---

docusaurus.config.js

- removed the bar on the top for the new features
removed the bar on the top of the pages in docusaurus.config.js
fix #2228 
close #2228 

remove the bar of new features

---

docs/getting-started/release-notes/v2_1_0.md

First pass at the CLI/Imperative v2.1 changelog

First pass at the CLI/Imperative v2.1 changelog

---

docs/user-guide/initialize-zos-system.md
docusaurus.config.js

Fix the link for mvs datasets

---

docs/user-guide/initialize-zos-system.md
docs/user-guide/installandconfig.md

Few install/configure tips we collected when working with customer. @CarsonCook 

few tips on install/configure

---

docs/user-guide/api-mediation/api-mediation-overview.md

- fixed a broken link on the APIML overview page
fix a broken link on the 

fix a broken link

---

docs/getting-started/release-notes/v2_2_0.md

Created the sections for each component in the Release Notes article.
@nannanli - can you please approve?
I created the framework so the we all use the same structure.

created framework for the change log (rel notes)

---

docs/user-guide/cli-using-initializing-team-configuration.md

@t1m0thyj 
re: https://github.com/zowe/docs-site/issues/2276

changed zowe config init ... to ... zowe config init --global-config

---

docs/user-guide/cli-installcli.md

@t1m0thyj 
https://github.com/zowe/docs-site/blob/jabauman-%232275/docs/user-guide/cli-installcli.md

To fix broken links in Installing CLI

---

docs/user-guide/k8s-config.md

Signed-off-by: Tom Zhang <14881754+FlappiTomic@users.noreply.github.com>

updates on k8s config doc

---

docs/troubleshoot/launcher/launcher-error-codes.md

fixes #2288

---

src/css/custom.css

style: Enhance doc version banner

---

docs/user-guide/cli-cicsplugin.md

Signed-off-by: anaxceron <ana.ceron@broadcom.com>
Updated creating user profile steps. Includes added topics Create Plugin Profile Using a Config File; Create Profiles Using a Command.

Updated to include V2 profiles

---

docs/user-guide/cli-mqplugin.md

Signed-off-by: anaxceron <ana.ceron@broadcom.com>
Updated plugin to include team profile configuration

Updated plugin to include team profile configuration

---

docs/troubleshoot/app-framework/appserver-error-codes.md

update reason 75-100

---

docs/extend/extend-apiml/api-mediation-redis.md

Add documentation for `redis.sentinel.enabled` field.

Add redis sentinel enabled field
